### ISSUE TITLE
dokustreamer

### ISSUE THREAD

**Issue by polojoe** [StoneOffStones/plugin.video.xstream#100]
I can't watch documentaries of the dokustreamer site.
I'm on nightly branch.
Could someone please check this?

**Comment by ghost** [comment]
Is fixed since yesterday:

https://github.com/StoneOffStones/plugin.video.xstream/commits/nightly

Could u try the newest nightly and close the issue if ur are fine? :)

**Comment by polojoe** [comment]
Works now, thanks much!
