### ISSUE TITLE
[UpdateManager] Updatefehler Master

### ISSUE THREAD

**Issue by sraedler** [StoneOffStones/plugin.video.xstream#14]
Der UpdateManager kann sich nicht von Master auf Beta oder Beta auf Master Updaten, da sonst folgender Fehler auftritt:

> from resources.lib import common
>                                               File "C:\Users\admin\AppData\Roaming\Kodi\addons\plugin.video.xstream\resources\lib\common.py", line 5, in <module>
>                                                 addon = xbmcaddon.Addon(id = addonID)
>                                             RuntimeError: Unknown addon id 'plugin.video.xstream'.
>                                             -->End of Python script error report<--

Grund dafür ist, dass die AddonID geändert wird.

Sollte nun eine einheitliche ID gefunden werden oder wie lösen wir das Problem?

**Comment by sraedler** [comment]
Was denkt ihr? @Lynx187 @StoneOffStones @Viper2k4

**Comment by Ston3s** [comment]
Vor meiner Seite aus spricht absolut nichts dagegen.
Hatte bereits im Forum gefragt wie man dazu vorgehen sollte.

An welche Art von einheitliche Versions-Benennung hast du da gedacht?

**Comment by sraedler** [comment]
Ich würde es einfach "plugin.video.xStream" nennen, seh da nicht den mehrwert wenn in der ID Beta steht.

**Comment by ghost** [comment]
Weil so doppelt installationen möglich sind?

**Comment by Ston3s** [comment]
Genau, das war der Grund wieso es überhaupt umbenannt wurde...

**Comment by ghost** [comment]
Ja eben. Daher sollte es auch so bleiben :)

**Comment by sraedler** [comment]
aber dann ist es nicht möglich zwischen Master und beta zu wechseln. außer einer von euch weiß eine Möglichkeit

**Comment by ghost** [comment]
Wieso sollte es nicht möglich sein? Du kannst doch sehen welche Version grade aktuell ist und ensprechend Handeln.

**Comment by sraedler** [comment]
aber was ist entsprechend handeln?

heißt das es muss zwei ids haben und beim initiieren die Settings für beide versionen anlegen oder wie soll das gehen?

**Comment by ghost** [comment]
Ich bin nicht in dem Thema drin. Aber z.b die ID vor dem Update auf die Ziel ID anpassen oder sowas in der Art.

**Comment by Ston3s** [comment]
Das hört sich aber nach sehr kompliziert umzusetzen an.
Wenn man die ID wieder anpassen würde könnte man aber zu jeder Zeit zwischen Master und Beta switchen.

**Comment by Ston3s** [comment]
Würde dafür sprechen...

**Comment by sraedler** [comment]
und man benötigt durch das switchen keine Doppelinstallation mehr und dadurch wären die Einstellungen für beide Versionen gleich.

**Comment by Ston3s** [comment]
Rein technisch gesehen gibt es irgend eine Möglichkeit den anderen Namen der Beta beizubehalten?

**Comment by sraedler** [comment]
das weiß ich nicht.

aber theoretisch müsste die Common erweitert werden um eine Abfrage ob die Einstellung bzw. die addonid vorhanden ist und wenn nicht muss es initialisiert werden. Das heißt Neuanlagen bei erstwechsel zu Beta oder Master. 

Versteh aber den Grund nicht wofür die separaten ids und dadurch Einstellungen benötigt werden, da sowieso innerhalb Sekunden gewechselt werden kann (natürlich erst wenn der updatemanager mal im Master enthalten ist)
Und denk es gibt keinen Grund für Beta und Master unterschiedliche Einstellungen zu haben.

Oder irre ich mich?

**Comment by Ston3s** [comment]
Was denkt Lynx187 dazu?

**Comment by Ston3s** [comment]
Hab nochmal drüber nachgedacht. Wäre es wirklich so, dass man von der Beta auf die Master jederzeit wechseln könnte. Die meiste Zeit wäre die Master ja eine niedrigere Version als die Beta. Klappt das dann auch?!

**Comment by sraedler** [comment]
da hast du recht, das müsste noch eingebaut werden dass bei einem
Wechsel 100%ig gepullt wird.

DONE

**Comment by Ston3s** [comment]
Gibt an der Stelle noch weiters zu berücksichtigen?!

Sollte eine Beschränkung eingebaut werden damit nur von einer neueren Beta auf einer älteren Master-Version gedowngradet werden kann und nicht umgekehrt?!
Sprich von einer neueren Master auf eine ältere Beta.
Nicht das der Update-Zyklus am Ende in einer Endlosschleife stattfindet.
Vielleicht auch ein Gedankenfehler von mir, wollte aber trotzdem nachhaken!

Ganz nebenbei, die AddonID wurde bereits angepasst und sollte keine Probleme mehr bereiten.
Sobald alle eventuellen Probleme beseitigt sind könnte der Punkt an geschlossen werden.

**Comment by ghost** [comment]
Gegen ein Downgrade spricht eigentlich nichts. Nur sollten dann ggf. die Settings gelöscht werden. Denn neue Settings mit alter Version könnten ggf. mal Fehler verursachen.

Falls man das nicht möchte könnte man natürlich auch einen Blocker einbauen. Oder wenigstens ein Meldung nach dem Motto "Ein Downgrade könnte zu blablalba führen".

**Comment by sraedler** [comment]
hm, bin mir nicht sicher ob man ein General downgrade erlauben sollte. Denn der Master ist ja Stable, und die Beta wird immer weiter als der Master sein, daher ist glaub kein bedarf, das von Master auf Beta gedowngraded wird.

Und wenn jemand auf eine ältere Version will, dann würde ich eher Update off und eine ältere Version von Github herunterladen und installieren. Diesen Fall sehe ich im Moment nicht notwendig als Feature.

Aber wenn ihr das wollt können wir das einbauen. Müsste dann nur wissen was gewünscht ist oder jemand von euch muss es ändern.

**Comment by ghost** [comment]
Das meine ich nicht. Es sollte halt nur möglich seint z.b von xStream v1 auf xStream v2 Beta und wieder zurück (weil Beta z.b blöd). Das meinte ich.

**Comment by ghost** [comment]
Btw, wenn man die Zip der Beta installiert und auf ein frisches Kodi packt. Wird ersten start direkt ein Download ausgeführt und danach erscheint ein Fehlermeldung:

"SyntaxError: invalid syntax (<string>,line1) /plugin.video.xstream-beta/.gitattributes"

Der Fehler geht nur wegen wenn man in die Einstellungen geht und auf "Beta" stellt.

**Comment by sraedler** [comment]
Hm, aber das ist aber schwer zu realisieren...

Würde da eher nach dem Motto gehen wenn man wirklich die alte Version will muss man neuinstallieren.

@Viper2k4 danke, weiß gar nicht woher der typo kommt, aber sollte nun funktionieren, siehe  d8f4ff1

**Comment by ghost** [comment]
Können wir auch gern machen (macht FireStarter z.b auch so). Wenn man da bei Kodi sich z.b die Beta installiert (Kodi 15 Beta 14 z.b) und dann wieder auf stable stellt gibt es erst wieder ein Update bei Kodi 16.

**Comment by sraedler** [comment]
@Viper2k4 mir ist vor 5 Minuten der selbe Gedanke gekommen!
Das Problem mit dem "downgraden" ist, dass wir den Master als default haben, das heißt wenn ein Benutzer xStream neuinstalliert und nicht direkt die Einstellungen auf Beta oder Off ändert, dann wird direkt die Master geladen, bei welcher z.B. HDStream fehlt.

Werde das Downgraden daher wieder herausnehmen!

**Comment by Ston3s** [comment]
War mit dem Master als default aber so mit Lynx187 abgestimmt ;)

**Comment by sraedler** [comment]
Es ist ja weiterhin default, aber wenn die Beta neuer ist, dann wird nicht automatisch auf Master downgraded

**Comment by Ston3s** [comment]
Milestone definiert ;)

**Comment by Ston3s** [comment]
Leider lädt er die Beta nicht wenn ich von Nightly auf Beta schalte.

Von Nighly sollte er in beide Richtungen wieder zurück switchen können da diese meist keinen stabilen und zuverlässigen Stand beinhaltet...

**Comment by ghost** [comment]
Sehe ich anders.

Wenn jemand von Nighly auf Beta zurückstellt. Sollte erst wieder ein Update durchlaufen wenn die Update neuer ist als die aktuell installierte Nighly.

So hatten wir das eigentlich auch besprochen weiter oben oder?

**Comment by Ston3s** [comment]
Ja stimmt, hast recht...

**Comment by sraedler** [comment]
Dann würde ich sagen closed, bzw. bei weiteren anliegen diesbezüglich ein neuen Issue machen.
