### ISSUE TITLE
Central Settings-Folder 

### ISSUE THREAD

**Issue by Ston3s** [StoneOffStones/plugin.video.xstream#16]
Hallo zusammen,

aktuell gibt es insgesamt drei Ordner über die man auf die Einstellungen für das Addon xStream, UrlResolver und den Metahandler zugreifen kann.
Wäre es nicht angenehmer und schöner wenn man nur einen Ordner Settings im "Home" Verzeichnis von xStream hätte und in diesem die ganzen weiteren Ordner integriert wären.

Das würde den User so wenig wie nur möglich vom eigentlichen Zweck und somit den eigentlichen Inhalten des Addons bzw. der Seiten ablenken.

Es wäre schön wenn mich dabei jemand unterstützen könnte oder vielleicht ein paar Tipps über hat ;)

**Comment by ghost** [comment]
Ich würde das gern anders Lösen.

Und zwar mit Trennlinien zwischen Plugins,Suche und Settings

Sprich:

Seite 1
Seite 2
Seite 3
Seite 4

---

Globale Suche

---

Settings 1
Settings 2

(Optimal wäre hier wenn die Trennlinine/Leerzeile beim Navigieren übersprungen wird wenn das Möglich ist. Z.b so wie in den Kodi-Settings selbst, dort ist die Linie zwischen den Punkten einfach Dicker)

Btw. kann man für die Suche auch ne Icon festlegen? Wäre irgendwie cool wenn man direkte sieht das die Suche sucht :)

**Comment by Ston3s** [comment]
Weiß nicht ob ich das richtig verstanden habe. Das ganze bezieht sich eher auf eine Listenansicht. Wie ist das wenn es in anderen Viewtypes mit den Icons angezeigt wird...

**Comment by sraedler** [comment]
Finde die Idee super das so abzugrenzen :+1: 

Ich versuch mal da eine Trennlinie hinzubekommen.

Das Icon geht ganz leicht, muss nur ein png erstellt werden, wird dann in der xstream.py in Zeile 232 hinzugefügt, ist also kein Stress 

Edit: die Trennlinie ist etwas komplizierter, wenn sie eine Zeile überspringen soll, evtl. kann da Lynx helfen

**Comment by Ston3s** [comment]
Sorry kann es immer noch nicht einschätzen. Das mit dem Icon empfinde ich unnötig, da je nach Skin bereits was angezeigt wird...

**Comment by sraedler** [comment]
@StoneOffStones  Es kommt drauf an, was wir als Icon erachten. Vor dem "Globale Suche" ist es nicht nötig, aber das Thumbnail auf der rechten Seite, was momentan der Ordner ist, könnte schon durch ein "Suchbild" ersetzt werden

**Comment by Ston3s** [comment]
Ist der Gedanke von viper2k4 nicht sehr stark abhängig vom verwendeten Skin.
Was ist absolut vermeiden will ist eine fehlerhafte Darstellung weil du nicht Continium als Standard Skin verwendest!

**Comment by sraedler** [comment]
Soll dann jetzt an einer Trennlinie gearbeitet werden oder wollt ihr ein Ordner für die Settings machen?

**Comment by Ston3s** [comment]
Könnt ihr mir bitte erklären wie genau die Darstellung mit Trennlinie in anderen Skins in Ansichten außerhalb von Listenansichten aussieht?

Gibt es da dann Probleme, das wäre für mich ein Todschlag-Argument!

**Comment by Ston3s** [comment]
Mir reicht der Ordner erstmal für die 2.1.16 voll aus ;)

**Comment by Ston3s** [comment]
Das mit den Trennlinien kann ich mir wirklich gut in dieser Ansicht vorstellen, da ist es sogar eine ganz wunderbare Idee!
![bildschirmfoto 2016-03-24 um 21 01 25](https://cloud.githubusercontent.com/assets/12751497/14029772/5424b0b2-f204-11e5-998b-cd2ceaba8331.png)

Aber wie sieht das ganze bei z.B. dieser Ansicht aus?!
![bildschirmfoto 2016-03-24 um 21 00 57](https://cloud.githubusercontent.com/assets/12751497/14029803/7c67971a-f204-11e5-8629-a7700e5f443d.png)

Ich nutze gerade einen Skin namens fTV der die FireTV ziemlich gut nachstellt.
Dort weiß ich auch nicht wie Linien einzubauen wären und dazu sind die Logos für die Einstellungen ganz schlicht und wunderbar!
![bildschirmfoto 2016-03-24 um 21 00 11](https://cloud.githubusercontent.com/assets/12751497/14029844/b5c5dce2-f204-11e5-8034-6f39f0db9290.png)
![bildschirmfoto 2016-03-24 um 21 12 07](https://cloud.githubusercontent.com/assets/12751497/14029906/225d4dea-f205-11e5-85e3-5de5e269c15b.png)

Ich hoffe Ihr versteht jetzt etwas besser warum ich mir das mit den Linien nur schwer als universelle Lösung vorstellen kann.

**Comment by sraedler** [comment]
Ja da stimm ich dir vollkommen zu!

Sollen wir dann einen Ordner Settings machen ?

@StoneOffStones du bist doch ein guter Designer, kannst du ein Logo für die Globale Suche und eines für die Settings machen? Dann würde ich das einbauen..

**Comment by Ston3s** [comment]
Ordner wäre spitze.
Wenn man ihn universell für englisch und deutsch erstellt sollte dieser Settings lauten aber wenn es möglich ist den Namen je nach Spracheinstellung unterschiedlich auszugeben würde ich Settings bzw. Einstellungen favorisieren.

Erstmal für die Komplimente aber ihr überschätzt mich ;)
Wenn dann würde ich etwas ganz schlichtes in Betracht ziehen.
Da gibt es teilweise auch schon ansprechende Templates die eventuelle das sind was wir brauchen.
Da brauch ich aber etwas Zeit für.
Kann ich ja dann wenn es soweit ist nachreichen...

**Comment by sraedler** [comment]
Ok, dann werd ich die Ordner angehen, wenn ich zeit hab (heute nachmittag)

**Comment by sraedler** [comment]
Hab einen Settingsfolder gemacht und die Globale Suche an den Anfang, finde ich schöner, denn wenn man einen Film schauen will egal woher und alle Plugins aktiviert hat ist bis nach unten Scrollen blöd.

TODO: Bild für die Suche

1db2469

**Comment by Ston3s** [comment]
Sehr gut, Danke!

Weiß aber nicht ob das mit der Suche zum Anfang so toll ist. Sinnvoll vielleicht jedoch ist es ein allgemeiner Ordner wie die Settings. Deshalb fühlt sich das für mich hinter richtiger an.

Vielleicht sollte man dem User die Wahl über eine entsprechende Option in den Einstellungen selber überlassen wo die Suche positioniert wird?!

**Comment by sraedler** [comment]
Ja eine Setting wäre schon gut!

Aber ein Logo für die Suche wäre noch besser

**Comment by Ston3s** [comment]
Bin doch schon dran ;)

**Comment by Ston3s** [comment]
**Vorschlag1**
Kann man jetzt hinterm weißen Hintergrund nur schlecht einschätzen.
Müsste man ein Screenshot in Kodi machen wenn diese richtig hinterlegt sind.
Globale Suche:
![global_search1](https://cloud.githubusercontent.com/assets/12751497/14059158/94fc1342-f339-11e5-82a1-496218a34035.png)

Settings:
![settings1](https://cloud.githubusercontent.com/assets/12751497/14059161/9da14f62-f339-11e5-8c4f-f3fd72f2e034.png)

**Comment by Ston3s** [comment]
Vorschlag2:

![global_search2](https://cloud.githubusercontent.com/assets/12751497/14059311/7c504544-f33d-11e5-8e45-56694b3fef4d.png)
![settings2](https://cloud.githubusercontent.com/assets/12751497/14059312/7c766828-f33d-11e5-9fe8-13960983ae45.png)

**Comment by Ston3s** [comment]
Ich habe eben gerade auch in eine weitere Richtung recherchiert.
Mir ist das ein wenig zu statisch, wenn ich z.B. den Skin ändere passt eventuell die Optik nicht mehr.
Bei den Einstellungen wird ja bereits ein dynamisches System verwendet es wird, da wird die DefaultAddonService.png vom jeweilig verwendeten Skin geladen.
Ehrlich gesagt finde ich das so viel besser!!!

Bin gerade auf der Suche welche DefaultIcons dafür prädestiniert wären.
Melde mich später!

**Comment by Ston3s** [comment]
Für die Globale Suche empfinde ich das **DefaultAddonWebSkin** am sinnvollsten.
Habe natürlich dazu in Confluence geschaut aber auch in den Skin Estuary, welcher ab Krypton verwendet wird.
OnTop habe ich als Britenabsicherung noch in einen dritten Skin geschaut um nochmals sicherzugehen!
Werde jetzt die verschiedenen Icons für oben genannte DefaultIcon hochladen damit man sich dazu einen Eindruck machen kann.

Confluence:
![defaultaddonwebskin](https://cloud.githubusercontent.com/assets/12751497/14059395/07dc1244-f340-11e5-9587-3212b44a3321.png)

Estuary:
![defaultaddonwebskin](https://cloud.githubusercontent.com/assets/12751497/14059397/0c48ab94-f340-11e5-8be1-aff93d8f5ef4.png)

fTV:
![defaultaddonwebskin](https://cloud.githubusercontent.com/assets/12751497/14059401/20531ae8-f340-11e5-836b-c1388ed33e61.png)

**Comment by Ston3s** [comment]
Für die Settings wurde bisher **DefaultAddonService** verwendet:
![defaultaddonservice](https://cloud.githubusercontent.com/assets/12751497/14059417/7522b498-f340-11e5-9e76-1fcc81c365bf.png)
![defaultaddonservice](https://cloud.githubusercontent.com/assets/12751497/14059421/820b271c-f340-11e5-961c-d6ead5dfd9cb.png)
![defaultaddonservice](https://cloud.githubusercontent.com/assets/12751497/14059422/84528cd6-f340-11e5-9582-348bc273722f.png)

Als alternative könnte man auch den **DefaultAddonHelper** verwenden:
![defaultaddonhelper](https://cloud.githubusercontent.com/assets/12751497/14059426/a5687732-f340-11e5-8848-195eea1a9109.png)
![defaultaddonhelper](https://cloud.githubusercontent.com/assets/12751497/14059427/a9d6226a-f340-11e5-802d-c1234b3ddb8e.png)
![defaultaddonhelper](https://cloud.githubusercontent.com/assets/12751497/14059429/ad5de1a2-f340-11e5-956a-cfcca795b16b.png)

**Comment by Ston3s** [comment]
Für den Metahandler würde ich **DefaultAddonTvInfo** nehmen:

![defaultaddontvinfo](https://cloud.githubusercontent.com/assets/12751497/14059469/d3e2a97e-f341-11e5-9f53-d9423a0acba7.png)
![defaultaddontvinfo](https://cloud.githubusercontent.com/assets/12751497/14059470/d583aef4-f341-11e5-88e0-34f8aec5c949.png)
![defaultaddontvinfo](https://cloud.githubusercontent.com/assets/12751497/14059472/d722736c-f341-11e5-8bf5-f1bd08f28eec.png)

**Comment by Ston3s** [comment]
Und für den URLResolver bietet sich **DefaultMusicPlaylists** an
Nicht wundern die VideoPlaylist hat eine für unsere Bedürfnisse schlechte Formfaktor. (Poster-View)

![defaultmusicplaylists](https://cloud.githubusercontent.com/assets/12751497/14059483/367da44e-f342-11e5-86dc-c59ef05eb125.png)
![defaultmusicplaylists](https://cloud.githubusercontent.com/assets/12751497/14059484/3844b812-f342-11e5-84bb-3658935d5af9.png)
![defaultmusicplaylists](https://cloud.githubusercontent.com/assets/12751497/14059486/39426c1e-f342-11e5-8cf1-e599ab384677.png)

**Comment by Ston3s** [comment]
Oder man nimmt alternativ für den URLResolver den **DefaultAddonRepository**:

![defaultaddonrepository](https://cloud.githubusercontent.com/assets/12751497/14059496/6835a59a-f342-11e5-9933-5c568abb44bc.png)
![defaultaddonrepository](https://cloud.githubusercontent.com/assets/12751497/14059497/699f949a-f342-11e5-9251-3024c73763b5.png)
![defaultaddonrepository](https://cloud.githubusercontent.com/assets/12751497/14059498/6ad1fb96-f342-11e5-9855-eef248838569.png)

**Comment by Ston3s** [comment]
Habe mal erstmal nach meinem Empfinden entschieden und bereits was gepusht.
Warte auf Feedback...

[new DefaultIcons for GlobalSearch and Settings](https://github.com/StoneOffStones/plugin.video.xstream/commit/c04fd77d6857bd562ec8a819449766c926334292)

**Comment by Ston3s** [comment]
Wäre es jetzt eventuell möglich das Setting bezüglich der Position der Globalen Suche einzubauen? ;)
Dann könnte ich noch heute die Beta3 pushen...

**Comment by Ston3s** [comment]
für die xStream Settings habe ich **DefaultAddonProgram** gewählt:

![defaultaddonprogram](https://cloud.githubusercontent.com/assets/12751497/14059632/6ee23c32-f347-11e5-95fc-b21129a62e60.png)
![defaultaddonprogram](https://cloud.githubusercontent.com/assets/12751497/14059633/709efb3c-f347-11e5-88b2-b7604d953fe8.png)
![defaultaddonprogram](https://cloud.githubusercontent.com/assets/12751497/14059634/723380d0-f347-11e5-9cf6-5710f0186a42.png)

**Comment by Lynx187** [comment]
Also nues Logo gut. Settingsfolder schlecht dann muss man ja einmal mehr klicken und Trennlinien sind wohl ohne neuen View eher nicht möglich und für den Thumbview bspw. auch contraproduktiv.

**Comment by Ston3s** [comment]
Der neue Ordner macht das ganze Erscheinungsbild schlanker.

**Comment by Lynx187** [comment]
1 zusätzlicher Click wegen kosmetischem Schnickschnack. Man könnte die im Prinzip auch ganz weglassen da man alle inzwischen auch mit nativen Kodimittel erreicht.
Ne evtl. noch akzeptable Möglichkeit wäre Pro-View und Normal-View aber im Prinzip nix was wirklich Nutzen bringt.

**Comment by Ston3s** [comment]
Was genau meinst du mit Pro- und Notmal-View

**Comment by Lynx187** [comment]
Na eine Menüansicht mit diesem ordne rund eine wo es direkt zugänglich ist

**Comment by Ston3s** [comment]
Über eine Option in den xStream Settings wählbar.
Das hört sich nach einer vernünftigen Lösung an!

**Comment by Kukolorus** [comment]
Also ich habe eben mal die aktuelle Nightly getestet und finde es eigentlich so wie es ist ganz gut.

Zu dem Thema mit den Trennlinien; Ich finde das auch nicht so gut, aber ich muss sagen das es durch die "vielen" neuen Seiten relativ unübersichtlich sein kann. Wenn ihr versteht was ich meine, am Anfang wenn man xStream öffnet hat man ja die Seiten und die Optionen, Globale Suche gelistet. Ich finde das kann ganz schön unübersichtlich werden, was meint ihr?

**Comment by Ston3s** [comment]
To-Do for Beta4:
Zusätzliche Option in den Setting für zentralisierte Settings. (Wunsch von Lynx187)

**Comment by Kukolorus** [comment]
Ich hätte da nochmal eine Idee, wollte jedoch kein neues Issue öffnen.

Wie wäre es eigentlich wenn man in den Settings auch eine Option hätte, in der man z.B. einen Proxy aktivieren kann, oder irgendwie ein VPN (Dienst).

Ich weiß nicht ob das überhaupt umsetzbar ist, aber vielleicht für die Leute toll die noch mehr Anonymität wollen. Bei Kodi auf einem PC bzw. MAC ist das ja unnötig, da kann man einfach VPN im Hintergrund laufen lassen bzw. Proxy, vielleicht ja für Nutzer des Fire TVs oder so interessant.

Nur mal so ein Gedanke der mir kam^^.

**Comment by sraedler** [comment]
VPN müsste bei Kodi unter den System Settings bei Internet Access gehen.

**Comment by Kukolorus** [comment]
Oh, ok :D

**Comment by Kukolorus** [comment]
Wieso existiert dieser Issue eigentlich noch ? Oder habe ich nur wieder nicht richtig gelesen? :D 

Denn in der Nightly ist doch schon ein Zentraler Settings Ordner eingetragen, oder hat dies noc hnicht das Ergebnis welches gewünscht ist?

**Comment by ghost** [comment]
Sieh Eintrag von StoneOffStones:

"To-Do for Beta4:
Zusätzliche Option in den Setting für zentralisierte Settings. (Wunsch von Lynx187)"
