### ISSUE TITLE
Identical name-logic for site-plugins

### ISSUE THREAD

**Issue by Ston3s** [StoneOffStones/plugin.video.xstream#17]
Mir ist heute aufgefallen das die einzelnen Webseiten eine komplett unterschiedliche Namensgebung aufweisen.
Es wäre doch schön wenn die Darstellung einheitlich und logisch stattfinden würde.
Das ist zwar bei den Logos auch teilweise unterschiedlich, jedoch gibt es dort einen kleinen aber feinen Unterschied. Die gestalterischen Möglichkeiten liegen bei diesen im Rahmen des Gestalters, damit meine ich nicht die von z.B. mir sondern von dem Ersteller des eigentlichen Bildmaterials der Webseite.

Die Namen sollten entweder die gesamte Web-Adresse/Domain mit .to, .com und .tv...

**KKiste.to
BS.to
ddl.me**

...oder den offiziellen und ausgeschrieben Eigennamen enthalten.

**KinoKiste
Burning Series
DirectDownLoad**

Außerdem ist mir aufgefallen, dass die .py-Dateien teilweise noch alte Kennungen haben.
Beispiel ist hier Burning Series. Früher unter burning-series.org erreichbar heiß die Datei auch immer noch so obwohl schon lange unter bs.to wiederzufinden.

Wenn ich was vergessen habe oder weitere Ideen vorhanden bitte anfügen.
Bevor man fleißig ans Umändern geht und vielleicht unbewusst Bezüge zerstört wäre ich über Infos ob etwas bei der Änderung berücksichtigt werden muss sehr dankbar.

**Comment by Ston3s** [comment]
Hallo miteinander,

mich stört die unterschiedliche Namensgebung tatsächlich extrem.
Ich würde dies demnächst sehr gerne anpassen, aktuell denke ich das die Variante mit dem Eigennamen des Anbieters (Webseite) am sinnvollsten ist.
Es ist ja schließlich nicht bs sondern Burning Series und eigentlich auch nicht kkiste sondern KinoKiste. Es stellt sich jetzt nur noch die Frage ob den Namen mit oder ohne Domain?

Bitte an dieser Stelle um euer Feedback...
Reicht es wenn ich den SiteName in der Site.py und in den Settings ändere oder gibt es da noch weitere nötige Anpassungen?

Sage an der Stelle schon mal danke!!!

**Comment by sraedler** [comment]
Den SITE_NAME ändern reicht an der stelle.

Versuch es einfach mal, Ich hab grad ein paar Sachen ausprobiert und nur der Name finde ich richtig schlecht.
Denn ddl.me kennt man, DirectDownLoad kennt kein Mensch

Im Moment ist die Namensgebung eigentlich schon ok. Kannst ja mal Beispiele Machen mit Screenshots.

Könnte mir ein Mix aus Namen und Domain vorstellen

**Comment by Ston3s** [comment]
Ok bei ddl.me verstehe ich das auch. Kannte den vollen Namen vorher auch nicht.
Du hättest die Wiedererkennung aber auch über das Icon wo ganz klar ddl.me aufgezeigt wird.

Mich stört aber auch das bei vielen Seiten die Domain dabei ist und bei anderen wiederum nicht.

**Comment by Ston3s** [comment]
Zitat von  von ddl.me:

bla bla bla ...Euer (D)irect(D)own(L)oad Team

Habe es jetzt mal nur mit Eigennamen in der nightly gemacht.
Ehrlich gesagt finde ich es garnicht so verkehrt, die Logos beinhalten die Domains sowieso sehr oft.
Die würde ich aber nicht anpassen wollen weil diese auch genau so von den Bereitstellern genutzt/vorgesehen waren.

Außerdem wirkt es so viel seriöser, man hat schon fast das Gefühl es könnte sich um eine Alternative zu den großen anderen wie WotchEvor ;) oder Netflix ;) handeln.

**Comment by ghost** [comment]
Ich muss sagen ich finde die Umbenennen nicht gut. Das "könnte" verwirren.

Den so sieht es aus das es bei "HDfilme" HDFilme gibt und bei "DirectDownLoad" kann man was runter laden.

Ich finde mit domain. Haben die Namen mehr sinn ergeben. So sehen sie Teilweise aus wie Funktionsnamen.

**Comment by Ston3s** [comment]
Bei SeriesEver, MoviesEver, Burning-Series, Szene-Streams und weiteren war es schon die ganze Zeit so. 

Möchte nur hierbei einen einheitlichen Weg finden!

Gegenvorschlag...

**Comment by sraedler** [comment]
bin mir auch sehr unschlüssig.

Würde aber eher auf alle mit dem Domainnamen anstatt alle mit Seitennamen angeben.

Das Problem sehe ich auch wie Viper bei ddl.me und auch bei Bundesliga, MoviesEver und SeriesEver, da ist nämlich im Logo keine Domain.

Muss aber dazu sagen, mich hat es davor nie gestört...

**Comment by Ston3s** [comment]
Was ist wenn man Eigenname+Domain macht.
Habe ein Problem mit den ganzen Abkürzungen es ist und bleibt nämlich BurningSeries und nicht BS.
Dann würde ich eher einen Zwitter wie BurningSeries.to wählen...

**Comment by sraedler** [comment]
Kannst du selber entscheiden, wenn es dann nicht passt melden wir uns schon ;)

**Comment by Ston3s** [comment]
Hatte ja bereits entschieden ;)

**Comment by Lynx187** [comment]
Also das Renames kann man zwar machen aber ist im Prinzip auch nur Kosmetik. Wenn es ohnehin etwas dran zu fixen gibt ok wenn nicht dann nicht. Gleiches gilt für das umbennen der .pys nur das da eben wieder ein neues setting angelegt wird.
PS: die Sites solle zukünftig ohnehin so in den Hintergund wandern dass Browsebarkeit und Aussehen nebensächlich sind

**Comment by sraedler** [comment]
@Lynx187 kannst du das etwas beschreiben, was du mit 

> die Sites solle zukünftig ohnehin so in den Hintergund wandern dass Browsebarkeit und Aussehen nebensächlich sind

meinst?

**Comment by Ston3s** [comment]
Da dieses Thema mit #36 verknüpft ist würde ich den Milestone für beide Issues gleichermaßen anpassen.
Habe es erstmal auf die rc1 angepasst, wenn früher fertig kann dies natürlich angepasst werden!
