### ISSUE TITLE
Integrate ddl.me

### ISSUE THREAD

**Issue by Ston3s** [StoneOffStones/plugin.video.xstream#18]
Hallo zusammen,

an dieser Stelle wollte ich nochmals auf die Weiterentwicklung von der de_ddl_me.py aufmerksam machen.
Es wäre toll wenn diese Seite zur Beta3 der Version 2.1.16 bzw. final in die 2.1.16 mit einfließen würde.
Sobald es die anderen Baustellen ermöglichen wäre es schön wenn wir das Site-Plugin entsprechend erweitern könnten.

To-Do:
- Die Suchfunktion auf die Serien erweitern
- Ordnerstruktur der eigentlichen Webseite im Addon abbilden/spiegeln
- Integration des englischen Ablegers en.ddl.me
- Aufwertung des Icons da die bisherige Version eine schlechte Qualität aufweist

**Comment by Ston3s** [comment]
Hab mal ne allgemeine Frage.
Kann man die Seite für beide Sprachen (de.ddl.me & en.ddl.me) innerhalb eines Site-Plugins abbilden oder benötigt man zwei einzelne .pys?

**Comment by ghost** [comment]
Gehen tut das schon über eine py. Man könnte das quasi als Unterordner sehen. Wo mann dann jeweils wählt.

Oder halt nach eingestellter Sprache.

Oder man macht (wenn nötig) zwei Abfragen und packt die Ergebnisse in eine Ausgabe.

Möglichkeiten über Möglichkeiten ^^

**Comment by Ston3s** [comment]
Verknüpft über die Sprachootion in den Einstellungen wäre natürlich dafür die schönste Lösung. 

Also sind nicht zwei Site-Plugins notwendig. Das war nämlich der Grund warum ich die SiteID auf de_ddl_me gesetzt hab. Dachte zur Unterscheidung für die andere "en" Version.

Dann ändere ich heute auf ddl_me, danke dafür.

**Comment by Ston3s** [comment]
Was denkt ihr eigentlich zu der Seite?!
Die gibt es schon ziemlich lange und soll auch zuverlässig sein.

**Comment by sraedler** [comment]
ich will sie behalten
wenn keiner es macht mach ich sie in ein paar Wochen spätestens wenn ich Zeit hab

**Comment by ghost** [comment]
Würde ich mir angucken wenn die BS und HDFilme sache durch ist

**Comment by sraedler** [comment]
:+1:

**Comment by ghost** [comment]
Bin grade schon dran. Nachher kommt was :)

**Comment by Ston3s** [comment]
MEGA!!!

**Comment by sraedler** [comment]
:+1:

**Comment by ghost** [comment]
So erste Version ist online. Könnte ja mal gucken

**Comment by sraedler** [comment]
@Viper2k4 sehr nice, schaut bisher super aus!

Falls du das nicht weißt, versuch mal auf der website und im plugin "Lissi" zu suchen, da gibt es einen bug, denk das ist aber gut machbar.

Baust du die en Version auch mit ein oder ist das noch nicht geplant?

**Comment by ghost** [comment]
fixed https://github.com/StoneOffStones/plugin.video.xstream/commit/a1c0d5751ebb8adf37b1bf12606819216b3702bf

Wie ich das mit der Englischen mache gucke ich mir später an. Werde denke ich erstmal versuchen die Serien einzubauen.

**Comment by sraedler** [comment]
:+1: 

ja, seh ich auch so! 

wenn die domain auf en.ddl.me änderst, dann geht es ja schon, wird also nicht all zu viel noch sein, englisch hinzuzufügen :)

**Comment by Ston3s** [comment]
Bin ja mal echt sprachlos wie du heute abgehst :)

**Comment by Ston3s** [comment]
Mal ne Frage,

so langsam würde ich gerne die Beta3 fertig machen.
Die Namengebung und die Logos für den Settings Ordner würde ich jetzt noch fertig machen und dann hätten wir die Punkte.
Ich stelle die Frage hier weil ich den Anschein habe, dass ddl.de gut vorangeht und sich für mich die frage stellt ob die Seite noch ebenfalls für die Beta3 oder die Beta4 realistisch ist?

**Comment by ghost** [comment]
Wann genau sie fertig ist. Weiß ich nicht. Muss mich ja noch um die Serien kümmern.

Btw. wenn nen Comment machst wo du nur den Text änderst. Schreib mal "fix typo" oder so. Als ich die comments gesehen habe dachte ich schon ich habe nen Fehler drin gehabt.

Btw.@sraedler kannst mal gucken wie man einen Part auswahl vom Prinzip macht? Sprich das man den Part auswählt und dann den Hoster oder umgedreht.

Ich habe in der jetzigen Version schon MultiPart-Support eingebaut. Nur geht das in xStream besser. Habe nur noch nicht rausgefunden wie. Movie4k und BurningSeries machen das glaube ich.

Reicht wenn ich weiß wie es grob geht. Ich schön und angepasst an ddl_me kann ich dann später machen.

**Comment by sraedler** [comment]
Ja werd ich mir anschauen, aber komm wahrscheinlich erst Anfang Mitte nächster Woche genau dazu.

bei Movie4k ist es in Zeile 625 schonmal gemacht.

aber hab mir eh schon gedacht evtl. eine Umstrukturierung zu machen, werde das aber ausführlich noch beschreiben in einem Issue, in welchem das dann ausführlich beschrieben wird.

**Comment by Ston3s** [comment]
Jo fix typo wird beim nächste Mal berücksichtigt!
Hast keinen Fehler gemacht ;)

**Comment by Ston3s** [comment]
Das mit dem mit der Beta3 bald fertig sein ist ja nur mein Empfinden. Auch um euer Meinung einzuholen ;)

**Comment by ghost** [comment]
Mit den der Integration der Serien fast fertig.

Aber mal ne Frage. Wie wollen wir das jetzt mit der de/en Domain machen?

Mir fallen spotan zwei Möglichkeiten ein:
- Site-Settings wie z.b bei movie4k/kinox (sprich man stellt die Domain in den Einstellungen ein)
- anziehen der Einstellung "bevorzugt Sprache" (dann müsste man noch definieren was default ist, da es ja auch "All" gibt)

Mir gefällt die Variante mit Site-Settings am besten.

**Comment by Ston3s** [comment]
Bin auch für Option 1

**Comment by ghost** [comment]
Habe ich jetzt so eingebaut und funktioniert perfekt. (Siehe commit)

**Comment by Ston3s** [comment]
Lynx187 ist es für dich so auch ok?!
Würde mich freuen wenn du uns bei der Entwicklung begleiten/unterstützen könntest, dass hätte auch den positiven Effekt das dann der PullRequest am Ende eher nachvollziehbar ist :)

**Comment by ghost** [comment]
So habe das ganze soweit eingebaut. Siehe https://github.com/StoneOffStones/plugin.video.xstream/commit/e54acb590c20ecdd7878c46c1d6f81b3fcc330eb.

Bitte mal prüfen ob soweit alles ok ist. Ich bin soweit eigentlich recht zufrieden. Wobeiman glaube ich mit etwas mehr pyton-Skills einiges besser lösen könnte (grade die Verarbeitung der JSon-Daten.

Das einzige was ich mir an Funktionen noch vorstellen könnte wäre ein Menü-Punkt "Top 100" wie auf der Seite. Und dadrin ist dann "Heute", "Monat" und "Hall of Fame" zu sehen. Wäre schnell eingebaut ist nur die Frage ob sinvoll.

**Comment by sraedler** [comment]
Ich finde das mit "Top 100" eine super Idee! 

Wer kennt es nicht, man will einen Film schauen und weiß nicht welchen. Dadurch hat man eine Eingrenzung durch aktuell gute Filme und Serien

**Comment by ghost** [comment]
Habe das jetzt ermal wie folgt auf gebaut:

Hall of Fame => im Hauptmenü (weil keine Filterung nach Film oder Serie möglich ist)
Heute und Monat => im jeweiligen Bereich z.b Filme => Top 100 => Heute

So ok? Wäre nämlich z.b auch möglich keinen Ordner zu machen und jeweilige zwei Neue Punkte "Top 100 - Heute" und "Top 100 - Monat" im jeweiligen Bereich zu machen.

**Comment by Ston3s** [comment]
Ziemlich genial!
Ist die Seite somit fertig oder hast du noch weitere Anpassungs- bzw. Verbesserungsideen?

**Comment by Ston3s** [comment]
abgeschlossen?!

**Comment by ghost** [comment]
Erstmal ja. Falls was ist einfach nen neues issue machen.

**Comment by Ston3s** [comment]
Aye aye!!!
