### ISSUE TITLE
Integrate anime-loads.org

### ISSUE THREAD

**Issue by Ston3s** [StoneOffStones/plugin.video.xstream#19]
Hallo zusammen, 

möchte an dieser Stelle ebenfalls auf die mögliche Integration der Webseite anime-loadz.org hinweisen.
Diese wurde bereits von viper2k4 auf einen vorzeigbaren Arbeitsstand gebracht.
Jedoch bereitet zum aktuellen Zeitpunkt noch die Verwendung des reCaptcha-Features noch größere Probleme. Falls ich etwas vergessen oder nicht richtig dargestellt habe bitte ich um Korrektur!

Werbe kräftig für Mithilfe...

**Comment by sraedler** [comment]
Wenn wir auf den neuen Release von url resolver warten, dann könnte dieses Plugin vervollständigt werden, die haben nämlich ein reCaptcha script includiert, evtl. könnte man das direkt ansprechen.

[urlresolver recaptcha v2](https://github.com/Eldorados/script.module.urlresolver/blob/master/lib/urlresolver/plugins/lib/recaptcha_v2.py)

Edit: Oder das reCaptcha.py direkt in den resource\lib ordner kopieren, dann könnte das Problem direkt angegangen werden.
@Viper2k4

**Comment by ghost** [comment]
meinen sourcen sind durch nen Update leider weg :'(

Du hast dir meine Version nicht zufällig gezogen?

**Comment by Ston3s** [comment]
Schau mal in die Branch backup und in den Ordner sites...

**Comment by sraedler** [comment]
Ich hab die selbe Version, wie @StoneOffStones in dem Backup branch. Hab zwar schon was dran gearbeitet, aber das ist so unsauber, da bist du besser dran, wenn es selber versuchst.

Aber es muss zusätzlich ein teil von [hier](https://github.com/Eldorados/script.module.urlresolver/blob/master/lib/urlresolver/plugins/lib/captcha_lib.py) übernommen werden

**Comment by Ston3s** [comment]
Deshalb würde ich euch bitten halbfertige Entwicklungen in Zukunft einfach im Branch abzulegen.
Für den Fall, dass man mal irgendwann dran weiter arbeiten möchte bzw. kann!

**Comment by Kukolorus** [comment]
Also, wenn ich die Seite anime-loadz.org öffnen möchte, dann komme ich auf eine T-Online Navigationshilfe-Seite :P

**Comment by ghost** [comment]
http://www.anime-loads.org/

geht perfekt

**Comment by Kukolorus** [comment]
Oh, doch. 
Also ich muss sagen die Seite mach einen Recht schönen Eindruck. :)

**Comment by Ston3s** [comment]
Finde die Seite auch echt klasse, vor allem weil noch es sich hierbei um etwas Handelt was bisher nicht so richtig im Addon verfügbar ist. Dementsprechend interessantes Portfolio!!!

Für diese Seite müsste aber zuerst das Problem mit dem reCaptcha bzw. die integration des neuen URLResolvers bzw. die integration des reCaptcha.py direkt in xStream gelöst werden.
Deshalb setzte ich hier den Milestone mal etwas in weitere Ferne :)

**Comment by seberoth** [comment]
Hab grad mal ein bisschen rumgespielt. Ersten Tests nach, brauch man den reCaptcha blödsinn überhaupt nicht...

**Comment by ghost** [comment]
Dann schlau mich auf und ich gucke weiter :)

**Comment by seberoth** [comment]
Hab hier einen kleinen JS Code (ich denke ja mal, das umsetzten kriegste hin :P )

Einzige sache wo ich mir noch nicht 100% sicher bin, auf der Seite steht das man am Tag max. 30 Streams ohne Captcha gucken kann. Hab meine Methode jetzt über 30 mal probiert, aber nicht an 30 verschiedenen Links. Müsste noch überprüft werden.

Enc ist das was in 'data-enc=""' steht.

https://gist.github.com/seberoth/46a600ad5e143b783f56

**Comment by sraedler** [comment]
ja an einem Link könnte es Probleme mit dem Cache geben ;)

aber denk an 30 verschiedenen kann man das auch testen ;)

**Comment by ghost** [comment]
@seberoth danke schonmal dafür :)
@sraedler fallst grade Zeit hast kannst mal kurz gucken? Mache grade "Gute-Filme" fertig

**Comment by sraedler** [comment]
Ja, versuch es mal zu integrieren, denn manuell im browser ist das blöd zu testen (aber es hat schonmal geklappt)

**Comment by Kukolorus** [comment]
@Viper2k4 Da freue ich mich aber :D

**Comment by sraedler** [comment]
@Viper2k4 Ich komm einfach nicht weiter, im Browser geht es und in dem Python Script nicht, kannst du mir helfen?

evtl. weiß @seberoth was ich falsch mach.

Mir ist klar, dass die success Funktion fehlt, aber der Response dafür ist schon ein HTTP 200 aber mit inhalt error. Hab sogar mit Wireshark versucht das mitzusniffen, aber finde nicht warum es nicht geht.

[Mein aktueller Stand](https://gist.github.com/sraedler/4ab3c8e8b33357a9b32e)

**Comment by seberoth** [comment]
So. Habs grad mal in Python nachgebaut. Leider war es etwas komplexer als ich gedacht habe... Werd es noch vereinfachen und dann hier posten.

EDIT 1: Ok. Nach 30 mal ist schluss... Jedoch sollten diese 30 ja für die meisten schon ausrreichen. Die anderen müssen dann halt doch Captchas lösen

**Comment by ghost** [comment]
Ich komme wohl leider erst Mittwoch da zu mir das Site-Plugin weiter anzugucken :/

Aber ich denke auch das 30 erstmal ausreichen sollte (besser als nichts ^^). Man müsste mal prüfen auf welcher Basis dieser sperre funktioniert. Vermutlich IP-Basiert oder?

Aber ich denke falls wir das nicht umgehen können und wir dem Anwender ne Meldung ausgeben das das Limit erreicht ist sollte das ok sein. Dann kann der Anwender ja selbst reagieren z.b mit nem reconnect (falls Sperre IP-Bassiert ist und der Anwender DSL hat).

Aber schon mal danke für die tatkräftige Untersützung bei meinen Problem :)

**Comment by seberoth** [comment]
Kann man bestimmt noch optimieren und fehlerbehandlungen einbauen, aber es funktioniert (hab auch gleich den Captcha code mit eingebunden, der funktinieren sollte wenn man die urlresolver version von tvaddons hat)

https://gist.github.com/seberoth/58fa5c08283e27aa11e1

EDIT1: Wenn ich clever gewesen wäre, hätte ich statt >=31 überprüft, ob ne error Meldung zurück kommt...
EDIT2: So, nachgebessert...

**Comment by sraedler** [comment]
[https://gist.github.com/sraedler/4ab3c8e8b33357a9b32e](https://gist.github.com/sraedler/4ab3c8e8b33357a9b32e)

Hab es versucht zu integrieren, bei mir geht es mit dem was du als allgemeingültig beschreibst nicht und das was ich als regex und aus der html mit math.floor gezogen hab geht es auch nicht.

Fehler: {u'message': u'Der Antwort Parameter ist ung\xfcltig oder fehlerhaft.', u'code': u'error'}

**Comment by ghost** [comment]
Ich freu mich schon richtig auf Mittwoch das alles anzugucken :). Und echt doof das ich grade nichts beitragen kann :/

Aber echt richtig schön das wir doch irgendwie vorran kommen!

**Comment by seberoth** [comment]
https://gist.github.com/seberoth/58fa5c08283e27aa11e1

Ok. War mein fehler. Hab es nur manuel mit einem Anime getestet (nicht über Kodi) und eine ud ist immer für einen Anime gültig. Deswegen ist mir der fehler nicht direkt aufgefallen.

Aber das mit dem Regex sollte klappen, so hab ich es jetzt auch angepasst und probiert in Kodi.
Den quatch mit cb und random kannste weglassen.

Wer ist jetzt eigtl. für das Plugin verantwortlich?

Randnotiz: Anime-Loads hat wohl ein "bisschen" geklaut... (http://www.animenati.com)

**Comment by ghost** [comment]
Ich habe das Addon vom Prinzip ja verbockt. Bin ja nur mit dem Captcha nicht weiter gekommen :/

Wenn das ganze jetzt funktioniert. Werde ich das alles umbauen und in schön mit Auswahl des Releases und co. Das habe ich nur alles nicht gemacht weil es ja nicht weiter ging ^^

@animenati.com
das sieht fast so aus als ob das die selben entwickler sind. Nur einmal mit und einmal ohne streams :)

**Comment by sraedler** [comment]
@seberoth es geht bei mir leider trotzdem nicht.

https://gist.github.com/sraedler/4ab3c8e8b33357a9b32e

allerdings wieder {"code":"error","message":"noadblock"} aber weiß nichtmal wenn ich den noadblock cookie hinzufüg geht es^

Auch deine doEnc ging bei mir nicht zum ausführen

**Comment by seberoth** [comment]
Dann weiß ich leider auch nicht weiter. Hab es grad nochmal getestet und bei mir läufts.

Hab es hiermit getestet:

oParams = ParameterHandler()
oParams.addParams({'sUrl': 'http://www.anime-loads.org/media/gin-no-saji-2014-silver-spoon-2'})
oGui.addFolder(cGuiElement('Debug', SITE_IDENTIFIER, 'showEntries'), oParams)

**Comment by sraedler** [comment]
mit was für einem kodi hast du das versuch ?

ich seh grad du hast nicht oRequestHandler.setRequestType(1) hinzugefügt um das ganze als post anstatt get zu senden, was mit dem javascript auch nicht geht.

aber sehe auch im Requesthandler nicht, wo die post variable ausgelesen wird...

**Comment by seberoth** [comment]
oRequestHandler.setRequestType(1) ist auch nicht nötig, da urllib2/mechanize automatisch einen POST draus macht, sobald data gesetzt wurde.

Habs jetzt auch auf einem 2ten Rechner getestet und es läuft.

EInmal WIn7 mit Jarvis und einmal Win10 mit Jarvis.

**Comment by sraedler** [comment]
kannst du deine komplette Datei einmal als gist oder zip bereitstellen, damit ich das testen kann?

**Comment by seberoth** [comment]
https://gist.github.com/seberoth/58fa5c08283e27aa11e1 ist aktuell

Das bisher beste an der ganzen Seite ist, das man die 10-15 Sekunden wartezeit bevor man den Link kriegt (bzw. zum Hoster weitergeleitet wird) nicht überspringen kann...

**Comment by sraedler** [comment]
geht bei mir leider nicht :cry: 

Kann das jemand anders mal testen, ob es an meinem Kodi liegt?

**Comment by ghost** [comment]
Heute Abend :)

**Comment by ghost** [comment]
Sooo erst mal zieh ich meinen hut vor dir  seberoth. Klasse Leistung :)

Ich musste es noch etwas umbauen damit Kodi damit klar kommt. Aber dir eigentlich Arbeit war mit deinem gist schon gemacht.

Waren die Header eigentlich nur zum testen? Weil wirklich nötig sind sie ja nicht.

Jetzt müssen wir nur noch das Leave-Script überlisten. Die 15sec nerven etwas :/

_EDIT_

Das man die Bilder auswählen muss geht ja leider nichts anders :'(. Aber besser als nichts :)

_EDIT2_

Wo hast den Site-Key eigentlich her? Kann ich den evtl. irgend wo auslesen (damit wir dynamisch bleiben)

**Comment by seberoth** [comment]
Da bin ich ja froh das es doch läuft. Müssen wir mal gucken was bei sraedler schief läuft :/

Bzgl. des Headers: Bei mir lief es mit dem standard python Header nicht, hab nur noadblock (scheint bei dennen die fehlermeldung für alles zu sein) als Fehler zurück bekommen.

Und für die Wartezeit hab ich leider keine lösung gefunden...

**Comment by ghost** [comment]
Also ich habe mal alle Header rausgenommen (so nimmt er ja den stein alten von xStream) und das funktioniert wunderbar.

Mal gucken was die Anwender dazusagen wenn sie nen captcha lösen müssen ^^ (ist ja glaube das erste Plugin wo sowas drin ist)

**Comment by sraedler** [comment]
Sobald @Viper2k4 das gepusht hat werde ich es testen, evtl. war es mein Fehler!

Ja, @seberoth  das ist echt eine abartige Leistung !!!

Ich freu mich auf meinen ersten Captcha :laughing: 

@Viper2k4 wenn du mir eine lauffähige Version gibst, dann mach ich das mit den 15 Sekunden, hab voraussichtlich etwas gefunden :+1:

**Comment by ghost** [comment]
Das dauert aber noch etwas. Da ich es erstmal Funktional bauen weil. Damit es funktioniert (auch mit den 15sec^^)

Btw. habt ihr auf der Seite ne Serien mit mehreren Staffeln gesehen?

Ich finde immer nur releases. So das bei "Pokemon" z.b einfach stumpf alle ~300 folgen aufgelistet werden.

Daher wollte ich das jetzt so aufbauen.

Eintrag => Release-Auswahl => Liste der Einträge

Sprich keinen Staffel auswahl (da nicht existent)

_EDIT_

Habe grade mal die Sprache vom capacha auf "de" gestellt und musst dann keines lösen ^^

**Comment by sraedler** [comment]
Wenn du nur an den 15 sec hängst, dann kannst mir ein gist zukommen lassen, aber lass dir ruhig zeit ;)

Ich würde auch behaupten es gibt keine Staffeln...

**Comment by ghost** [comment]
Jetzt habe ich komischweiese plötzlichprobleme mit der Leave-Seite:

"Seite abgelaufen. Die von dir angeforderte Seite ist nicht mehr verfügbar, bitte versuche es nochmal!"

**Comment by sraedler** [comment]
lösch mal dein cache oder stell ihn auf 1 sekunde

**Comment by ghost** [comment]
Habe mir nen Handler gebaut ohne caching und mit neustem Chrome-Useragent und damit ist er zufreiden ^^

**Comment by ghost** [comment]
https://gist.github.com/Viper2k4/04e1e30f621dbe04da5930b20e64d87d

@sraedler Das funktioniert perfekt. Aber bitte benutz nur den Test-Link. An dem anderen (Sprich Releaseauswahl arbeite ich dann)
@seberoth Habe das ganze mal etwas umstrukturiert und etwas kommentiert damit ich es verstehe. Bitte korrigier mich wenn kommentare keinen Sinn ergeben ^^

**Comment by sraedler** [comment]
Heute hab ich leider nichts mehr herausgefunden, mein verdacht hat sich nicht bewahrheitet.

Aber ich glaub nun, dass es eine Serverseitige Validierung ist, denn wenn man im Browser den leavepage Balken durchlaufen lässt reicht es die Seite neuzuladen, man benötigt also nicht zwangsläufig den finalen Url. Lädt man die Seite zwischen drin jedoch neu, so wird die Wartezeit wieder zurück gesetzt.

Ich weiß es gab bei einigen OCH's die Möglichkeit einen Manipulierten Header zu schicken mit falschen Zeitstempeln und dann ging es. Aber das hab ich bisher nicht prüfen können bzw. hat nicht funktioniert.

threading ist auch ein bisschen ein Problem, denn sobald ein neuer link angefragt wird, ist die "alte" Zeit nicht mehr gültig, das heißt es ist immer nur der letzte angefragte link aufgelöst und die anderen sind anime-load*...

**Comment by ghost** [comment]
Wir können das ganze noch etwas optimieren (mache ich denke ich morgen).

Und zwar ist es jetzt so das die Links direkt resolved werden. Was dazu führt das bei 3 Hostern (auch wenn nur 2 supportet werden) der Resolve ausgeführt wird. Was damit quasi 3x15sek sind.

Man könnte aber beim Hoster auch nicht direkt den resolve durchführen sondern nur den Link übergeben und dann nach der Auswahl  den Resolve durchführen.

Das würde die Wartezeite wenigstens auf 15sek senken.

Das wir den Leave irgendwie austrickesen können wäre natürlich das Optimum :)

**Comment by seberoth** [comment]
Man kann aber auch alle 3 per threading gleichzeitig auslösen.

Das Problem was sraedler hat,  ist das du pro Leave-Link ein Cookie gesetzt wird. Da der RequestHandler diese jedoch bei einem Request überschreibt, funktioniert immer nur der letzte (ist ne vermutung, aber im Browser kann ich alle gleichzeitg aufrufen).

Ich bin dabei den RequestHandler entsprechend anzupassen und es dann zu probieren.

**Comment by ghost** [comment]
Aber wieso sollte man denn alle 3 Auflösen wenn es garnicht nötig ist?

Im JSon wird ja wir für jeder Hoster "link" übergeben. Denn man dann ans Leave übergibt. Wieso nicht in "_decryptLink" nur "item['link']" ans Hosterarray koppel und dann in der funktion "getHosterUrl" mit dem Link der ja übergeben wurde den Resolve durchführen.

So erscheint für den Anweder die Liste der Hoster direkt (dann auch nur 2 der 3) und erst beim Auswahl des Hoster wird der Link des jeweiligen Hoster resolved.

Das hört sich für mich wesentlich sauber and und hat weniger overhead.

**Comment by seberoth** [comment]
Imprinzip hast du recht.

Es gibt aber einen Fall, wo die Wartezeit durch diese methode wieder steigt und zwar, wenn der entsprechende Hosterlink ungültig ist (Datei gelöscht usw.)
In dem Fall müsste der Benutzer dann wieder 15 Sekunden warten. (Und ja, es gibt einige, vorallem ältere Animes wo das der fall ist)

**Comment by sraedler** [comment]
Wenn nun der Link an die Liste übergeben wird, dann laufen die 15 Sekunden doch Schon los?

das heißt wenn der Benutzer 5 Sekunden benötigt um einen Hoster anzuklicken sind nur noch 10 über.

Wenn das mit den Cookies funktioniert, dann kann man diese auch speichern und durch eine Loop die jede Sekunde prüft die Zeit minimiert werden.

oder nicht?

**Comment by ghost** [comment]
Die Zeit beginnt mit dem ersten Aufruf des Leave-Links (_resolveLeaveLink) nicht vorher.

Man könnte natürlich beim erstellen der Liste alle Leave-Links 1x aufrufen (womit der Zähler beginnt). Dann dem Anwender die Liste zeigen und dann wie sraedler mit ner schleife solange warten bis man ein Link bekommt der nicht von Anime-Loads kommt.

Falls dann ein Link nicht geht und der Anwender (oder die Automatische Hosterauswahl) einen anderen wählt sollte die Zeit der anderen ja abgelaufen sein.

Am besten wäre immer noch den Mist zu umgehen (und ich dachte der capacha wäre unser einziges problem^^)

_EDIT_

Guckt mal hier:

https://github.com/adsbypasser/adsbypasser/issues/849

Es wurde zwar abgelehnt. Aber dieses Projekt hat einige Skiper eingebaut:

https://github.com/adsbypasser/adsbypasser/tree/master/src/sites/link

Evtl. funktioniert ja irgend was davon hier.

**Comment by Ston3s** [comment]
Site-Icon minimal überarbeitet damit es auch in breiten Kacheln sauber dargestellt wird.

![anime-loads](https://cloud.githubusercontent.com/assets/12751497/14210588/f41619c8-f829-11e5-9d87-fceb36a025d7.png)

**Comment by ghost** [comment]
Guckt mal:

https://github.com/Lynx187/plugin.video.xstream/commit/ca3d4373a4abec8eea4508d3e56d1eb0336cd30f

Hilft uns das ggf.?

**Comment by ghost** [comment]
Sooooo ich habe jetzt eine Release- und Episoden-Auswahl eingebaut. Das ganze ist noch nicht perfekt (Grade im Bezug auf MetaHandler).

https://gist.github.com/Viper2k4/04e1e30f621dbe04da5930b20e64d87d

Aber ich denke die Version ist soweit das man sie schon mal Testen könnte. Wenn ihr euer OK gebt (also keinen Großen Fehler findet) baue ich das ganze ins Nightly ein und wir gucken mal was die User sagen.

Sprachen (Anzeigen was die Ton und Untertitelsprache ist) würde ich dann später nachreichen.

_EDIT_

Ich muss die Release-Auswahl leider vor die Episoden anzeigen. Dann es gibt Teilweise Serien existieren die vom Content underschiedlich (Release 2 z.b hat Folgen die Release 1 nicht hat usw.). Und ich denke ist für den User auch logischer wenn er erst das Release (was ja Teilweise auch unterschiedliche Sprachen sind) und dann die Episode auswählt.

Das Einzige was mich nervt ist das bei Filmen (die ja keine Episoden haben). Dann halt Title im Player "Release 1 - SD" oder sowas steht. Ich würde dem Player irgend wie gern den Filmnamen übergeben.

**Comment by sraedler** [comment]
Funktionsfähig und auch gut gemacht, kleine Verbesserungsmöglichkeit wäre, wenn der sleep ist, dass dann in der Ladebox ein Counter runterzählt.

**Comment by ghost** [comment]
Die Frage ist => Wie geht das? ^^

Zu dem Zeitpunkt ist er ja in dieser "prepare Hosterlist". Ich weiß nich in wiefern ich darauf eingreifen kann.

**Comment by ghost** [comment]
Sooooooooooooo habe noch mal nen Miniupdate gemacht (der hat immer die erste Episode abgespielt egal was man gewählt hat ^^)

https://gist.github.com/Viper2k4/04e1e30f621dbe04da5930b20e64d87d/revisions

Aber egal. Also meint ihr schon mal in die nightly mit reinhauen? Weill dann nehme ich die Links raus und commite nachher mal.

**Comment by sraedler** [comment]
bei manchen hostern ist das wenn man urlresolver.resolve() aufruft kommt das...

muss es mir aber auch erst anschauen

**Comment by ghost** [comment]
Gesehen habe ich es auch schon mal. Müsste man mal gucken bei welchen. Und vorallem wie man das Proaktiv aus einem Plugin aufrufen kann.

**Comment by ghost** [comment]
Habe nen commit gemacht

(Habe bewusst die Debug-Links als Kommentar drin gelassen. Solang wir noch nicht durch sind ist das denke ich besser)

**Comment by Ston3s** [comment]
Bist mir mit dem zurücksetzten des Site-Icons etwas zuvor gekommen.
Habe auch gesehen, dass es nicht sauber war und einen Absatz im Randbereich hatte.
Jetzt habe ich mich nochmal hingesetzt und das Site-Icon nicht nur angepasst sondern von "neu auf" erstellt und das Design von der Homepage etwas mehr berücksichtigt.
https://github.com/StoneOffStones/plugin.video.xstream/commit/5f4f74a7a1f1593e46349762f9d2c2593103a23c

![anime-loads3](https://cloud.githubusercontent.com/assets/12751497/14232953/d2af086c-f9b9-11e5-84d6-fd4230103b7d.png)

**Comment by ghost** [comment]
Noch besser. Dankeschön :)

**Comment by Ston3s** [comment]
Nicht wundern warum da so komische Commits erzeugt wurden. Er hatte bei mir in GitHub for Desktop irgendwie einen Bug mit der anime-loads_org.py.
Wollte diese die ganze Zeit ersetzen obwohl ich an dieser nichts gemacht habe.
Auf jeden Fall habe ich jetzt die Datei aus deinem letzten Commit zu Anime-Loads genommen und damit ersetzt um sicher zu gehen das nicht versehentlich doch was daran anders ist.

**Comment by shagger** [comment]
Hallo zusammen, 
Tolle Arbeit. 
Habe hier einen Fehler in der nightly.wenn ich Serien anklicke oder auch neuste serien...Kommt die Fehlermeldung :key error:tvshows title 
....gui/guiElement.py line 222,in getMeta 

Gruß shagger

**Comment by ghost** [comment]
Hi,

hast den MetaHandler an (Wenn der Metahandler aus ist sollte der Fehler nicht kommen)? Der Fehler liegt leider nicht am Addon selbst sondern an xStream. Könntest du evtl. mal den Teil der Log posten?

Gruß

**Comment by shagger** [comment]
Sorry,das ich jetzt erst antworte. 

log: http://xbmclogs.com/prfwajgyl

Ja,das stimmt.ohne metahandler geht es. 
Gruß shagger

**Comment by ghost** [comment]
Siehe unter meinen Post. Lynx hat es bereits im Auge und bei sich intern geändert (aber noch nicht bereitgestellt)

**Comment by ghost** [comment]
@shagger 
Lynx187 hat das gestern im Master gefixed https://github.com/Lynx187/plugin.video.xstream/commit/81cfae7b8d1ec614874c256cfda1561d79aaefae . Ich denke das wird bald von StoneOffStones in die Nightly mit aufgenommen. 

Dann solltest den MetaHandler wieder benutzen können.

**Comment by ghost** [comment]
So aber mal wieder zum Addon. Ich wollte mich als nächstes mit den Sprachen auseinander setzen.

Wie soll ich es am besten gestalten? Die Sprachen scheinen ja an die Releases gebunden zu sein. Daher wollte es auch dort anzeigen. Quasi so (Beispiel "The Garden of Words"):
- Release 1: 720P (JP | DE)
- Release 2: SD (DE)
- Release 3: 1080P (DE)
- Release 4: SD (JP | DE)
- Release 5: 1080P (JP | DE)

Ist das so gut erkenntlich?

@Lynx187 

Wo wird setLanguage und setSubLanguage weiter benutzt? Ich habe gesehen das es in movie4k und kinox.to benutzt wird. Jedoch finde ich keinern Punkte wo die Information benutzt wird.

Daher weiß ich nicht genau was ich wie und wofür übergebe. Ich würde jetzt stumpf "de" und "jp" übergeben (falls überhaupt "nötig")

**Comment by Ston3s** [comment]
Werde ich versuchen heute Nachmittag in die Nightly aufzunehmen. ;)

Würde vielleicht wenn du SD aufzählst auch HD mit der entsprechenden Auflösung nennen.
Vielleicht kann man die Sprachen noch über Fett geschriebene Schrift hervorheben.

 Release 1: HD, 720p ( DE | EN | JP )

War wäre wenn man die Sprache wie in den Einstellungen voll ausschreibt, zu lang??

**Comment by ghost** [comment]
Die Anzeige kommt stumpf von der Webseite. Wenn der Release auf der Seite "Release 1: 720P" heißt. Dann ist dem halt so. Teilweise heißen die auch ganz anders :)

Was die Sprachen angeht ist es wie folgt. Ich ermittelt die Sprache über die CSS-Klasse. Diese heißen "flag-jp","flag-de","flag-en" usw. per Regex ermittelt ich dann das "jp,de,en" usw.

Das heißt wenn ich Deutsch, Japanisch, English möchte. Müsste ich das extra übersetzen. Sprich ein Array wo drin steht "JP" => "Japanisch".

**Comment by Ston3s** [comment]
Ok, danke für die Ausführung zum Verständnis!

Das mit den ausgeschriebenen Spachen war nur ein Gedankenanstoß von mir, vielleicht hätte es ja Sinn gemacht. Mir soll beides recht sein, was denkst du bzw. der Rest?

**Comment by Lynx187** [comment]
Stimmt `setLanguage` und `setSubLanguage` werden bis jetzt nur in diese beiden Seiten, mehr oder weniger, konsequent benutzt, da dort mehrere Sprachen verfügbar sind und der eigentliche Name durch diese Angaben "verunreinigt" wird.
Man müsste natürlich auch nachsehen wozu die Attribute in denen diese Angaben landen dann benutzt werden. Man kann damit den eigentlich Titel sauber lassen. Diese Zusatzanbagen werden dann in einen definierten Format angezeigt was man bei Bedarf auch leicht wieder herausfiltern kann.

**Comment by ghost** [comment]
Ok also hat das für Kodi ansich keine bewandtnis sondern ist mehr ein Internes womit man weiter Arbeiten könnte (sofern benötigt).

In diesem Fall wäre die Anzeige wie oben eigentlich ok. Sprich die Angabe der Sprachen würde nicht stören im Text wrüde nicht stören und nicht zu probleme führen. Heißt ich kann die Funktion weglassen. Korrekt?

Gibt es eigentlich eine Möglichkeit dem Player den Title mit zu geben? Weil per Default steht dort z.b "Folge 1" wenn der Listen Eintrag so hieß.

**Comment by Lynx187** [comment]
Ja wäre ok wenn man es nicht weiter verarbeiten will.
Es gibt übrigens noch ein Quality Attribut.

Wenn man den Titel im Player ändern will sollte einer der Parameter die für den Titel geprüft werden (hoster.py getInfoAndResolve) den Titel enthalten.
Für Play müsste man dann diesen Titel dem listitem das zum abpielen in der hoster.py erzeugt wird mitgeben.

**Comment by ghost** [comment]
Dieser wird aber genauso wie _Language_ und _SubLanguage_ auch nur in den InfoString benutzt oder?

Das prüfe ich heute Abend mal. Ist ja nicht essenziell aber ist mir so aufgefallen :)

**Comment by ghost** [comment]
So also die Anzeige der Sprache habe ich eingebaut (ohne Setzen der funktionen). Aber zwei fragen hätte ich noch:
1. Stört es wenn ich mit [i]Text[/I] die Sache etwas formatieren ung führt das ggf. zu problemen?
2. Problem ist das es glaube ich einen bug in der gui.py gibt. Und zwar kann ich z.b 'MovieTitle' als parm an den Eintrag übergeben. Aber in der Zeile 254 wird er immer mit dem Title des Eintrags überschrieben. Das hat zur folge das die Abfrage in der hoster.py hinfällig ist da 'MovieTitle' immer mit einem Wert gefüllt ist. Was wiederrum dazu führt das die anderen Werte auf nie überprüft werden. Kommentiere ich aus Testzwecken die Zeile aus funktioniert das ganze perfekt. Ggf. könnte ne Prüfung in der gui.py reichen ob 'MovieTitle' schon in den parms ist und nur im false Fall den Title des Eintrags zu nehmen. (Habe ich nicht getestet war nur eine Idee)

**Comment by Lynx187** [comment]
1. Sollte nicht, ist genau das was auch passieren würde wenn du die vorhandenn Attribute nutzen würdest.
2. Hm ja stimmt das war früher mal nötig zumindest um es nicht jedesl mal extra zu setzen. Aber andererseits diesen Parameter müsstest du ohnehin bereits setzen wenn du als Titel nur  z.B "Folge 1"  weisst und dann Kannst du auch Gleich dne Wuschtitel setzen.
   Alles was kommt wenn die Hoster gesucht werden fließt nicht mit ein.
   Würde ich jetzt aber auch nicht zu viel dran machen da es in Zukunft nicht so bleiben kann/wird.

**Comment by ghost** [comment]
Mh stimmt grade getestet. Dann stellt sich halt die Frage:
- Release 1: 720p (JP | DE)
- Release 2: 720p (EN | DE)

Oder
- Release 1: 720p (JP) _Sub: DE_
- Release 2: 720p (EN) _Sub: DE_

Variante 1 wäre manuel gesetzt und Variante 2 wäre mit interen xStream Funktionen.

**Comment by Lynx187** [comment]
Kommt drauf an ist die Sub denn de ? Ansonsten sollte man bis jetzt auch nen belieben String übergeben können.

**Comment by Ston3s** [comment]
Geht auch 

Release 1: 720p (Language: JP | Subtitle: DE)
Oder...
Release 1: 720p (Lang.: JP | Sub.: DE)

Auf jeden Fall würde ich es in einer Klammer machen weil es selbe Thematik betrifft.

**Comment by Ston3s** [comment]
Wenn nicht dann einfach ignorieren ;)

**Comment by ghost** [comment]
@StoneOffStones 
Bei Variante 1 könnte man das machen ja

@Lynx187 
http://www.anime-loads.org/media/kotonoha-no-niwa-the-garden-of-words

Hier sieht man recht gut wie es normal aussieht.

Bei Streams gibt es eigentlich immer nur einen Hauptsprache (mehrere Audiostreams habe ich bis jetzt nur bei Downloads gefunden) und ggf. nen Sub. Normal fehlt der Sub nur bei Deutschen Streams. So habe ich es aktuell in der nightly:
-     Release 1: 720P (JP | DE)
-     Release 2: SD (DE)
-     Release 3: 1080P (DE)
-     Release 4: SD (JP | DE)
-     Release 5: 1080P (JP | DE)

**Comment by ghost** [comment]
Glaubt es es gibt einen "Markt" hier für:

http://www.anime-loads.org/asia
(Falls ja müsste man ggf. die Ansicht anpassen da es auch nur Unterscheidung zwischen Serien und Filmen gibt)

und ggf.:

http://www.anime-loads.org/hentai
(Natürlich mit Abfrage des XXX-Schutzes versteht sich)

**Comment by Ston3s** [comment]
Der eine brauch es der andere nicht ;)

**Comment by Kukolorus** [comment]
;)

**Comment by ghost** [comment]
Ok guck ich mir am Sontag ggf. mal an :)

**Comment by ghost** [comment]
Was meint ihr? Sollte beim Öffnen des Addons das Menü dann so aussehen?

## \- Anime
- Filme
- Serien
- Suche

## \- Asia
- Filme
- Serien
- Suche

## \- Hentai _(nur sichtbar wenn aktiviert)_
- Filme
- Suche

## \- Suche

Die Suche im Unterbereich würde dann filtern auf den Bereich und die Suche im Hauptmenü sucht in allen Bereichen. (Wenn aktiviert natürlich mit SafeSearch)

**Comment by Ston3s** [comment]
Hört sich logisch an...

**Comment by ghost** [comment]
ok habe nen commit eingereicht. Dort sind die Asia-Filme schon mal eingebaut.

Für Hentai müsste ich noch "SafeSearch" ausschalten. Jemand ne Idee wie ich das im Cookie am besten setze?

**Comment by seberoth** [comment]
Reicht es nicht wenn du safe_search=1 an die url anhängst?

**Comment by ghost** [comment]
jop tut es :)

Aber aus irgend welchen gründen müssen ich auch safe_search=0 setzen weil wenn nicht erscheinen auch wieder ergebnisse vom nicht gesetzten safe_search.

Sprich selbst wenn das Caching NICHT aktiv ist. Liefert die suche das ergebniss vom zuletzt gesetzten safe_search status. Also muss ein Cookie geladen werden.

**Comment by ghost** [comment]
Ok Hentai ist nun auch drin. Bitte mal prüfen ob das alles funktionert (das Hentai nur angezeigt wird wenn das Setting gesetzt ist und das auch die suche gefiltert ist)

**Comment by HvDaedalus** [comment]
Keine Ahnung warum "mein" Kodi da rummault - habe mal einen Pull-Request erstellt. Nach der mini-Änderung funktioniert es.

**Comment by ghost** [comment]
Jo war mein Fail { } ist eigentlich ne Dict und [ ] nen Array (was es wie der Name sagt ja auch sein sollte ^^. Die Frage ist eher wieso mein Kodi nicht gemäckert hat :)

**Comment by Ston3s** [comment]
Ist ja jetzt eigentlich drin?!

**Comment by Ston3s** [comment]
Das Capchta Problem dann bitte in einem neuen Issue. Danke!
