### ISSUE TITLE
[User Experience] same language-settings like Kodi

### ISSUE THREAD

**Issue by Ston3s** [StoneOffStones/plugin.video.xstream#20]
Hallo miteinander,

würde gerne ein einem weiteren Punkt eine kleine Verbesserung erwirken.
Mir ist aufgefallen, dass in den xStream-Settings für Spracheinstellungen zwischen den Abkürzungen all/en/de ausgewählt werden kann.
Um ein einheitlicheres Benutzererlebnis zu ermöglichen dachte ich daran die Spracheinstellungen ähnlich zu gestallten wie bei den Kodi-Einstellungen.
Dort wird es in englischer Sprache ausgeschrieben, somit würde eine Änderung zu All/German/English sinnig sein.

**Comment by Ston3s** [comment]
Reicht es wenn ich wenn ich in der settings.py in der folgenden Zeile die Abkürzungen auf die gewünschte Benennung ändere oder muss ich noch mehr anpassen?

`<setting default="2" id="prefLanguage" label="30002" type="enum" values="ger|eng|all" />`

Eventuell in den den Site-Plugins für movie4k und Kinox wo “getPreferredLanguage“ genutzt wird?!

**Comment by Ston3s** [comment]
Hier der Bereich von movie4k:

```
# preferred language
sPrefLang = __getPreferredLanguage()
# adult Cookie
if showAdult():
    adultCookie ='xxx2=ok;'
else:
    adultCookie = ''
# Make the request
oRequest = cRequestHandler(sUrl)
oRequest.addHeaderEntry('Cookie', sPrefLang+sSecurityValue+adultCookie)

return oRequest.request()

def __getPreferredLanguage():
oConfig = cConfig()
sLanguage = oConfig.getSetting('prefLanguage')
if sLanguage == '0':
    sPrefLang = 'lang=de;onlylanguage=de;'
elif sLanguage == '1':
    sPrefLang = 'lang=us;onlylanguage=en;'
else:
    sPrefLang = ''
return sPrefLang
```

**Comment by Ston3s** [comment]
Und für Kinox:

```
# preferred language
sPrefLang = __getPreferredLanguage()
# Make the request
oRequest = cRequestHandler(sUrl)
oRequest.addHeaderEntry('Cookie', sPrefLang + str(sSecurityValue) + 'ListDisplayYears=Always;')
oRequest.addHeaderEntry('Referer', URL_MAIN)
oRequest.addHeaderEntry('Accept', '*/*')
oRequest.addHeaderEntry('Host', domain)

return oRequest.request()

def __getPreferredLanguage():
sLanguage = oConfig.getSetting('prefLanguage')
if sLanguage == '0':
    sPrefLang = 'ListNeededLanguage=25%2C24%2C26%2C2%2C5%2C6%2C7%2C8%2C11%2C15%2C16%2C9%2C12%2C13%2C14%2C17%2C4'
elif sLanguage == '1':
    sPrefLang = 'ListNeededLanguage=25%2C24%2C26%2C5%2C6%2C7%2C8%2C11%2C15%2C16%2C9%2C12%2C13%2C14%2C17%2C4%2C1'
else:
    sPrefLang = ''
return sPrefLang
```

**Comment by sraedler** [comment]
sollte normal passen, weil die Anweisung das enum zurück gibt.

Wichtig ist nur, dass die Reihenfolge gleich bleib, also wenn ursprünglich all|de|en war muss all|deutsch|englisch stehen, nicht deutsch und englisch vertauschen!

**Comment by Ston3s** [comment]
Wurde berücksichtigt

**Comment by Ston3s** [comment]
Wir warten mal eine Beta ab, wenn es keine negative Rückmeldung gibt wird der Issue auch gleich wieder geschlossen.

**Comment by Ston3s** [comment]
Beta3 sollte jetzt auch bald soweit sein, bis jetzt alles ok.
Deshalb dicht gemacht!
