### ISSUE TITLE
Beta hochzählen

### ISSUE THREAD

**Issue by sraedler** [StoneOffStones/plugin.video.xstream#22]
Folgendes anliegen:

Im Forum kann fast täglich gelesen werden, "Wie kann ich das updaten" oder "Wohin muss ich die Py kopieren?". Sollten wir nicht genau dafür die Betas nutzen? Ist doch egal wenn die Beta bis zum Mergen auf 100 hochgezählt ist.

Daher mein Vorschlag, wenn es Änderungen an einem Tag gibt, dann wird am ende des Tages das Tag hochgezählt.

Also z.B. heute Abend auf 2.1.16~beta2
bei der nächsten Änderung wird am Abend auf 2.1.16~beta3 geändert.

@StoneOffStones @Viper2k4

**Comment by Ston3s** [comment]
Also ich bin auch dafür heute die Beta2 zu veröffentlichen. Jedoch macht es Sinn für die nächsten Sprünge kleine Pakete zu schnüren.
Ich will ungern jeden Tag eine Beta die dann nicht funktionsfähig ist veröffentlichen müssen!

Bin dafür grob zu definieren was man für die nächste Beta vor hat und dann erst Veröffentlichen!!!

**Comment by sraedler** [comment]
ja ich fände wie gesagt die Milestones gut...
aber die musst glaub du einstellen

**Comment by Ston3s** [comment]
Ok, und was ist das jetzt schon wieder bei GitHub.
Man lernt hier extrem schnell ;)

**Comment by sraedler** [comment]
An der rechten Seite siehst du doch die Milestones, du kannst jeden Bug zu einem Hinzufügen und bei den Einstellungen textuell ziele festlegen

**Comment by Ston3s** [comment]
Oder einfach gewisse Issues Milestones hinzufügen.
Wenn wir hier sauber über die Issues arbeiten ist das ne gute Sache.

Hatte bereits parallel geschaut wie das funktionieren könnte.
Guter Tipp danke!

Wichtig: 
Wenn in euren Augen ein Issue für die nächste Beta interessant oder sogar wichtig ist bitte einfach kurz ein Comment absetzen und ich kann kurzfristig reagieren ;)

**Comment by ghost** [comment]
Dann würde ich eher nighlie's machen. Und das alls zusäzuliche möglichen Updatezweig definieren.

Sprich:
- Stable => Lynx187/plugin.video.xstream
- Beta => StoneOffStones/plugin.video.xstream (Master Branch)
- Nighlies => StoneOffStones/plugin.video.xstream (Beta Branch)

So bekommt jeder was er braucht ^^

**Comment by sraedler** [comment]
Wäre auch eine gute idee :+1: 

und downgrade zu beta von nightly erlauben aber nicht von beta auf master oder wie ist das gedacht?

**Comment by Ston3s** [comment]
Das wäre so möglich. 
Würde man die nightlies dann als PR in die Beta einpflegen oder wie?

Frage nur weil ich euch ja extra freigeschaltet habe um es einfacher und ohne PRs zu haben.

Wenn wir uns darauf einigen würde ich die Beta aber gerne im selben Branch lassen und für die nightlies ein neues Branch erstellen.

**Comment by Ston3s** [comment]
Obwohl ich glaube das die Milestones uns schon fast ausreichen sollten. 
Ich sehe es jetzt nicht als zwingend erforderlich jeden Tag ein neues Build zu präsentieren.
Wenn man zusieht das die Betas laufen kann man auch mal ein paar Tage warten!!!

**Comment by Ston3s** [comment]
Habe eben nochmals durchgelesen.
Wenn ich das richtig verstanden habe soll die nightly Branch dann auch über das AutoUpdate Feature verfügbar gemacht werden?

Wenn ja dann verstehe ich jetzt Suchdienst Analogie zum FireStarter. ;)

Hab das nur aus der Team Organisation Brille gesehen da würden die Milestones natürlich ch ausreichen!

Ich weiß das Lynx187 schon bei der Beta bedenken wegen der Supportanfragen im Forum geäußert hat. 
Er hatte sich für alles was keinen Finalen stand hat einen eindeutigen Hinweis gewünscht, dass es eine Beta/Nightly ist und es dafür kein Support im Forum gibt!

**Comment by sraedler** [comment]
Ja soll dann auch im Autoupdate als dritte Updatequelle hinzugefügt werden.

Das Problem ist, über kurz oder lang nutzt kaum jemand die Beta, weil wenn schon nicht die Stable Version genutzt wird, warum dann nicht die wirklich neuste Version?

Zu dem bedenken von Lynx, das wird automatisch übers Forum laufen, denn wo sollten die Benutzer sonst Fragen und Probleme schildern?

Prinzipiell ist es mir egal, ob wir einen weiteren Branch nutzen oder nicht. Aber hier noch zwei fakten zu den Überlegungen:
1. Da wir die Version **nicht** immer **kontinuierlich hochzählen** werden wir irgendwann **das Problem von unterschiedlichen Versionen** haben, welche **dieselbe Versionsnummer** haben (z.B. einer Installiert am Montag die neuste Beta, der andere am Freitag, weil dazwischen entwickelt wurde aber keine neue Version vergeben wurde.
2. Egal ob wir 1,2 oder 5 Branches haben, die Benutzer werden sich irgendwie immer melden, auch wenn sie einen Github Account machen und hier rein schreiben, was meiner Meinung nach sehr schlecht wäre!

Ich hätte drei Lösungen des Problems als Vorschlag:
1. Beta,Nightly Version - Wir haben drei Verschiedene Versionen, welche alle in den Settings gewählt werden können, geben jedoch bei JEDEM start von xStream eine Info aus, dass die Nightly NICHT im Forum unterstützt wird und nur Entwicklerstände enthält. Diese **Nightly** Version wird dann **entweder über Versionen** verwaltet, welche wirklich **bei jedem Commit** hochgezählt wird,
   **oder bei jedem start unabhängig von der Version upgedatet**.

Ist der Stand dann einen definierten Milestone erreicht hat, lauffähig und ohne grobe Bugs ist, dann wird er in den Beta gemerged (aber ohne Pull Requests, die nerven da nur)
1. Wir haben nur zwei Versionen, Beta und Stable. Hierbei wird wie aktuell **in der Beta gearbeitet** (was dann aber eigentlich der Falsche Name ist) und **nach** jedem **Milestone wird die Beta Version hochgezählt.**
2. Ein Mix aus 1 und 2. Das heißt drei Branches, Beta und Stable können per Autoupdate geladen werden, ein Entwicklungsbranch muss manuell installiert werden. Nach jedem Milestone wird in den Beta gemerged.

Ich Persönlich würde Punkt 1 wählen, denn dann hat man nicht so viele Posts über die nicht Funktionierenden Nightly versionen, jedoch gutes Feedback zur Beta.

**Comment by ghost** [comment]
Aber guck doch was im Forum abgeht. Die Leute wollen schlicht und ergreifend den aktuellen Stand.

Ich würde es so machen wie aktuell auch. Wir entwickeln im Beta Branch. Der Updater scheißt hier quasi auf Versionsnummern (oder wäre es möglich ggf. zu prüfen ob es zwischen den letzten Update nen commit gab).

Irgend wann wird nen Stand aus dem Beta Branch in die Master gemerged und es wird die Versionsnummer angepasst.

Ich glaube eben das wenn wir keine Nightly haben das es mehr fragen gibt. 

Grade wenn sich z.b was an nem Plugin ändert. Es gemeldet wird und es gefixt wird. Ist es in der Nightly drin. Und die Leute wollen es halt haben. Müssen dann aber halt mit ner Nightly leben.

**Comment by sraedler** [comment]
Hoff ich versteh dich richtig, du willst drei Branches?

Also quasi so:

Nightly: Hier wird entwickelt und wenn diese Einstellung in den Settings festgelegt ist, dann wird immer beim start geupdated.
Beta: Hier wird die ~Beta1, hochgezählt wenn von Nightly germerged wird. Hochzählen, da sonst auch immer geupdated wird, egal ob eine neue Version da ist oder nicht und das nervt beim täglichen betrieb.
Stable: Wird von Lynx gemacht

Forum kann man nicht verbieten.

Commit erkennen wäre möglich, aber leider zu viel Aufwand für das Resultat.

Hab ich das richtig verstanden? Wenn ja, das würde ich so auch unterschreiben!

**Comment by Ston3s** [comment]
Ist für mich so auch ok. Damit verlagern wir die eigentliche Entwicklung in kleinen Steps nur in ein neues Branch namens "nightly"!

Für mich trotzdem wichtig das die Info beim öffnen des Addons kommt das es für die Nightly Version kein Support gibt.
Möchte die eineände von Lynx187 ernst nehmen ;)

**Comment by ghost** [comment]
Ich würde die Meldung beim Umstellen der Settings machen oder wäre das nicht ok?

**Comment by Ston3s** [comment]
**Bei der nighly wäre ich wirklich dafür diese meldung bei jedem Start zu zeigen auch weil bei jedem Start die neue Version bezogen wird.**
Bei der beta reicht es einmalig wie von dir beschrieben.

**Comment by sraedler** [comment]
ja eine Meldung ist für mich auch gut!

@Viper2k4 beim Setting umstellen weiß ich nicht wie ein Dialog angezeigt wird...

@StoneOffStones haben wir in dem nightly Schreibrechte ?

**Comment by Ston3s** [comment]
Der Branch "nighly" ist erstellt und kann/sollte ab sofort für alle Commits genutzt werden.
Erst bei einem über die Milestones definierten Stand in einem "betawürdigen" qualität wird diese in die Beta Übertragen und somit ein Versionssprung vollzogen!

**Comment by Ston3s** [comment]
Rechte wurden erteilt...

**Comment by sraedler** [comment]
Ok, dann werde ich nun die Nightly in den UpdateManager einbauen.

Werde es aber nur auf den Nightly pushen

**Comment by sraedler** [comment]
Nightly sollte nun updatebar sein 3321acf  

TODO: Meldung was für eine Version, aber da müssen wir noch entscheiden wo die kommen soll, entweder bei jedem Start als info oder nach jedem update oder beim setting ändern.

**Comment by Ston3s** [comment]
Die Nightly Funktion würde ich dann offiziell in der Beta3 machen.
Bin bei der Nachricht für Option 1 oder 2.
Also bei jedem Start bzw. bei jedem Update da es sich bei der Nightly um eine absolut experimentelle Version handelt.

Dafür wäre eine Art Support gar nicht chr ableistbar!!!

**Comment by ghost** [comment]
Support wird ja eh nicht geliefert :) (also in dem Sinne das jemand drauf bestehen kann)

Ich finde ne Meldung für den Anwender das wenn er Beta oder Nightly auswählt mit Fehler eechnen muss ausreichend.

Ich nutze z.b den Firefox Nightly und muss sagen es würde mich total nerven wenn bei jedem Start nen Meldung kommt.

**Comment by Ston3s** [comment]
Vielleicht ist es nervig jedoch will ich den Otto-Normal-User auch nicht dazu motivieren die Nighly zu nutzen.

Wie gesagt es handelt sich dabei hauptsächlich als reines Tool zur Entwicklung.

Vielleicht gibt einen Mittelweg über die Beschränkung der Häufigkeit solcher Meldungen.
Quasi nur einmal an Tag oder so...

**Comment by sraedler** [comment]
Ich würde im Moment auch keine Meldung einbauen, da es nicht immer schön ist wenn für alles eine Meldung kommt. Und schätze die meisten User werden eh nicht auf die Nightly wechseln.

Da wäre sinnvoller, wenn man einen Wikieintrag schreiben würde, in welchem diese Info bezüglich Nightly enthalten ist.

**Comment by Ston3s** [comment]
Ich hab euch gewarnt.

Aber die ich möchte das erstmal nur auf Probe so reinkommt.
Wenn es im Forum zu bunt wird sollte die regelmäßige  Meldung unbedingt nachgezogen werden. ;)

Nicht das Lynx187 die neue Version wegen solcher Kleinigkeiten gar nicht annehmen möchte.
Das Ziel des ganzen ist ja der final zuzuarbeiten!

**Comment by sraedler** [comment]
ja, kann ja jeder Zeit ohne viel Aufwand hinzugefügt werden.

**Comment by Ston3s** [comment]
Top!

Könnte den Fehler bei der Nightly ebenfalls feststellen. Leider kann xStream nicht mehr geöffnet werden.

**Comment by sraedler** [comment]
Da versteh ich grad nicht was du meinst.

welcher Fehler?
wie nicht mehr geöffnet werden?

**Comment by Ston3s** [comment]
Ups da war ich zu schnell war für Issue #25 das mit dem Fehler.

**Comment by sraedler** [comment]
Ich denk das kann geschlossen werden
