### ISSUE TITLE
 [User Experience] alphabetic sorting

### ISSUE THREAD

**Issue by Ston3s** [StoneOffStones/plugin.video.xstream#23]
Hallo zusammen,

konnte bis jetzt nicht nachvollziehen nach welcher Logic die Sie-Plugins in xStream dargestellt werden.
Vermute das es stark davon abhängig ist wie Seiten in den Settings aufgeführt werden.
Ich wäre dafür da mal etwas Ordnung rein zu bringen.
Entweder man sortiert hier nach aktualität oder was für mich viel logischer ist, auch im Bezug auf die weiterführende Entwicklung, ist eine alphabetische Sortiereung.

**Comment by sraedler** [comment]
Hab es geändert a909fd8

Soll Globale Suche am Anfang sein?

Momentan sind nämlich globale suche und die Settings am ende....

Ich würde die Globale suche am Anfang bevorzugen und die Settings am ende

**Comment by ghost** [comment]
Ich würde die Globale-Suche nur nach vorne setzen wenn wir diesen "Trennlinien" hin bekommen. Sonst finde ich das etwas zu gemixt :)

**Comment by Ston3s** [comment]
Aktuell sehe ich das mit der Trennlinie noch nicht so greifbar.

Lass doch die Suche als vorletztes vor den Settings. Kann man dann auch gleich alle Settings für xStream, Metahandler und URLResolver in einen Hauptordner Settings ablegen. 
Sonst da am Ende so viel unnötiges Gedöhns...

**Comment by sraedler** [comment]
Denk die hauptaufgabe des issues ist erledigt, der rest wird in #16 gemacht
