### ISSUE TITLE
Versionssprung bei dem Umfang

### ISSUE THREAD

**Issue by Ston3s** [StoneOffStones/plugin.video.xstream#24]
Hallo,

so langsam habe ich den Anschein, dass wenn es mit den Features für die vermeintlich nächste Version 2.1.16 so rasant weiter geht der Sprung gar nicht mehr aussreicht um die Verbesserungen entsprechend wertig darzustellen.
Allein mit dem AutoUpdate Feature, der Integration von HDfilme.py und den ganzen anderen geplanten Anpassungen in Richtung User Experience ist es schon ganz ordentlich.
Und wer weiß vielleicht bekommt man auch noch andere Features wie reCapacha und somit Animie-Loadz.org auch noch dazu.

Was spricht denn dagegen den Sprung auf xStream 2.2.0 zu wagen?!

**Comment by sraedler** [comment]
Das ist mir egal, denk Lynx macht das eh nach seinen Überlegungen, da haben wir kein Mitsprache recht.

**Comment by ghost** [comment]
Denke auch das wir die Versionierung bei Lynx lassen. Wir arbeiten ja quasi nur zu.

**Comment by Ston3s** [comment]
Ok dann nehmen wir für uns bei jeder Weiterentwicklung der aktuellen Master stumpf den nächst möglichen Versionssprung an und übergeben an Lynx187 und überlassen ihm dann die Wertigkeit des Updates bzw. den tatsächlichen Versionssprung!

Ist gut...

**Comment by Lynx187** [comment]
Kann man machen aber ich werde auch nur Änderungen übernnehemn die ich als PR bekomme und damit miene ich nicht zig unabhängige änderungen in einem, sonst bruahc ich stunden das durzusehen

**Comment by sraedler** [comment]
@Lynx187 also irgendwann einen großen pull?

**Comment by Ston3s** [comment]
Also ist 2.2.0 ok aber es soll nicht die ganze Beta als PullRequest eingereicht werden.

Aber wie kriegt man es jetzt noch in vernünftige Häppchen zerkleinert und übermittelt?!

**Comment by Ston3s** [comment]
Vielleicht sollen in Zukunft die Änderungen zu den Veröffentlichungen der Betas bereitgestellt werden???
Oder gibt es noch eine bessere Idee...

**Comment by Lynx187** [comment]
Ja das ist nicht ganz einfach. Da die Ursprungsbraches ja nicht mehr existieren und in die Beta ja erst mal alles gemerged hat was irgendwo aufgetaucht war.

**Comment by Ston3s** [comment]
Genau deshalb frage ich ;)
Hatte ja wegen dem Anspruch an die Beta, dass diese "mergebar" sein sollte extra alle Inhalte ohne wirkliche Funktion (Alpha-Status) entfernt.

Muss einfach nur wissen wie es für dich gut ist aber es für uns auch machbar/praktikabel bleibt.
