### ISSUE TITLE
[UpdateManager] ständige updates

### ISSUE THREAD

**Issue by sraedler** [StoneOffStones/plugin.video.xstream#25]
Da keine Version geprüft wird, updated der updatemanager bei nightly ständig

**Comment by sraedler** [comment]
Nightly update limit auf 1 mal pro Stunde 5a072a2

**Comment by ghost** [comment]
Aber es muss doch ne Möglichkeit geben das letzte Commit zu prüfen oder? Und wenn es nur ne dumme http-Abfrage ist.

https://developer.github.com/v3/

Weil aktuell ist das etwas zu aggro^^

**Comment by sraedler** [comment]
Es gibt zwei Lösungen:
1. Bei jedem Commit muss manuell die addon.xml Version erhöht werden
2. Github webpage downloaden und per regex den letzten commit herausparsen. Diesen in einer Temp datei speichern und wenn er sich ändert neu updaten und den neuen speichern

Take a choice ;)

**Comment by ghost** [comment]
https://developer.github.com/v3/repos/commits/

? ^^

**Comment by sraedler** [comment]
Da müsstest aber wieder eine lib eingebunden werden, oder irre ich mich?

**Comment by ghost** [comment]
Du musst einfach nur z.b folgendes Aufrufen:

https://api.github.com/repos/StoneOffStones/plugin.video.xstream/commits/nightly

Dann bekommst die Commits der nightly als json. Und besser gehts vermutlich nicht ;)

**Comment by sraedler** [comment]
Da hast du recht, hab es eben auch versucht ^^

Werde es einbauen!

Danke :+1:

**Comment by ghost** [comment]
(Habe ich gesehen weil dein Kommentar schon wieder gelöscht wurde^^)

**Comment by Ston3s** [comment]
Hab es erst jetzt gelesen.
Sonst ist mir noch die Idee gekommen, dass man beim Nighly auf bis zweimal pro Tag beschränken könnte und zusätzlich eine Option einbaut um das Update manuell anzufordern.

**Comment by Ston3s** [comment]
Leute ich muss echt sagen das arbeiten/ zusammen arbeiten mit euch hier über die Issues ist echt super.
Macht richtig Spaß und ist oben drein noch recht produktiv!

:)

**Comment by ghost** [comment]
Ist ja jetzt nicht mehr nötig. Bei diesen Variante wird ja nur 4/5kb groiße Datei geladen. Und geprüft ob ein Update nötigt ist. Für den Anwender quasi unbemerkt.

@sraedler 
Btw. es gibt auch ne **since** und **until** Eigenschaft in der API. Evtl. könnte damit die Abfrage noch kleiner halten. SPrich das man das **since** auf das Datum des letzte Update setzt. Somit hätte die JSon wirklich nur die Commits seit dem letzten Update.

Damit wäre A) die Abfrage kleiner und B) könnte man sogar so crazy shit machen wie (Update erst wenn es 5 Commits gab) => auch wenn ich das für unnötig halte. ABER man könnte es ^^

**Comment by sraedler** [comment]
@Viper2k4 ja, das klingt echt nice :+1: 

Würde es aber denk jetzt erst mal so lassen, denn 5kb ist eine größe die man innerhalb von millisekunden laden können muss, sonst ist streamen eh hinfällig ;)

Und zusätzlich ist die anfrage nach since auch bestimmt 3kb groß...

Aber man könnte es im hinterkopf behalten!

**Comment by ghost** [comment]
Ist mehr ne Prinzip Sache :).

Nur werden es ja immer und immer mehr commits. Damit wird die Abfrage natürlich mit jeden commit untnötig größer.

Aber wie gesagt aktuell reicht es erstmal so. Aber nicht vergessen :)

**Comment by Ston3s** [comment]
Wie ist das eigentlich mit den 3-5kb großen Daten, häufen sich diese immer weiter an oder werden die nach dem Update bzw. gewissen wieder gelöscht.

Nicht das, dass System langfristig zugemüllt wird!

**Comment by ghost** [comment]
Es wird keine Datei geschrieben. Die Daten werden nur in eine Variable geschrieben und benutzt. Mit verfall der Variable (quasi nach benutzung) fliegt sie aus dem RAM und ist quasi weg.

**Comment by sraedler** [comment]
@Viper2k4 versuch es mal mit dem  [Master](https://api.github.com/repos/StoneOffStones/plugin.video.xstream/commits/master) oder [Beta](https://api.github.com/repos/StoneOffStones/plugin.video.xstream/commits/Beta) im Browser

Da werden nie mehr angezeigt.

Jedoch bin ich eben auf ein "Problem" gestoßen, bei vielen calls, wird deine IP gesperrt für eine Stunde oder so (ab 60 aufrufen laut API)
Weiß aber nicht wann meine IP wieder freigeschalten wird.

**Comment by Ston3s** [comment]
Funktion ist "final" als Milesone für beta3 realistisch, beta2 ist ja bereits raus ;)

**Comment by Ston3s** [comment]
Problem mit der API kann ich auch bestätigen, konnte das Addon sogar nicht öffnen also auch nicht auf die Site-Plugins zugreifen.

Erst als ich über das Kontext Menü in die Einstellungen ging und die Bezugsquelle für das AutoUpdate auf Beta geändert hatte konnte ich es wieder normal nutzen.

**Comment by sraedler** [comment]
ah ich verstehe ^^

Bau morgen oder so ein bugfix ein

**Comment by Ston3s** [comment]
👍🏼

**Comment by sraedler** [comment]
Done  559fd9b

**Comment by Ston3s** [comment]
Issue abgeschlossen?!

**Comment by sraedler** [comment]
Ja ist abgeschlossen
