### ISSUE TITLE
Hoster Parsing Error in MoviesEver

### ISSUE THREAD

**Issue by sraedler** [StoneOffStones/plugin.video.xstream#26]
MoviesEver geht nicht mehr

**Comment by seberoth** [comment]
Also bei mir läuft es noch einwandfrei. Das einzige was ich festgestellt habe, ist das viele Filme keine Hoster mehr haben (also auch auf der Seite)

**Comment by Ston3s** [comment]
Problem noch bestehend?
Ich konnte bei mir nichts feststellen außer der Situation, die seberoth bereits geschildert hat.

Abgeschlossen?!

**Comment by sraedler** [comment]
Naja, also bei mir geht es nicht immer und das find ich falsch. 

Bei neue Filme geht bei mir kein einziger und dass ist auf der Webseite nicht so z.B. Transporter geht da, im Plugin nicht.

Oder Unknown User, das geht zwar auf der Webseite auch nicht, aber das dauert im Plugin ewig und dann kommt eine Fehlermeldung.

**Comment by sraedler** [comment]
Also auf der Webseite ist das selbe verhalten, daher nicht xStream's problem
