### ISSUE TITLE
[Site-Plugin] Bundesliga.de

### ISSUE THREAD

**Issue by Ston3s** [StoneOffStones/plugin.video.xstream#27]
Macht die Seite überhaupt noch Sinn.
Seitdem ich xStream benutze kann ich mich nicht daran erinnern, dass das Plugin bzw. die Seite mal zuverlässig funktioniert  hätte.

Löschen oder behalten?!

**Comment by sraedler** [comment]
Ich würde nicht alles gleich löschen, nur weil es nicht geht. es ist natürlich nicht Priorität 1, aber wenn zeit dafür ist, dann wird auch das gefixt, weil warum die bisherige arbeit wegwerfen?

**Comment by Ston3s** [comment]
Ah ok, wenn es zu fixen ist sehe ich es ganz genau so!
Irgendwo hatte ich mal gelesen das auch diese Seite down, nicht mehr zu verwenden oder sowas in der art ist.
Dann parken wir das einfach erstmal ;)

**Comment by sraedler** [comment]
So nachdem ich mir das angeschaut hab, bin ich zur Schlussfolgerung gekommen, Bundesliga.de hat zu wenige Videos, dass es sich rentiert.

Es gibt wirklich kaum Videos, daher hab ich es gelöscht.

Wenn es keine einwende gibt, wird der Issue geschlossen
