### ISSUE TITLE
BS.to uses now HTTPS

### ISSUE THREAD

**Issue by Ston3s** [StoneOffStones/plugin.video.xstream#28]
Hallo,

soeben habe ich erfahren, dass BurningSeries ab heute das sichere HTTPS verwendet und die Serien somit nicht mehr über xStream erreichbar sind.

Hier die Fehlerbeschreibung:

[http://xstream-addon.square7.ch/showthread.php?tid=608]()

**Comment by ghost** [comment]
Gucke nachher mal was geht

**Comment by ghost** [comment]
HTTPS ist nicht das Problem. Die API ist nicht mehr frei verfügbar wie es aussieht. Der Response ist wie folgt:

{"error":"unauthorized","unauthorized":"no_token"}

**Comment by ghost** [comment]
btw. wieso ist BS nicht in der nightly?

**Comment by Ston3s** [comment]
Ok und wie gehen wir jetzt weiter vor?!

BS ist doch drin, habe nur auf die neue Webseitennamen+Domain angepasst.
Jetzt unter bs_to.py

**Comment by ghost** [comment]
Keine Ahnung. Ich wir können entwender die Parser-Version einbauen oder halt ne Key erfragen und dann irgend was zureche Programmieren wie in dem anderen Addon.

Damit wir den Key quasi online ändern können ohne Update vom Addon selbst.

**Comment by sraedler** [comment]
Wie ist der aktuelle Stand?

Komm im Forum nicht so ganz mit, weil kreuz und quer Gepostet wird ^^

**Comment by Ston3s** [comment]
Ich muss sagen ich auch nicht ganz.
Bevor ich jetzt die Jungs von BS kontaktiere würde ich schon gern wissen ob das Problem überhaupt das missen einer neue API ist.

**Comment by halidri** [comment]
Es liegt am urlresolver von Kodi, der ist ohne TLS Unterstützung, wollte es gestern im Forum schon schreiben, aber leider ist es ja down.

**Comment by Ston3s** [comment]
Und warum geht dann das BurningSeries Addon dann noch?!
Das benutzt ja mit Sicherheit ebenfalls den URLResolver

**Comment by ghost** [comment]
HTTPS, URL-Resolver und go sind dadran nicht schuld.

Der URL-Resolver wird erst aktiv wenn man einen, jetzt kommt's, URL resolven möchte. Und das ist in der Regel erst der Fall wenn man einen Stream aufruft.

Das Problem ist das die API-Anfragen einfach nicht mehr funktionieren. Diese Anfragen sind dumme HTTP anfragen mit Key im Header.

Und damit haut irgend was nicht hin.

**Comment by seberoth** [comment]
Hi,
hab leider grad kein Kodi zur Hand, deswegen konnte ich es nicht damit testen, jedoch sollte folgendes abhilfe schaffen (und im Site plugin die url ändern)

https://gist.github.com/seberoth/e0b34838bb44839cbba1

**Comment by ghost** [comment]
habs getestet. Änderung der URL's im Siteplugin war nich nötigt.

Vielen dank :)

**Comment by seberoth** [comment]
Noch ein kleiner Nachtrag:

Ist zwar funktionel nicht bedeutsam, aber damit es vollständig angepasst ist, muss der 2te addHeaderEntry noch durch folgendes ersetzt werden.

https://gist.github.com/seberoth/c6f3530f26e162aa6674

**Comment by ghost** [comment]
Du bist Collaborator kannst direkt einreichen wenn möchtes :)

**Comment by ghost** [comment]
Hab's angepasst. Hoffe das passt jetzt :)

**Comment by Ston3s** [comment]
Gibt es bei BS eigentlich auch sowas wie bei vielen anderen Seiten ala Letztes Update oder Neu hinzugefügt?
Als das Forum noch online war hatte ich eine Mail mit genau her frage erhalten.

Soll es wohl früher vor der Änderung auf die API gegeben haben...

**Comment by Ston3s** [comment]
Werde mit dem letzten Punkt ein neues Issue eröffnen aber dieser Punkt sollte ja abgeschlossen sein!
