### ISSUE TITLE
[Site-Plugin] Logo für HDfilme

### ISSUE THREAD

**Issue by Ston3s** [StoneOffStones/plugin.video.xstream#29]
Hallo Leute,

mir ist heute ins Auge gefallen, dass HDfilme einen "neuen" grünen Grundfarbton auf der Seite verwendet.
Jetzt wollte ich das bestehende Logo in xStream dazu anpassen, dabei ist mir aufgefallen, dass HDfilme bei Google+ und Facebook ein ganz anderes Logo verwendet.
Jetzt stellt sich die Frage soll ich das offizielle von den Social-Plattformen oder den alten Schriftzug nehmen?!

![hdfilme2](https://cloud.githubusercontent.com/assets/12751497/14030058/e86a4b78-f205-11e5-96c8-5b44cee77dfd.png)
![bildschirmfoto 2016-03-24 um 21 16 15](https://cloud.githubusercontent.com/assets/12751497/14030061/ec87f07a-f205-11e5-9b19-52bc018b6727.png)

**Comment by Ston3s** [comment]
In Kodi würde es in etwa so aussehen...
![bildschirmfoto 2016-03-24 um 21 21 15](https://cloud.githubusercontent.com/assets/12751497/14030315/4ca28104-f207-11e5-9bc4-7dc31f4ece5e.png)
![bildschirmfoto 2016-03-24 um 21 27 06](https://cloud.githubusercontent.com/assets/12751497/14030317/4df2bb32-f207-11e5-96bc-98ba2bfad99b.png)

**Comment by ghost** [comment]
Ich muss sagen ich finde das Ganz grüne schöner (wenn auch nicht wirklisch schön). 

Fallst lust hast kannst den Kollegen von der Seite ja mal nen neues Logo bauen und ihnen dabei direkt mitteilen das ihre Sortierung auf der Seite nicht funktioniert ^^

**Comment by Ston3s** [comment]
Bin leider auf Facebook und Co nicht unterwegs!
Weiß auch nicht ob es nicht ein bisschen zu dreist wäre wenn ich die Jungs auf ihr unschönes Logo anspreche... ;)

**Comment by sraedler** [comment]
Würde auch eher das ganz grüne bevorzugen, weil das andere so arg an Facebook erinnert ^^

aber ist mir eigentlich egal ;)

**Comment by Ston3s** [comment]
Mir ist es eigentlich egal, habe nur entdeckt das es dabei um das offizielle Logo von HDfilme handelt.
ob auf Google+ oder sogar bei Facebook überall ist die Seite damit angemeldet.
Ich finde nur das so grün so beißend ist und bei dem runden ist es etwas dezenter!

**Comment by Ston3s** [comment]
Habe jetzt das grüne nochmals etwas überarbeitet, sodass sowohl der Grünton als auch der leichte Schimmer-Effekt jetzt auch vorhanden sind!
