### ISSUE TITLE
Integrate the newest urlresolverversion

### ISSUE THREAD

**Issue by sraedler** [StoneOffStones/plugin.video.xstream#30]
In den nächsten Tagen kommt höchstwahrscheinlich eine neue Version von urlresolver heraus. Diese sollten wir umgehend unterstützen

Im voraus, sollen wir die aktuelle und die 2.9.0 unterstützen? 

Also wenn eine Funktion aufgerufen wird, dass diese erst abfragt, welche urlresolverversion installiert ist.

**Comment by sraedler** [comment]
https://github.com/tknorris/script.module.urlresolver/issues/67

also ab morgen gibt es Arbeit, denn das autoupdate der repo wird bei einigen Benutzern die neue version laden.

evtl. könnte man das heute mit der Beta schon vorbereiten, hab gesehen da passen ein paar Sachen nicht (priority z.B.)

**Comment by sraedler** [comment]
Sollte alles gewesen sein.

**Comment by Ston3s** [comment]
Heißt das, dass man jetzt die neueste 2.10.13-Beta installieren kann?

**Comment by sraedler** [comment]
Ja kann man
