### ISSUE TITLE
Integrate CinePlex.tv

### ISSUE THREAD

**Issue by sraedler** [StoneOffStones/plugin.video.xstream#31]
Evtl. als Site Plugin aufnehmen

**Comment by sraedler** [comment]
Der erste Teil ist gemacht: dec1de3

TODO: 
- Suche
- Serien
- Erscheinung
- Schauspieler

Da bis Mitte der Woche keine zeit hab hier der Commit. Wenn jemand Langeweile hat kann er das ja weiter machen ;)

P.s. Bin mir aber nicht sicher wie sinnvoll es noch ist, weil die Website nicht allzu groß bzw. befüllt ist, hab es nur erst spät gemerkt ^^

**Comment by ghost** [comment]
Wenn dem so ist finde ich das wir nicht jede kleine seite einbauen sollte :)

**Comment by sraedler** [comment]
ja, da hast recht!

es sind schätzungsweise 1200 Filme

was meint ihr?
Löschen oder weiterentwickeln ?

**Comment by ghost** [comment]
ddl.me hat im vergleich 15036. Ich würde sagen löschen. Und die anderen?

**Comment by Ston3s** [comment]
Wenn es Alternative Seiten gibt die mehr bieten dann würde ich die Arbeit definitiv verlagern

**Comment by Ston3s** [comment]
Kann allerdings den weiterhin benötigten Arbeitsaufwand nicht ganz abschätzen. Wäre auch um die bereits am investierte Arbeit schade. Wenn überschaubar würde ich die Arbeiten an der Seite noch abschließen aber bei zukünftigen genauer drauf achten ;)

**Comment by Kukolorus** [comment]
Wenn ich das recht sehe, hat das denn nicht schon jemand vor 4 Stunden gemacht? Also die Seite der nightly hinzugefügt? Weil da steht das vor 4 Stunden eine cineplex.py hinzugefügt wurde. 

Ich würde es schon cool finden, ich glaube auch das jede Seite eine Bereicherung für xStream ist, aber natürlich muss sich der Aufwand auch lohnen, da stimme ich euch zu.

Würde ja selber gerne helfen, auch da ich relativ viel Zeit habe und mir manchmal langweilig ist, da ist das bestimmt ganz nett Musik zu hören, Tee zu trinken und solche Seiten hinzuzufügen. Aber ich stelle mich einfach, glaube ich, ein bisschen Dumm an, das TuTo auf der xStream Seite habe ich auch nur so halb verstanden :D

_EDIT_ Würde es ja schon gerne "lernen". :/

**Comment by ghost** [comment]
Naja mehr seiten führen zurzeit dann stark zu weniger übersicht. Daher würde ich am besten große Seiten aufnenhmen wenn möglich. Oder Seiten wo wir das Thema nicht abdecken wie zb. Anime.

So Plugin mal kurz zu schreiben das es "etwas" funktioniert geht recht fix. Zumal man sich auch recht viel zusammen kopieren kann. Da die Seiten doch recht identisch von der Funktion sind.

**Comment by Kukolorus** [comment]
Dass wir Seiten aufnehmen sollten mit Genres die wir noch nicht haben finde ich auch sinnvoller, da muss ich dir zustimmen. Eigentlich haben wir abgesehen von Anime doch alle Genres, oder vergesse ich da was, von Action bis zu Pornos haben wir doch eigentlich alles vertreten, nur halt das z.B. Pornos bei Seiten wie Movie4K.to enthalten sind. Aber eine extra Anime-Seite würde bestimmt auf positives Feedback stoßen.

_Zu dem Plugin schreiben_ Naja, trotzdem würde ich das gerne mal nebenbei machen... 
Ich will ja nicht sagen das man sowas in der Schule lernen sollte, doch sollte man in der Schule vielleicht im Fach Informatik bzw PCI (PC-Information) spezifischere Sachen durchnehmen, wir machen nämlich in diesen Fächern Microsoft Word und PowerPoint ...von 2007... Das sieht heute alles voll anders aus und ist einfach nur dämlich, hätte den jemand irgendwie ein TuTo oder so? ganz zufällig? :D 

Ach übrigens; Frohe Ostern! :D

**Comment by Ston3s** [comment]
Ich bin auch ein Quereinsteiger. Wenn ich Zeit über habe versuche ich die Programmiersprache Python mehr zu verstehen.
Dazu ziehe ich mir die Tutorials von YouTube rein ;)

**Comment by Ston3s** [comment]
Hab da was ;)

![cineplex](https://cloud.githubusercontent.com/assets/12751497/14075691/75489342-f4db-11e5-959b-bea28836a032.png)
![cineplex2](https://cloud.githubusercontent.com/assets/12751497/14075689/75473a4c-f4db-11e5-8684-201b29c611ec.png)
![cineplex3](https://cloud.githubusercontent.com/assets/12751497/14075690/7547c87c-f4db-11e5-8895-307e5bd9e0ff.png)
![cineplex4](https://cloud.githubusercontent.com/assets/12751497/14075692/7548c02e-f4db-11e5-8ed0-60320e23c917.png)

Finde das mit dem Stern ganz gut jedoch ist dann der Schriftzug zu klein!
Mein Favorit ist weiß auf grau, alternativ geht auch schwarz auf grau...

**Comment by Ston3s** [comment]
cineplex_tv.px und SiteInfo: CinePlex

**Comment by sraedler** [comment]
also doch behalten ?

bin mir nämlich auch nicht sicher ob der weitere Aufwand sich lohnt oder ob ich eher das Anime-loads Versuch mit recaptcha...

**Comment by Ston3s** [comment]
Teilweise ist es ja schon implementiert.
wenn du erstmal am anderen weiter machen möchtest kann man ja die arbeiten hier nach hinten verschieben.
Aber etwas zu löschen was bereits zum Teil funktioniert wäre doch unsinnig oder?!

**Comment by sraedler** [comment]
ja, kann jeder der Zeit und Lust hat weiter machen

**Comment by ghost** [comment]
Was meint ihr? Falls jetzt keiner Lust hat das ganze zuende zu bringen. Ab mit der Seite ins BackUp branche? So wäre sie nicht weg. Aber wir sind sauber im Branch und der Issue kann erstmal zu?

**Comment by sraedler** [comment]
ja, bin ich auch dafür!

**Comment by ghost** [comment]
@StoneOffStones machst du das? ^^ Ich würde dann wiedr wild rum commiten sonst :)

**Comment by Ston3s** [comment]
Wird später erledigt!

**Comment by Ston3s** [comment]
Wurde soeben aus nightly entfernt und in backup abgelegt!

**Comment by ghost** [comment]
Dann schließen wir das, braucht ja nicht offen sein oder?

**Comment by Ston3s** [comment]
Weiß ich nicht ganz genau, wird ja vielleicht in Zukunft noch fertig gemacht.
Habe den Milestone auf "future release" gesetzt.
Wenns geschlossen wird, wird der Punkt sehr wahrscheinlich vergessen...

**Comment by Ston3s** [comment]
Wird erstmal bis auf weiteres geparkt, kann bei Bedarf wieder gerne geöffnet werden!!!
