### ISSUE TITLE
Integrate SerienStream.to

### ISSUE THREAD

**Issue by Ston3s** [StoneOffStones/plugin.video.xstream#32]
Evtl. als Site-Plugin integrieren...

**Comment by Ston3s** [comment]
Hab mir mal die Seite genauer angeschaut und diese sieht ziemlich vielversprechend aus.
Extrem umfangreiches Portfolio ;)

**Comment by Kukolorus** [comment]
Das freut mich das so viel über meine Vorgeschlagenen Seiten Diskutiert wird :)

**Comment by sraedler** [comment]
Kannst du etwas genaueres dazu sagen? Wie meinst du umfangreiches Portfolio?

Denk da ist [video4k.to](http://video4k.to/) deutlich umfangreicher und sollte eher angegangen werden.

video4k hat nämlich circa 5400 Serien und 35000 Filme, wobei ältere nicht mehr so oft online sind.

**Comment by Ston3s** [comment]
Ok die Seite war mir bis jetzt nicht bekannt!
Man kann ja erstmal die neuen Seiten vorstellen und dann im Nachhinein gemeinsam bewerten.

**Comment by Kukolorus** [comment]
Toll, da kann ich noch eine Seite zu meinem Streaming Ordner hinzufügen :D 

:+1:

**Comment by sraedler** [comment]
Es gibt unzählige Seiten, welche wirklich nach dem Mehrwert für xStream durchforstet werden können ;)

siehe [hier](http://startseite.to/) (Es gibt natürlich einige solche listen, wie RaidRush auch anbietet)

oder ein englischer Anbieter mit vielen links [wheretowatch.to](https://www.wheretowatch.to)

**Comment by Ston3s** [comment]
Wird erstmal geparkt und kann bei Interesse jederzeit wieder aktiviert werden!!!
