### ISSUE TITLE
Forum down

### ISSUE THREAD

**Issue by AlleSchonWeg** [StoneOffStones/plugin.video.xstream#33]
Hi,

ist das Forum nicht mehr erreichbar oder ist die URL falsch? xstream-addon.square7.ch

MfG

**Comment by Kukolorus** [comment]
Nein, erreiche das Forum seit ca ein einhalb Stunden nicht mehr :(

**Comment by Ston3s** [comment]
Ist mir auch schon aufgefallen aber keine Ahnung was da gerade stattfindet.

**Comment by Kukolorus** [comment]
Hatte mich nur nicht so recht getraut hier ein thema zu eröffnen, da es ja hier in erster Linie um xStream Beta Probleme geht xD

**Comment by AlleSchonWeg** [comment]
Ok, dann bin ich nicht der einzige. ;)
Wusste sonst nicht wo man posten sollte, deswegen einfach mal hier :)

**Comment by Ston3s** [comment]
Das stimmt schon, aber geradewegs ja nichts anderes.
Was noch mehr Sinn machen würde ist Lynx187  im Madter Branch direkt zu fragen ;)

**Comment by Kukolorus** [comment]
Ja... und jetzt? :D

**Comment by ghost** [comment]
Nichts? Ist nicht unser Forum. Also warten

**Comment by Ston3s** [comment]
Hallo zusammen,

ich habe die Frage mal ans richtige Adressat weitergeleitet und bitte euch, wie bereits schon Viper2k4, die Füße still zu halten und entweder auf das wiedererschienen der Website bzw. ein Statement von Lynx187 geduldig zu warten.
https://github.com/Lynx187/plugin.video.xstream/issues/100

Das Thema hier an der Stelle ist für mich damit erledigt!

**Comment by seberoth** [comment]
So, ich hoffe mal das Github auch bei geschlossenen Issues benachrichtigungen verschickt :P 

Da das Forum ja down ist, und ich die Besprechung von Features im Ticketsystem nicht wirklich mag, kann ich euch eine temporäre Lösung anbieten. Und zwar hab ich auf meinem privaten Dev-Server Redmine installiert, wo auch eine rudimentäre Foren funktion integriert ist.

Wer interesse hat, kann sich ja anmelden (Benutzter schalt ich per Hand frei, deshalb wäre es nett, wenn Ihr die selben Namen benutzt).

Fast vergessen, hier der Link: https://rm.bg-entwicklung.de

**Comment by sraedler** [comment]
Hammer!
Fände das als Entwickler Forum für längere Zeit super ;)

**Comment by sraedler** [comment]
hab es geöffnet damit die Nachricht an die anderen weiter geht ;)

**Comment by Kukolorus** [comment]
Oha, sehr schön, gleich mal registrieren. ;)

**Comment by Ston3s** [comment]
Danke für die Notiz, werde mich sobald ich etwas Zeit habe direkt anmelden!

**Comment by Ston3s** [comment]
Info von Lynx187 aus der Master-Issue:

Ok ich weiss inzwischen das Warum: es wurden ungewöhlich viele Mails versendet. Dadurch wurde angenommen dass Spam versendet wird und somit automatisch die Seite deaktiviert. Jetzt müsste ich schaun ob der Code tatsächlich kompromittiert wurde und es ggf. bereinigen. Echt K.A. ob ich darauf noch Lust habe.

**Comment by seberoth** [comment]
Nur als Info: Auch wenn ihr keine Benachritigung bekommt, die die sich bereits registriert haben, wurden alle freigeschaltet.

P.S.: Nur um das nochmal zu verdeutlichen, das soll kein Support-Forum werden, sondern nur für die hier anwesenden Devs.
