### ISSUE TITLE
Integrate Gute-Filme.to

### ISSUE THREAD

**Issue by Kukolorus** [StoneOffStones/plugin.video.xstream#39]
Wäre ein Vorschlag, dies ist eine Seite die alte bis sehr alte Filme anbietet. Ich weiß ja nicht wie die Nachfrage nach solchen Klassikern und Raritäten ist, wenn nicht einfach das hier wieder schließen :)

http://www.gute-filme.to/

**Comment by Ston3s** [comment]
Ist auf jeden Fall noch nicht im Portfolio von xStream vorhanden...

**Comment by ghost** [comment]
Muss noch Eierverstecken und dann mach ich das nachher fertig.

Kannst bis dahin ja nen Icon bauen und mir sagen wie ich die Datei benennen soll.

**Comment by Ston3s** [comment]
Ich meinte die Art der Medien. Es geht hier rein um Klassiker.
Allerdings wird im Vergleich zu anderen integrierten Seiten mit knapp 800 Filmen recht wenig geboten.

**Comment by Ston3s** [comment]
@Viper2k4 kann gerne in die Richtung unterstützen, bin jedoch erstmal die nächsten Stunden out of order...

**Comment by Kukolorus** [comment]
Könnte ich denn in irgendeiner Form helfen?

**Comment by burnmaster** [comment]
Für Klassik-Liebhaber auf jeden Fall eine Alternative, sicherlich sind auch ein paar Filmklassiker für meinen Vater interessant. :)

Habe gerade auch was auf der Seite gesehen, um die Seite etwas fixer zu parsen.
Man kann in der URL angeben, wie viele Filme pro Seite angezeigt werden, über folgende Settings: grid/4:6 --> Man kann z.B. 10:10 angeben.
So könnte man das Parsen auf wenige Seiten beschränken.

Falls Unterstützung benötigt / gewünscht, biete mich natürlich auch an. :)

**Comment by Ston3s** [comment]
Jetzt habe versehentlich Logo für Cineplex.tv bereitgestellt. Ups, war keine Absicht!
Jetzt bin ich erstmal unterwegs, kann aber heute Abend nachliefern.

@burnmaster: Hilfe wird immer sehr gerne entgegengenommen!
Wenn du möchtest kannst du sehr gerne hierbei viper2k4 unterstützen. Wieder einfach über PR einreichen ;)

**Comment by ghost** [comment]
Blöde Frage. Aber sollte man direkt loslegen im Menü oder sollte man erste "Filme" anklicken. Weil Serien gibt es ja nicht ^^

**Comment by Ston3s** [comment]
Wenn keine Serien dann gleich mit Filmen durchstarten :)
Außer es gibt wieder Genre und andere Ordner...

**Comment by ghost** [comment]
Wollte es wie folgt aufbauen:

Filmliste
Genre
Sammlung
Suche

oder wirklich:

Filme
Suche

Sprich alles in den Ordner Filme packen?

**Comment by Ston3s** [comment]
Finde ich wie du vorgeschlagen hast ziemlich gut!

**Comment by Kukolorus** [comment]
Vielleicht als Genres die Jahrzehnte benutzen wie auf der Seite bzw. einen "Jahrzehnte-Ordner" einführen, für Leute die Filme aus bestimmten Zeiten suchen; 

![asdasdasdasdsada](https://cloud.githubusercontent.com/assets/18074507/14078426/09a5d4a4-f4f6-11e5-841f-ea0fefee6d4e.PNG)

**Comment by burnmaster** [comment]
Wollte ich auch gerade vorschlagen, denkbar wäre auf der ersten Seite folgende Auflistung:
Alphabetisch
Genre
Jahr
Sammlungen
Suche

Und dann die einzelnen Seiten auflisten.

**Comment by Kukolorus** [comment]
Jap, das ist eine gute Unterteilung.

**Comment by Kukolorus** [comment]
Ähm, scheiße wie

**Comment by Kukolorus** [comment]
Okay, sorry erstmal das ich das ausversehen geschlossen habe, finde die Aufteilung gut xD

Sorry,sorry sorry xDD

**Comment by ghost** [comment]
Mein Problem ist eher das der URL resolver nicht damit klar kommt :'(

```
15:50:28 T:8112  NOTICE:    [xStream] ->gute_filme: xStream checkforupdates
15:50:28 T:8112  NOTICE:    [xStream] ->gute_filme: xStream Remoteversion: 2.1.15
15:50:28 T:8112  NOTICE:    [xStream] ->gute_filme: xStream Localversion: 2.1.16~beta2
15:50:28 T:8112  NOTICE:    [xStream] ->gute_filme: {'function': 'showHosters', 'thumb': 'http://i1.wp.com/www.gute-filme.to/wp-content/uploads/2016/03/1nMIyBkc5JXTyiJMv3il11Pf01g.jpg', 'title': '2001: Odyssee im Weltraum', 'sUrl': 'http://www.gute-filme.to/filmliste/grid/2/4:6/title/ASC/page/1/', 'mediaType': 'movie', 'site': 'gute_filme', 'entryUrl': 'http://www.gute-filme.to/film/2001-odyssee-im-weltraum/', 'playMode': 'play', 'MovieTitle': '2001: Odyssee im Weltraum'}
15:50:32 T:8112  NOTICE:    [xStream] ->gute_filme: attempt to play file
15:50:32 T:8112  NOTICE: URLResolver: Initializing URLResolver version: 2.10.12
15:50:32 T:8112  NOTICE: URLResolver: No Settings Update Needed
15:50:32 T:8112  NOTICE:    [xStream] ->gute_filme: resolve: https://openload.co/embed/XAGAikuQcEs/2001.Odyssee.im.Weltraum.1968.German.DL.AC3.DVDRiP.XViD-QRC.avi.mp4
15:50:32 T:8112   ERROR: URLResolver: Resolver Error - From: openload Link: https://openload.co/embed/XAGAikuQcEs/2001.Odyssee.im.Weltraum.1968.German.DL.AC3.DVDRiP.XViD-QRC.avi.mp4: Exception in openload: the owner of this file doesn't allow API downloads, please use browser instead
15:50:32 T:8112  NOTICE:    [xStream] ->gute_filme: Stream nicht mehr verfügbar oder Link fehlerhaft UnresolveableCode: -
```

**Comment by ghost** [comment]
OK Fehler behoben. Hatte nicht den neusten "URL-Resolver". Hier ist der Fix:

https://github.com/Eldorados/script.module.urlresolver/pull/364

**Comment by ghost** [comment]
Habe alles soweit eingebaut (außer die Sammlungen atm.). Bitte mal prüfen: https://github.com/StoneOffStones/plugin.video.xstream/commit/5158d5f3efbc971956e4ac1fb101d5fb067ebb42

Acho und prüft ob ihr den neusten GIT-Stand von https://github.com/Eldorados/script.module.urlresolver habt. Ohne die Version läuft Openload nämlich irgendwie nicht.

**Comment by Ston3s** [comment]
Wird gleich mal getestet!
Habe auch gleich als ich eben zu Hause ankam das Icon erstellt...
![gutefilme](https://cloud.githubusercontent.com/assets/12751497/14086053/8111f8e2-f523-11e5-96af-e35422ff49f2.png)

**Comment by Ston3s** [comment]
Sieht alles gut aus soweit.
Das einzige ist der Ordner Filmliste. Auch weil nochmals der Ordner Alle drin ist.
Im Grunde ist es doch "Alle Filme" und "A-Z"!

**Comment by ghost** [comment]
Kann ich ändern. Aber die Seite ist halt genau so aufgebaut :)

Ich könnte auch:

Alle
A-Z
Genre
Suche

machen

**Comment by Ston3s** [comment]
Fände ich logischer...

**Comment by Ston3s** [comment]
Den Begriff Filmliste kann man mal so garnicht sinnvoll zuordnen.

**Comment by ghost** [comment]
done => https://github.com/StoneOffStones/plugin.video.xstream/commit/55a700e6172ea0457d7f946bbb46f8035a85ab62

**Comment by Kukolorus** [comment]
Also ich habe eben mal probiert, bei allen Filmen steht das der stream nicht geöffnet werden kann oder der link nicht existiert.

Liegt das an irgend ein captcha?

**Comment by ghost** [comment]
Dann scroll bitte etwas nach oben:

"Acho und prüft ob ihr den neusten GIT-Stand von https://github.com/Eldorados/script.module.urlresolver habt. Ohne die Version läuft Openload nämlich irgendwie nicht."

**Comment by Kukolorus** [comment]
Oh. Ok in Ordnung. Werde es mal testen.

Habe das Gefühl das ich nerve xD

Entschuldigung dafür..

**Comment by Ston3s** [comment]
Schon viel besser, danke!
Ich würde jetzt noch vielleicht aus Alle >>> Alle Filme machen dann stellt sich die Frage bezüglich des Inhaltes automatisch nicht mehr...

**Comment by ghost** [comment]
done https://github.com/StoneOffStones/plugin.video.xstream/commit/6b43309ba50f4e0da0e03b24beab620bf5ad3819

**Comment by Ston3s** [comment]
Issue damit erledigt?!

**Comment by ghost** [comment]
könnte man sagen falls keiner mehr was sagt

**Comment by Lynx187** [comment]
Naja wie bei inzwischen manchen anderen Siteplugins wird dieses die globale Suche stören weil während der Suche die Liste abgeschlossen wird.

**Comment by ghost** [comment]
Es sagt einem ja auch niemand das dies nicht erlaubt ist ^^

Wie ist es denn mit der "next-Page" kommt die Globale-Suche damit klar oder kann sie defacto nur einen Seite anzeigen? (ok ist worst case das die Suche soviel zurück gibt)

**Comment by Lynx187** [comment]
Stimmt du hast dir leider ein fehlerhaftes als Vorbild genommen.
Obwohl man im log dann sieht dass er fröhlich invalid Handle meldet.
Hättest du bei mir eingereicht hätt ich dirs sofort sagen können ;-)

Jein, der next page link könnte theoretisch angezeigt werden, wird aber gefiltert.

**Comment by ghost** [comment]
Jop daher sind leider alle meine Plugins betroffen :(

Habe soweit jetzt glaube meine 3 Plugins gefixt. Jedoch sind mir dabei 2 Sachen aufgefallen:
- NextPage wird angezeigt und wirft einen dann in das jeweilige Plugin
- bei machen Einträge wird nicht angezeigt von welche Seite sie kommen

**Comment by Lynx187** [comment]
Achso dann ist der filter nur bei alterSearch aktiv.
Weiss ich hab den commit dazu noch nicht gesyncht

**Comment by ghost** [comment]
Ok dann habe ich das jetzt erstmal gefixt. Ich kann da ja jetzt aber erstmal nur für meine 3 Plugins + Vorlage (wo ich mir die Suche abgeguckt habe) sprechen. KKiste macht leider auch noch Probleme :/

Und sry für die vielen Commits.Habe mir jetzt erst Github für Desktop besorgt. Jetzt kann ich endlich auch commits zusammen fassen ^^
