### ISSUE TITLE
Newest Series/Last Episodes for BS.to

### ISSUE THREAD

**Issue by Ston3s** [StoneOffStones/plugin.video.xstream#40]
Gibt es bei BS eigentlich auch sowas wie bei vielen anderen Seiten ala Letztes Update oder Neu hinzugefügt?
Als das Forum noch online war hatte ich eine Mail mit genau her frage erhalten.

Soll es wohl früher vor der Änderung auf die neue API gegeben haben...

**Comment by Kukolorus** [comment]
Mhm, also wenn man auf BS geht ist ja auf der rechten Seite eine kleine Box die neue Serien anzeigt, nur leider kann man nicht auf die Box klicken und sie zeigt nur die neusten 4 an.

Aber sonst kenne ich das von Burning Series nicht^^

**Comment by Ston3s** [comment]
Ja, das Fenster habe ich auch bereits gesehen.
Der User, der mich anschrieb, berichtete das "damals" über die alte API wohl die die letzten 100 Episoden/Updates übergeben bzw. angezeigt wurden.

Kann das leider auch nicht entsprechend nachvollziehen.
Aber vielleicht kann einer von den begnadeteren Entwicklern dazu was sagen.
Ist auch nicht schlimm wenn dies heute nicht mehr gegeben ist dann kann das Issue auch Direkt geschlossen werden. ;)

**Comment by burnmaster** [comment]
Hm, also in der bs-api.doc find ich keine passende Methode, die das bieten soll.
Auch die Android-App nutzt leider keine passende Methode, welche man ggf. hätte sniffen können.

**Comment by halidri** [comment]
Früher, vor der API Änderung gab Diese die letzten 200 Epison als Info frei, nutzte es immer auf den enigma2 Receivern. Derzeit geht es halt nicht mehr, wenn, dann müßte man mit "Dev" von BS Kontakt aufnehmen um es wieder einzuführen, der entscheidet ob ja oder nein.

**Comment by halidri** [comment]
Mit V2 von BS kommt diese Funktion wieder, also so um 2021 wahrscheinlich, kann also geschlossen werden.
