### ISSUE TITLE
Updater

### ISSUE THREAD

**Issue by ghost** [StoneOffStones/plugin.video.xstream#42]
Hi,

Der Updater wird wie es aussieht ja bei JEDER Menüclick ausgeführt. Ist das nicht etwas unnötig? Können wir da nicht nen anderen Einsteigspunkt nehmen? Oder wenigsten nen Instance-Variable setzen oder ähnliches? So das, die Update-Funktion nur 1x pro xStream start ausgeführt wird oder ähnliches.

**Comment by Ston3s** [comment]
Genau das selbe ist mir ebenfalls heute Abend aufgefallen. Fände es auch schöner wenn es nur bei öffnen den Addons passieren könnte.
Bringt einen ansonsten etwas durcheinander dieses ewige geupdatete...

**Comment by sraedler** [comment]
Ich kenne mich mit Instance-Variablen nicht aus, aber kannst du natürlich gerne einfügen!

Edit: Hab ein bisschen gelesen und das Problem ist, dass es nicht Objektorientiert programmiert ist, das heißt wir haben keine Klassen und dadurch kein self. Daher gibt es kein self -> keine Instance Variable. Oder irre ich mich?

**Comment by ghost** [comment]
Ich auch nicht :)

Aber ich denke schon das sowas möglich sein wird. Man müsste sich ggf. mal ganz komplexe/große Addons angucken. Irgend wie muss sowas ja möglich sein.

**Comment by sraedler** [comment]
ja, aber die großen sind fast alle mit klassen und self

**Comment by ghost** [comment]
Naja ne notlösung wäre etwas wie ne. "var.json" oder ähnliches. Sprich ne "Datenbanke" für Variablen. Sicher nicht cool aber für sowas die einzige Möglichkeit, wenn wir keine Insance haben die, die ganze Zeit offen ist.

**Comment by sraedler** [comment]
ja, man könnte in die lastcommit datei von nightly auch ein timestamp reinschreiben, aber das ist alles nur so gebastel.

**Comment by Lynx187** [comment]
Objectorientierung ist vorhanden nur nicht überall so stark ausgeprägt. Wenn mans genau nimmt ist die bei Python ja per se vorhanden ;-). 
Das Problem liegt darin dass man bei einem Kodi Addon, wie Viper schon sagte, keine Instanz hat die permananet existiert und somit generell keine Persistenz, es sei denn man  übergibt etwas als Parameter, nutzt eine Datei, DB oder einen parallelen Prozess/Service von dem man Daten aus vorherigen Durchläufen erhält.

Aber wie ich schon mal gesagt habe, man könnte den Aufruf des Updaters auch dorthin verschieben wo das Hauptmenu erzeugt wird ,dann wird es wenigstens nicht ständig abgefragt.

**Comment by sraedler** [comment]
ja denk das mit dem Hauptmenü ist die richtigere Lösung!

werd ich morgen umstellen

**Comment by sraedler** [comment]
so, sollte nun nicht mehr so oft aufgerufen werden
