### ISSUE TITLE
KinoKister: KinoKiste stört Globale Suche

### ISSUE THREAD

**Issue by ghost** [StoneOffStones/plugin.video.xstream#44]
Da ich grade dabei war meine Addons (+ Vorlage) zu fixen ist mir aufgefallen das KKiste irgend wie auch die Globale Suche stört.
1. Sache die mich dabei störten:
- Es erscheint auch ne Meldung vom Plugin in der Globalen Suchen => das sollte vermieden werden
- Das Addon prüft bei jeden Einträg den er Erstellt ob es eine Serie ist (ist das nötig kann man das ggf. anders lösten?

Was davon die Globale Suche behindert weiß ich noch nicht. NUr da ich die nächsten Tage nicht wirklich Zeit haben wollte ich das Issus mal erstellen.

**Comment by Lynx187** [comment]
ja weiss ich glaube bereits, und nein geht nicht anders da es vorher keinen anhaltspunkt gibt ob es eine serie ist oder nicht

**Comment by Kukolorus** [comment]
Also ich habe gestern bei der globalen suche gemerkt, dass nur bei den Kinox.to filmen die Quelle, also Kinox.to, angezeigt wird. 

Ich glaube nicht das das seine Richtigkeit hat..

**Comment by ghost** [comment]
Stimmt das ist nicht korrekt. Ist Lynx auch schon bekannt und hat er wohl auch schon gefixt. Siehe:

https://github.com/StoneOffStones/plugin.video.xstream/issues/39

Wird vermutlich imt nächsten Sync von ihm drin sein (vermute ich mal)

**Comment by Ston3s** [comment]
Zusammenfassend:
1. Problem in der Beschreibung geht laut Lynx187 nicht anders zu lösen.
2. Nächstes aufgeführtes Problem ist anscheinend schon gefixt

Issue noch nötig???

**Comment by Lynx187** [comment]
1. korrekt
2. habe nochmal nachgeschaut konnte bei mir aber keine Störung feststellen

**Comment by Ston3s** [comment]
Zu machen?!

**Comment by ghost** [comment]
Jop ist auch keine Störung. War mein Fail. Kann also zu.
