### ISSUE TITLE
Kann nightly nicht starten

### ISSUE THREAD

**Issue by francescosoft** [StoneOffStones/plugin.video.xstream#45]
Hallo,

Ich habe mal die nightly versucht zu installieren auf Openelec.
Leider Startet das plugin dann nicht mehr.
`File "/storage/.kodi/addons/plugin.video.xstream-nightly/xstream.py", line 16, in run
                                                updateManager.checkforupdates()
                                              File "/storage/.kodi/addons/plugin.video.xstream-nightly/resources/updateManager.py", line 53, in checkforupdates
                                                if getRemoteVersion(REMOTE_VERSION_FILE_MASTER) > getLocalVersion():
                                              File "/storage/.kodi/addons/plugin.video.xstream-nightly/resources/updateManager.py", line 66, in getRemoteVersion
                                                version = V(ET.fromstring(xml).attrib['version'])
                                              File "/home/stephan/projects/openelec-6.0/build.OpenELEC-WeTek_Play.arm-6.0.3/Python-2.7.3/.install_pkg/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
                                              File "/home/stephan/projects/openelec-6.0/build.OpenELEC-WeTek_Play.arm-6.0.3/Python-2.7.3/.install_pkg/usr/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed
                                              File "/home/stephan/projects/openelec-6.0/build.OpenELEC-WeTek_Play.arm-6.0.3/Python-2.7.3/.install_pkg/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
                                            ParseError: mismatched tag: line 1, column 419
`

Kann mir da Jemand weiterhelfen ?

**Comment by sraedler** [comment]
geh mal in die Einstellungen und deaktiviere das Auto-Update

**Comment by francescosoft** [comment]
Super :) hat funktioniert. 

Danke :)

**Comment by ghost** [comment]
Wenn ich den StackTrace richtig lese ensteht der Fehler wie folgt:
- Update wird geprüft (xstream.py => Zeile 16)
- Updater prüft ob ein Update vorliegt (updateManager.py => Zeile 53) => daher scheint der Upater auf Stable zu stehen
- XML from Branche wird gelesen
- Fehler beim Ermitteln der Version => Zeile 66

Jetzt ist die Frage. Konnte die XML nicht gelesen werden? War der Inhalt leer? Evtl. Kodierungproblem?

Ich glaube wir sollten das Issus offen halten. Und ggf. mal prüfen was hier passiert. Weil dann müssten wir evlt. den Try Catch drum bauen. Auf Leeren String prüfen usw.

Weil das mal Probleme entstehen (Datei ändert sich, Branch ist evtl. weg, what ever). Darf die Update-Prüfung nicht zu einem Fehler bzw. zum nicht Starten des Addons führen (Log-Einträge beim Fehler wären ja ok).

**Comment by francescosoft** [comment]
habe jetzt nochmals von off auf nightly gestellt, damit funktioniert es auch.
Ich habe wohl verpasst von Stable auf nightly um zu stellen.
Danke fur die Hilfe.

**Comment by ghost** [comment]
Ja weil bei nightly die Version nicht geprüft wird (was der Grund des Fehlers ist). Wie gessagt ich behalte das Issus trotzdem mal offen. Um den Fehler noch etwas auf den Grund zu gehen.

Du könntest sogar etwas helfen falls du möchst:
- Stell mal den Updater wieder auf "Stable"
- füge mal unter Zeile 66 folgende Zeile ein:

`logger.info(xml)`

Das das ganze quasi so aussieht:

```
def getRemoteVersion(REMOTE_VERSION_URL):
    xml = urllib.urlopen(REMOTE_VERSION_URL).read()
    logger.info(xml)
    version = V(ET.fromstring(xml).attrib['version'])
    logger.info("xStream Remoteversion: " + version.vstring)
    return version
```

Und dann poste mal bitte die Log dazu. Mich würde mal interessieren wie der Variablen-Inhalt aussieht.

**Comment by francescosoft** [comment]
Sorry fuer die spaete Antwort, hier mal der log Auszug:
`21:18:53 T:2422207552  NOTICE: Thread BackgroundLoader start, auto delete: false
21:19:07 T:2422207552  NOTICE: Thread LanguageInvoker start, auto delete: false
21:19:07 T:2422207552  NOTICE: -->Python Interpreter Initialized<--
21:19:07 T:2422207552  NOTICE: *---- Running xStream, version 2.1.16~beta4 ----*
21:19:07 T:2422207552  NOTICE:  [xStream] xStream checkforupdates
21:19:07 T:2422207552  NOTICE:  [xStream] <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd"> <html><head> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"> <title>ERROR: The requested URL could not be retrieved</title> <style type="text/css"></style> </head><body id=ERR_UNSUP_REQ> <div id="titles"> <h1>ERROR</h1> <h2>The requested URL could not be retrieved</h2> </div> <hr>  <div id="content"> <p>The following error was encountered while trying to retrieve the URL: <a href="https://raw.githubusercontent.com/Lynx187/plugin.video.xstream/master/addon.xml">https://raw.githubusercontent.com/Lynx187/plugin.video.xstream/master/addon.xml</a></p>  <blockquote id="error"> <p><b>Unsupported Request Method and Protocol</b></p> </blockquote>  <p>Squid does not support all request methods for all access protocols. For example, you can not POST a Gopher request.</p>  <p>Your cache administrator is <a href="mailto:webmaster">webmaster</a>.</p> <br> </div>  <hr> <div id="footer"> <p>Generated Tue, 29 Mar 2016 21:09:48 GMT by foproxy.tzudomain.local (squid/2.7.STABLE9)</p>  </div> </body></html>
21:19:07 T:2422207552  NOTICE: Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.xstream-nightly/default.py", line 28, in <module>
                                                run()
                                              File "/storage/.kodi/addons/plugin.video.xstream-nightly/xstream.py", line 16, in run
                                                updateManager.checkforupdates()
                                              File "/storage/.kodi/addons/plugin.video.xstream-nightly/resources/updateManager.py", line 53, in checkforupdates
                                                if getRemoteVersion(REMOTE_VERSION_FILE_MASTER) > getLocalVersion():
                                              File "/storage/.kodi/addons/plugin.video.xstream-nightly/resources/updateManager.py", line 67, in getRemoteVersion
                                                version = V(ET.fromstring(xml).attrib['version'])
                                              File "/home/stephan/projects/openelec-6.0/build.OpenELEC-WeTek_Play.arm-6.0.3/Python-2.7.3/.install_pkg/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
                                              File "/home/stephan/projects/openelec-6.0/build.OpenELEC-WeTek_Play.arm-6.0.3/Python-2.7.3/.install_pkg/usr/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed
                                              File "/home/stephan/projects/openelec-6.0/build.OpenELEC-WeTek_Play.arm-6.0.3/Python-2.7.3/.install_pkg/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
                                            ParseError: mismatched tag: line 1, column 419
`
Hmm sieht so aus als ob mein Proxy dazwischen funkt.
Ich probiere es mal ohne Proxy.

**Comment by francescosoft** [comment]
Also ohne Proxy laeuft es.
`21:26:31 T:2545939520  NOTICE:     [xStream] xStream checkforupdates
21:26:32 T:2545939520  NOTICE:  [xStream] <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                                            <addon id="plugin.video.xstream"
                                                name="xStream"
                                                version="2.1.15"
                                                provider-name="Lynx187 (originator: murphy, MaxMustermann)">
                                              <requires>
                                                <import addon="xbmc.python"                 version="2.1.0"/>
                                                <import addon="script.module.urlresolver"   version="2.9.0"/>
                                                <import addon="script.module.metahandler"   version="1.0.0"/>
                                                <import addon="script.module.mechanize"     version="0.2.6"/>
                                              </requires>
                                              <extension point="xbmc.python.pluginsource" library="default.py">
                                                <provides>video</provides>
                                              </extension>
                                              <extension point="xbmc.addon.metadata">
                                                <summary lang="de">xStream</summary>
                                                <description lang="de">xStream ist ein Addon, welches mit eigenen Plugins erweitert werden kann. Hiermit kann man Filme, Serien, etc. per Stream anschauen.[CR]Support: http://xstream-addon.square7.ch </description>
                                                <summary lang="en">xStream</summary>
                                                <description lang="en">Addon to watch streams from various film an series sites.[CR]Support: http://xstream-addon.square7.ch</description>
                                                <forum>http://xstream-addon.square7.ch</forum>
                                                <website>http://xstream-addon.square7.ch</website>
                                                <platform>all</platform>
                                              </extension>
                                            </addon>
21:26:32 T:2545939520  NOTICE:  [xStream] xStream Remoteversion: 2.1.15
21:26:32 T:2545939520  NOTICE:  [xStream] xStream Localversion: 2.1.16~beta4`
Scheint so das mein Proxy das Problem verursacht.

**Comment by ghost** [comment]
Aber super. Da haben wir doch nen schönes Beispiel. Also werden wir uns dort noch nen Fehlerprüfung einbauen müssen. Danke für die Hilfe.

**Comment by ghost** [comment]
Jetzt sollte xStream wenigstens starten. Im Log wird dann Version als "Unbekannt" gekennzeichnet.

Ich hoffe die Änderungen sind so ok.
