### ISSUE TITLE
Set correct views for Site-Plugins

### ISSUE THREAD

**Issue by Ston3s** [StoneOffStones/plugin.video.xstream#46]
Hallo mir ist bei HDfilme.tv (bisher) aufgefallen das nicht die richtigen Viewtypes zugeordnet werden.
Wenn ich in die Ordner "Neu hinzugefügt" oder "A-Z" gehe, egal ob in Serien oder Filme, wird nicht der eingestellte Viehtype angezeigt. Es wird lediglich der letzte eingestellte View wiedergegeben.
Jedoch wird wenn ich dann von besagten Ordnern zurück in die Hauptordner Filme oder Serien komme dar eingestellte View für diese Ordner angezeigt.
Irgendwas haut da nicht ganz hin.

Vermute es liegt an den Zeilen für showEntries ...
`oGui.setView('tvshows' if isTvshow else 'movies')`

Ich bitte an der Stelle alle den etwas ähnliches auffällt in diesem Issue zu posten.
Bedanke mich im vorraus für jegliche Unterstützung!

**Comment by ghost** [comment]
Wird morgen direkt geprüft :)

Die Zeile besagt btw das der viewtyp auf Serie gesetzt wird wenn es ne Serie ist. Sonst auf Film.

**Comment by ghost** [comment]
Kann das mal noch jemand bitte prüfen. Ich finde da keinen Fehler im SitePlugin.

Beim erstellen der Liste wird korrekt "movies" für Filme gesetzt und "tvshows" für serien. Und bei der Episoden "episodes".

Das einzige worüber man bei HDFilme streiten könnte ist ob man "tvshows" nimmt. Weil es defacto eigentlich immer Staffeln sind (da es keine wirkliche Auflistung der Serien gibt).

Aber vom prinzip sollte das setzen korrekt sein.

**Comment by halidri** [comment]
Stimme dir zu, bis auf Staffeln wird alles korrekt angezeigt, als forced view für Staffel hab ich middle list (Aeon MQ6mod) eingestellt, angezeigt wird halt die rightlist.
Achja, möchte nicht schon wieder ein neues Issue aufmachen, fanarts vom metahandler geht bei HDFilme auch nicht?

**Comment by sraedler** [comment]
Kann mir einer erklären was das für unterschied macht?

**Comment by ghost** [comment]
Ich gehe jetzt mal vom Standart-Skin aus:
- Beim Filmem sieht Rechts ein Bild + Beschreibung
- Bei Serien zeigt er das Bild oben und dadrunter die Beschreibung + Infos (Anzahl Staffeln)
- Bei Episoden quasi das gleiche wie bei Serien nur die Infos sind anders

**Comment by sraedler** [comment]
kannst du mir mal Screenshots machen?

Sehe es nämlich nicht mal nach deiner detaillierten Beschreibung.

**Comment by halidri** [comment]
Screenshot HDFilme
http://www.bilder-upload.eu/show.php?file=d061e3-1459363159.png
Screenshot KinoX
http://www.bilder-upload.eu/show.php?file=aef556-1459363180.png

edit: 
also bei HDFilme fehlt das fanart

**Comment by Kukolorus** [comment]
Stimmt, da muss ich dir recht geben.

Ist denn dafür schon ein Fix gefunden worden?

**Comment by ghost** [comment]
Ich sehe nicht wirklich ein Fehler :'(

**Comment by ghost** [comment]
Ich habe das jetzt echt mehrfach geprüft. showEntries ist die Funktion die die Liste erstellt (z.b Ergebniss der Suche oder allgemein die Auflistung der Filme/Serien).

Besage Zeile von StoneOffStones setzt halt je nachdem auf welchen Link die Liste basiert ob es ein Filme oder ne Serien Auflistung ist. Auch wird für jeden Listeneintrag der Medien-Typ gesetzt.

Ich habe echt keine Ahnung was ich noch tun soll.

Prüft das mal bitte mit dem Basis-Skin (das ist besser für die Allgemeinheit)

**Comment by Ston3s** [comment]
Werd ich am Wochenende mit dem Standard Skin ausprobieren. Welche Viewtypes (Nunmern) habt ihr da gesetzt?

**Comment by Lynx187** [comment]
Seriename + "Staffel xx" ist ein ungüstiger Suchbegriff nur der Serienname ist wesentlich besser.

Evtl. sind auch noch fehlerhafte Einträge in der metahandlerDB, z.B. Serien wurden fälschlicherwesie als movie deklariert und als solche gesucht --> kein Ergebnis --> dummy Eintrag --> einzeln überschreiben/einträge in db manuell löschen/ gesamte db löschen und neu aufbauen (nicht so gut)

**Comment by ghost** [comment]
Das setzen der Views sollte soweit aber korrekt sein oder?

Die Frage ist wollte sollte man mit diesen Einträgen umgehen? MediaTyp evtl. auf "season" setzen statt auf "tvshow"? Weil defaco repesentiert der Eintrag ja eher ne Staffel als ne Serie ansich. Genau das selbe gilt für die ganze view. Auf "tvshows" lassen oder lieber auf "seasons" setzen?

Könnte ich bei Serien das dann wie folgt machen?
- setTVShowTitle => hier den richtigen Titel also ohne Staffel x => "Seriename"
- setTitle => dann aber schon so wie auf der Seite => "Seriename Staffel xx"
- setEpisode => auf die jeweils geparste Staffel setzen? => "xx"

**Comment by Lynx187** [comment]
Das wäre richtiger aber beim metahandler ist zum laden der Seasoninfo die imdbID Pflicht und der Seaonview zeigt weniger Infos in der Regel.
Ansonten passt das nur  die Staffelnummer sollte man schon per setSeason setzen und nicht Episode.
Aber habe da eben gerade ohnehinwas dran gemacht nur an setTVShowTitle  habe ich gar nicht mehr gedacht ^^

**Comment by ghost** [comment]
ups ja klar mein Fehler beim tippen ^^

Aber habe gesehen du hast gestern ne commit für HDFilme.TV gemacht. Werde denke davon mal paar Änderungen hier einfließen lassen.
- list closing hatte ich ja schon gefixt
- genau wie regex für var ermittelung

was ich aber einbauen werde ist die behandlung der Hoster und auch das setzen der view unterhalb der if beim schließen der Liste (könnte sonst ja ggf. Problem bei der Suche machen, das sollte ich entsprechen auch bei den anderen Plugins optimieren). Achja und "movie-cinemas" könnte ich natürlich auf entfernen.

@StoneOffStones 

Könntest du bitte beim merge von Lynxs Änderungen den HDFilme.tv commit nicht mit nehmen?

**Comment by Lynx187** [comment]
Wenn du es irgendwann wieder in den main branch mergen willst solltest du so viel wie möglich übernehmen (nur das was funktioniert natürlich) umso leichter geht das nachschauen, weil mans schon kennt bzw. weniger abweichung sind.

**Comment by ghost** [comment]
Meine frage würde jetzt etwas abdrifen daher mach ich mal nen neuen Issues auf

**Comment by Ston3s** [comment]
Soll ich dann die Merge welcher HDFilme angeht raus lassen oder doch mitnehmen?

**Comment by ghost** [comment]
Nimm bitte mal nicht mit. Grade die Sachen die wir eingeführt habe (Ordnerstruktur mit Genre usw.), Sortierung (die atm auf der Seite zwar verbuggt ist), angepasster UserAgent (der anscheinend nicht mehr nötigt ist).

Und ich bin der Meinung das bei Lynx187 Version nen Fehler in der Log verursachen würde wenn die Suche leer ist.

Aber egal nimm mal nicht an ^^

**Comment by Ston3s** [comment]
Folgende Commits lasse ich dann weg:

https://github.com/Lynx187/plugin.video.xstream/commit/faa9d496146088ee661b2842322b1363e0348db1

https://github.com/Lynx187/plugin.video.xstream/commit/9038afc5943ab762a887b2c804c6d1a8161a3701

**Comment by Ston3s** [comment]
Das ding ist er zeigt mir einige Konflikte auf.

**Conflicts:
    resources/lib/bs_finalizer.py
    sites/filmpalast_to.py
    sites/hdfilme_tv.py**

Wenn ich jetzt die hdfilme_tv.py weglasse bleiben immer noch die anderen Dateien.
Soll ich diese auch nicht weg lassen oder lieber mergen und im Nachhinein säubern?!

**Comment by ghost** [comment]
bs_finalizer.py kannst 1:1 von Lynx187 übernehmen
filmpalast_to.py auch (das einzige was danach noch ändern könntest wäre ggf. die namenes anpassen die du mal gemacht hast. Sonst ist die Version besser als unsere)

hdfilme_tv.py kannst wie gesagt weglassen. Ich mache "unsere" Version grade fertig.

**Comment by ghost** [comment]
So habe ne neue Version eingebaut die Lynx's Änderungen berücksichtigt:

https://github.com/StoneOffStones/plugin.video.xstream/blob/nightly/sites/hdfilme_tv.py

@Lynx187 
Ich habe es oben schon mal geschrieben. Aber habe es grade noch mal getest. Wenn man in der "showSearch" die Liste nicht schließt wird bei ner Suche ohne Ergebniss nen Fehler in der Log hinterlegt das die Liste nicht abgeschlossen wird. Und beim User passierte garnichst. Schließt man die Liste landet der User in einer Leeren Liste (was ja irgendwo auch korrekt ist)

Ich glaube das Problem sollte bei Filmpalast auch drin sein. Aber da deine Version im Forke besser ist fasse ich da mal nichts an ^^

@all
Bitte mal testen ob die Sache mit der View jetzt besser ist (falls ja Issus bitte schließen) 

PS: aktuell hat die Seite grade Problem mit den Streams von Filmen (daher bitte nur das Plugin selbst testen)

**Comment by Ston3s** [comment]
Musste jetzt doch alles übernehmen, sonst hätte der Merge nicht sauber funktioniert.
Aber keine Angst, habe nachträglich alle Dateien wieder sauber eingespielt

https://github.com/StoneOffStones/plugin.video.xstream/commit/49297202854bb11dbcd5dd50f1258645959827ba

**Comment by ghost** [comment]
Keine ding ist so korrekt. Habe eben noch die 0 am Anfang der Staffeln entfernt.

Gibt btw. 4 Serien auf der Seite die "stafffel" im Namen haben. Diese Serien funktionieren nicht:

http://hdfilme.tv/movie/search?key=stafffel

Aber sonst funktioniert die Version aktuell sehr gut mit dem Metahandler.

@Lynx187 
Könnte/sollte man **setTVShowTitle** auch beim Eintrag der Folge setzen? So das ggf. ne Info für die Folge ermittelt werden kann? Weil mit "Folge 1" wird vermutlich nichts gefunden oder?

**Comment by Ston3s** [comment]
Kann ich auch bestätigen, meine in der Beschreibung definierten Probleme sind jetzt nicht mehr in der Art vorhanden!
👍🏼

**Comment by Lynx187** [comment]
Bei der Episode wird nicht über den titel gesucht. Episode und Season muss gesetzt sein Typ sollte auf episode stehen und die imdbID sollte sich schon automatisch in den Parametern tummeln dann sollten die Infos gefunden werden.

**Comment by ghost** [comment]
Ok dann passt es ja. Ich habe es trotzdem mal gesetzt. Sieht irgendwie besser aus wenn beim auf "Info" klickt ^^

@Lynx187 
Btw. gibt es irgend wie ne Möglichkeit dem Player nen Namen mit zu geben denn er benutzt? Aktuell benutzt er ja irgend wie den Title vom Element. Und das manchmal etwas unpassend.

@StoneOffStones 
Wenn damit alles durch ist mach das issus mal zu. Würde gern bissel Ordnung hier rein bekommen :)

**Comment by Ston3s** [comment]
Von meiner Seite ja sowieso schon bereits einige Posts zuvor ;)
Super Arbeit, Danke!
