### ISSUE TITLE
Automatische Hosterwahl

### ISSUE THREAD

**Issue by halidri** [StoneOffStones/plugin.video.xstream#47]
Bei mir funktioniert die automatische Hosterwahl seit Umstieg auf die nightly Version nicht mehr.
System ist aktuelles OE 7.0 und LibreELEC 6.9.00.2. Egal welcher Skin.
*zeige Hosterliste als Verzeichnis ist deaktiviert
*Hostliste prüfen... ist deaktiviert

**Comment by Kukolorus** [comment]
Mhm, den Grund kenne ich nicht.

Bedenke bitte das die Nightly einen Experimentellen Zustand hat. Nichts was in der Nightly ist muss zwingend funktionieren, sie ist lediglich zum Testen da.

**Comment by halidri** [comment]
Schon klar, dachte aber, funktionierende Grundfunktionen würden auch in der nightly laufen.

**Comment by ghost** [comment]
Sollen sie auch :)

Hast evtl nen log?

**Comment by halidri** [comment]
Klar,
Uiuiui, da hab ich ja viele Fehler...
http://pastebin.com/JRTqy9LG

**Comment by ghost** [comment]
Das hier ist der wichtige Teil:

> 22:08:54 T:2894046112 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.xstream/?site=bs_to&function=showHosters&title=1+-+Reboot+in+Brooklyn&seriesID=326&episode=1&thumb=http%3A%2F%2Fthetvdb.com%2Fbanners%2Fepisodes%2F248741%2F4099506.jpg&Title=2+Broke+Girls&Season=1&TVShowTitle=2+Broke+Girls&mediaType=episode&EpisodeNr=1&season=1&MovieTitle=1+-+Reboot+in+Brooklyn&imdbID=tt1845307&playMode=play

Woran das genau liegt kann ich nur leider nicht sagen. Bzw. prüfen da ich kein ähnliches System laufen habe. Aber an der Nightly wurde eigentlich nichts tiefgreifendes in der Richtung geändert :/

_EDIT_

Habe mal nach **"CreateLoader - unsupported protocol(plugin) in " xstream** gegoogelt. Und finde dazu auch Forenbeiträge (was leider down ist).

Aber könntest du mal prüfen den Metahändler zu deaktivieren? (Der wirft ja auch einige Fehler ein paar Zeilen zuvor)

**Comment by halidri** [comment]
Komisch ist nur das es früher ging! Aber ich werde mal das System neu installieren, bewirkt meist wahre Wunder.

**Comment by halidri** [comment]
Hab gerade noch die 2.15 Version mit KinoX getestet, da funktionierts, also muß sich doch was geändert haben.

**Comment by sraedler** [comment]
@halidri kannst du mal deine settings.xml aus dem userdata ordner schicken?

dann simulier ich das bei mir und versuch den fehler zu finden.

@Viper2k4 [Google Cache](http://webcache.googleusercontent.com/search?q=cache:9r_14kvw-SoJ:xstream-addon.square7.ch/archive/index.php%3Fthread-509.html+&cd=1&hl=de&ct=clnk&gl=de)

Der kleine Pfeil neben dem googlesuche link hilft bei sowas gerne :)

**Comment by halidri** [comment]
http://pastebin.com/WsAL71Rt

**Comment by sraedler** [comment]
@halidri sollte jetzt wieder geben, war ein Rename bug.

**Comment by halidri** [comment]
Super! metahandler "aus" hatte ich jetzt erst getestet, daran lags auch nicht.
Jetzt geht es wieder richtig, danke!

**Comment by sraedler** [comment]
Geht auch mit metahandler, war wie gesagt an einer anderen stelle das problem
