### ISSUE TITLE
Anpassung des Logger verhaltens

### ISSUE THREAD

**Issue by seberoth** [StoneOffStones/plugin.video.xstream#48]
Meiner meinung nach, sollte der Logger in der Beta/Nightly ein von Kodi unabhängiges Log anlegen.
Mach ich bei mir lokal auch so, da mir das Kodi.log beim debuggen zu schnell unübersichtlich wird.

Steuern tue ich das ganze über einen entsprechenden Eintrag in "common.py".

Was haltet ihr davon? Soll es eine lokale änderung bleiben oder kann es ins Repo?

**Comment by ghost** [comment]
Also generell würde ich das nicht mit rein nehmen. Da es vermutich 98% der User nicht benutzen werden und sie dann ein unverwaltet (wird nicht gelöscht usw.) Log-Datei haben.

Aber guck mal in die Logger.py dort gibt es nen auskommentierte Zeile:

`# (config.getSetting("debug")=="true")`

Was ich mir vorstellen kann wäre in der Beta/Nightly ne Einstellungen "Debug" auf die man dann ja reagieren kann. Sprich wenn Debug gesetzt ist, schreibe ne Seperate Datei usw.

**Comment by sraedler** [comment]
Ich bin auch sehr dafür, dass wir eine Setting dafür einbauen und in den SitePlugins logger für ALLES einbauen, das erleichtert so viel!

**Comment by ghost** [comment]
Logger für alles? Ich habe es eher vermieder unnötig logger in den SitePlugins zu haben. Ich würde nur bei Fehler oder ähnliches loggen.

 seberoth wollte ja nicht das Loggin erweitern. Er wollte nur das xStream-Loggin umleiten um alles gebündelt zu haben.

**Comment by sraedler** [comment]
Ich würde es schon gerne etwas erweitern, aber mit Levels. Level High wäre alles mit xml welche in einen Logger Ordner kopiert werden, plus normales Logging. Level normal, nur die Logging datei, Level off, nur Kodi.log logging

**Comment by Lynx187** [comment]
Also ich lasse mein log im Betrachter ,falls wiklich mal zu viel im log stehen sollte, einfach nach den Ausgaben von xStream filtern.

Das Setting ist übrigens schon uralt k.A,. ob Kodi damals noch keine log levels kannte.
Zusätzlich ausgaben zu aktivieren kann manchmal schon sinnoll sein, könnte man aber auch über die loglevels regeln.
Permamanet in eine extra Datei zu loggen eher nicht so toll, in einigen Fällen muss man eben auch wissen was parallel in Kodi passiert.

**Comment by Ston3s** [comment]
Noch interessant?!
