### ISSUE TITLE
Check stream is online

### ISSUE THREAD

**Issue by sraedler** [StoneOffStones/plugin.video.xstream#49]
Hab eine neue Idee um xStream zu erweitern.

Jeder kennt es, man will einen Stream starten, aber die ersten 5 Streams sind down und nicht startbar. Hierfür würde ich gern eine Prüfung einführen mit welcher dies entfällt.

Hab es auch schon zusammengebastelt und ihr könnt es testen. (Jedoch ohne Setting, sondern nur als Permanentlösung)

Zum testen hab ich ddl.me genutzt.

Hierzu in der ddl_me.py in Zeile 10 `threading` einfügen (Wegen der Performance)

Anschließend Zeile 475 bis 493 durch check_online in folgendem Gist ersetzen. Alternativ könnt ihr auch die ddl_me.py durch die auch im Gist enthaltene ersetzen.

https://gist.github.com/sraedler/9e8d06dca56cb72af8e29e54915f0cc5

Nun könnt ihr ddl.me ganz normal nutzen und ihr bekommt nur links die auch gehen.

Bevor das kommt, ja ich weiß, dass man dann jedes mal 8 Sekunden warten muss, das liegt an gewissen hostern, aber deshalb wäre es als Setting optional sehr nett

P.s. Bedenkt beim Testen, dass mit dem "alten" urlresolver hoster wie videowee und novamov nicht funktionieren!

**Comment by ghost** [comment]
Hat xStream nicht genau dafür "Hoster automatisch wählen"?

Was ich mir nur immer mal gewünscht habe wäre ne einfach Bedienung der Prio. Denn "Hoster automatisch wählen" ist eigentlich genau das, was der normale Anwender sich wünscht. "Problem" ist nur das die Funktion einfach die Liste abarbeitet.

Sprich => Versuche zuerster Hoster x dann y dann z (gibt zwar etwas in der Art. Nur empfand ich die Bedienung nicht intuitiv. 3 Favoriten die per Dropbox ausgewählt werden z.b wären schöner)

Weil Stumpf alle Hoster vorher Anfragen finde ich etwas rapiat.

just my 2 cent

**Comment by sraedler** [comment]
ja, da hast du eigentlich recht, daran hab ich noch gar nicht gedacht.

Aber wie du auch schon sagst, das war auch für mich der Grund es immer selber zu versuchen, da die Prioritäten umstellen so nervig ist.

**Comment by ghost** [comment]
Wir können ja über folgendes nachdenken:

Settings (ggf. ne neue Gruppe oder so?)

Fav Hoster 1 => Dropdownbox
Fav Hoster 2 => Dropdownbox
Fav Hoster 2 => Dropdownbox

Die Dropdown auswahl wird gefüllt mit den Hostern die der jeweilige URLResolver beherscht (falls das geht).

**Comment by sraedler** [comment]
Ja, das wäre eine Idee!

Aber was anderes, Priorität ist bei allen Hostern auf 100.
Und je niedriger die Priorität, desto früher wird es genutzt, dachte es ist andersherum.

Das heißt eigentlich wird die Fav Hoster Dropdownbox Erweiterung nicht benötigt oder seh ich das falsch?

**Comment by ghost** [comment]
Ja das Problem ist halt das, das mit der Prio keinen wirklich einleuchtet. Ich kenne nur leute die sagen "Ich nehme immer Steamcloud" usw. 

Es lässt sich halt blöd erklären das man an den prios drehen muss.

**Comment by seberoth** [comment]
Soweit ich mich errinere, bezieht sich dir Prio beim resolver darauf, welcher genutzt werden soll wenn für einen Link mehrere verfügbar sind (z.B. Streamcloud, Premiumize.me,...)

**Comment by ghost** [comment]
Genau darum geht es ja. Die Funktion "Hoster automatisch wählen" gehalt die Liste durch. Was per default alle gleich behandelt (was ja auch ok ist).

Aber ich habe die Funktion bewusst aus weil Teilweise andere Hoster früher dran sind (die zwar funktionieren aber z.b langsam usw.). Daher müsste man jetzt an den Prios werkeln bis man seine 3/4 eingestellt hat.

Aber wenn man eben diese Einstelung für den Anwender einfacher zugänglich macht. Wäre die Funktion "Hoster automatisch wählen" perfekt.

**Comment by sraedler** [comment]
Ja, da hast du irgendwie recht...

Jetzt müsste nur noch ein dropdown in den Kodi settings möglich sein, dann wäre das perfekt.

**Comment by halidri** [comment]
Ich hab die Prio zB bei streamcloud auf 1 flashx auf 2 vivo auf 3 usw..
so startet immer streamcloud, wenn nicht verfügbar, flashx usw..
Das funktioniert super.

**Comment by sraedler** [comment]
Ja hab grad auch versucht, ein dropdown einzubauen, das macht es aber nicht einfacher.

Eine Überlegung wäre ein kurzer hinweis, ob Prio 1 oder Prio 10000 zuerst kommt, aber das ist eigentlich nicht unsere Aufgabe...

**Comment by seberoth** [comment]
Ein bisschen OT: Kann es sein, das die "cHosterGui__getPriorities" etwas fehlerhaft ist?
Soweit ich das sehe, wird pro hoster immer nur die prio des letzten dafür möglichen resolvers verwendet. Und ich glaube nicht, das `source._HostedMediaFile__resolvers` bereits nach prio sortiert ist

Müsste da nicht noch sowas wie `if resolver.priority < priority: priority = resolver.priority` rein?

**Comment by ghost** [comment]
Naja muss ja keine Dropdown sein. Quasi sowas wie der Auswahl für Off/Beta/Nightly.

Welches Steuerelement man nimmt ist ja zweiranging. Mir geht es nur darum das der Anwender keine Prios drehen muss. Sondern nur die namen kennen muss. Und die einstellt.

**Comment by sraedler** [comment]
Ja, labelenum hab ich versucht, aber da müsste man dynamisch die namen der urlresolver bekommen, sonst ist das eine schlechte Lösung und Wartungsaufwand

**Comment by midorlo** [comment]
Semi-OT: In Beta und Nightly scheint mir "hoster automatisch wählen" nicht zu funktionieren (der user erhält trotz aktiviertem setting einen dialog um den hoster zu wählen). Ist das bekannt? Normal würde ich nix zum betazweig reporten aber der fix für die bs.to api ist im stable noch nicht angekommen :P

**Comment by sraedler** [comment]
@netzgeist falscher Issue! 
Ist schon gemacht, update auf nightly siehe #47

**Comment by midorlo** [comment]
Sehr sehr lebendiger code hier. Hatte gestern Abend erst die nightly probiert. Ich halte zurück, bugs die ich finde habt ihr eh gefunden und gefixt bevor ich das issue fertig hab :D

**Comment by halidri** [comment]
Beim simpleBS und beim anderen BS addon, konnte man, wenn ich mich nicht irre, auch seine bevorzugten hoster auswählen, aber hier ist es natürlich umfangreicher.
Vielleicht kann trotzdem wer was damit anfangen, keine Ahnung...
http://repo.skinquantum.de/nerdsrepo/kodi15/plugin.video.burningseries/plugin.video.burningseries-1.5.1.1.zip

**Comment by sraedler** [comment]
@Viper2k4 willst du etwas ändern oder so lassen?

**Comment by ghost** [comment]
Aktuell stehts nicht auf meiner Liste. Aber ich finde das man den Punkte ggf. notieren sollte. Aber direkt vor habe ich jetzt nichts :)

**Comment by sraedler** [comment]
Ok, dann schließ ich es mal, weil sonst haben wir tausende Issues die evtl. mal gemacht werden könnten ^^

**Comment by Lynx187** [comment]
Doch die Sources sind beim urlresolver bereits nach ihrer Prio sortiert. Bzw. waren sie das bis jetzt immer. Da man so ziehmlich alles über den urlresolver auflösen lässt wurde genau diese Einstellung auch für die Auswahltreihenfolge der Hoster in xStream genutzt. Denn warum 2 mal einstellen. Steht/ Stand auch in den FAQs wenn die einige nicht lesen --> RTFM
