### ISSUE TITLE
BS.to Random Feature

### ISSUE THREAD

**Issue by sraedler** [StoneOffStones/plugin.video.xstream#50]
Das Random Feature von bs.to ist eine schöne Sache und würde ich gerne integrieren. Ob über API oder parsing muss noch geklärt werden. Aber schätze es geht nicht über die API

**Comment by seberoth** [comment]
Nicht direkt über die API, aber man kann python ja einen zufälligen eintrag aus allen Serien ausgeben lassen...

**Comment by sraedler** [comment]
Würdest du dann mit der Einstellungsmöglichkeit wie auf bs.to machen oder ohne?

**Comment by sraedler** [comment]
Zwei Funktionen:
- egal was für eine Episode von egal welcher Serie
- Specifische Serie, Episode egal

Edit: ist ein bug drin -.-

**Comment by sraedler** [comment]
Jetzt sollte es testbar sein

**Comment by sraedler** [comment]
close?
hat es jemand getestet?

**Comment by seberoth** [comment]
Bei mir läuft es soweit. Das einzige was man vlt. noch ändern könnte, wäre das er bei "Alle Serien" nicht direkt die Episode anzeigt, sondern erst die Serie allgemein und in dem Ordner dann eine Episode. So könnte man die Serie direkt als Favourit speichern, falls sie einem gefällt.

Ist aber geschmackssache.

**Comment by Ston3s** [comment]
Fuchs...

**Comment by sraedler** [comment]
sollen wir quasi Random folge und random Serie daraus machen?

d.h.  das eine wählt man eine Serie und kriegt eine random folge und das andere zeigt eine random Serie mit Staffeln usw. an?

würde mir auch gut gefallen.

**Comment by sraedler** [comment]
Soll das noch umgesetzt werden?

**Comment by Ston3s** [comment]
Die Idee war in den Kommentaren darüber war doch sehr gut...

**Comment by Ston3s** [comment]
Müsste noch in "update-siteplugins" eingepflegt werden...
