### ISSUE TITLE
TMDB api key

### ISSUE THREAD

**Issue by halidri** [StoneOffStones/plugin.video.xstream#53]
Seit längere Zeit muß jedes addon, welchen tmdb nutzt, ihren eigen key verwenden, ist hier auch schon etwas in Planung? Derzeit spuckt ja metahandler immer fehler aus und man kann manuel meist nichts korrigieren.

Laut Eldorados

> They have shut down the api key that meta handlers was usingNow all addons need to get their own api key and pass it into meta handlers for it to work

**Comment by Ston3s** [comment]
Kam schon länger nichts Neues zum Thema und Commit ist auch vorhanden!
