### ISSUE TITLE
Wohin geht die Reise mit dem Forum?

### ISSUE THREAD

**Issue by Kukolorus** [StoneOffStones/plugin.video.xstream#54]
https://www.youtube.com/watch?v=NkWdFWSxAnY

Ich würde dieses YouTube Video mit in der Datei angeben (In dem FAQ). Dieses TuTo benutzt einen alten Stand unseres xStreams, das sieht man ganz einfach an den Kommentaren. Es wurde vom Ersteller ja auch schon geschrieben das ein Update Video kommt. 

Wenn ihr mal die Aufrufzahl anguckt, sind das schon einige und es gibt auch so manches Problem in den Kommentaren. 

Die Frage die ich mir hier gerade stelle, woher bekommen diese Leute denn eigentlich die neusten xStream Versionen? Abgesehen vom Auto-Update. Und woher kriegen die den Support? Sicherlich kann so manch einer in den Kommentaren helfen, jedoch sind ja **hier** die meisten Experten. 

Ich vermute mal ganz einfach das die meisten gar nichts von uns hier wissen und das wir hier fleißig weiter arbeiten... Woher sollen sie das auch wissen? Das Forum für den Support ist nicht mehr vorhanden, vorzeitig, jedoch wissen wir auch nicht wie lange. 

Worauf ich hinaus will ist, sollten wir vielleicht auf uns Aufmerksam machen? Bzw. Nun mal endlich sagen wo die ganze Reise hin geht? 

**Sollen wir auf uns und dem hier aufmerksam machen und GitHub als Ersatzforum benutzen, oder dieses hier :** https://rm.bg-entwicklung.de/projects/xstream?jump=welcome 

Oder ein ganz anderes? Ich meine nur das wir sonst eventuell in Vergessenheit geraten! Und die Personen die diese Videos machen wissen vllt. auch nichts von uns, und falls wir auf uns Aufmerksam machen, **wie**? 

Die Nachfrage nach dem Addon ist Definitv vorhanden!

Denn wie schon im anderen Post gesagt wurde, für das FAQ würden wir auch gerne ein Forum zum Support als Anlaufstelle verwenden.

_PS: Ich finde es aber auch nicht unbedingt korrekt das dieser Nutzer, der dieses Video erstellte, nicht mal auf unser damals noch existente Forum verwies..._

@Lynx187 Wann geht denn vorraussichtlich das Forum wieder? Oder dauert es noch lange? Ich will nicht hetzen aber wir sollten uns nun bald entscheiden, finde ich.

**Comment by Lynx187** [comment]
K.A. vllt Mittwoch

**Comment by Ston3s** [comment]
Oh also geht es wieder online?!
Bin aktuell noch davon ausgegangen das, dass Forum Geschichte ist. 
Öde war es der verzögerte Aprilscherz :)

**Comment by Lynx187** [comment]
Nein, sonst müsste ich erst wieder etwas anderes anmelden um das Repo vie Quelle zu installieren.

**Comment by llgreekboy** [comment]
@Lynx187 
Was hältst du davon wenn ich und mein Partner euch ein Forum spendiere? 
Mit alles was dein Herz begehrt? Keine Einschränkungen oder sonst was wie es bei den free Hoster der Fall ist 😉

**Comment by Ron801** [comment]
wo ist der haken?im leben gibt es nix umsonst bzw. gegenleistung

**Comment by llgreekboy** [comment]
Es gibt kein Haken... Ich bin von allen Leuten hier so überzeugt dass ich uns allen ein platz geben möchte wo wir uns alle wieder ohne Probleme austauschen können!

**Comment by Kukolorus** [comment]
Hm. Ich bin auch skeptisch, bitte versteh uns nicht falsch, aber wie oben schon von Rene gesagt, im leben gibt es nix umsonst xD.

Aber, wer bist denn du und "dein Partner" das ihr das macht?

**Comment by Ston3s** [comment]
Ist doch ein sehr nettes Angebot!
Vielleicht einige technische Fakten für die Skeptiker???

**Comment by Kukolorus** [comment]
Genau :D

**Comment by Lynx187** [comment]
So, es sieht so aus als hätten einfach nur "viele" Registrierungen + mehrfachens Anfordern der Aktivierungsmail  und viel PN geschwafel den Rahmen des täglichen Mailkontingents gesprengt.

**Comment by Ston3s** [comment]
Tatsache die Seite ist wieder online, zwar noch nicht für alle geöffnet aber zumindest online...

**Comment by Kukolorus** [comment]
Oh, sehe es auch gerade!

**Comment by Ron801** [comment]
Super. Können wir dann die FAQ auf der HP einarbeiten?

**Comment by Kukolorus** [comment]
In dem "alten" Forum gab es ja auch eine Anleitung wie man Site-Plugins selber schreibt und sie in xStream einbetten kann. 

Wäre es vielleicht Sinnvoll dieses (mit Erlaubnis von @Lynx187) im FAQ einzubauen? 
So hätte man vielleicht mir Überblick und alles wäre Zentral.

Meinungen?

**Comment by seberoth** [comment]
Freut mich auch, dass das Forum wieder Online geht. Meine Lösung ist auch nicht für sowas ausgelegt und war ja nur für den "internen" gebrauch gedacht, was wohl ein paar nicht verstanden haben...

**Comment by Ron801** [comment]
Das Forum ist wieder voll da!!!!
