### ISSUE TITLE
KKiste und Kinoleak

### ISSUE THREAD

**Issue by Kukolorus** [StoneOffStones/plugin.video.xstream#55]
Hallo, 

also momentan funktionieren alle Site Plugins ja mehr oder weniger relativ gut und problemlos :+1: 

Außer KKiste und Kinoleak, KKiste ist ja mal erreichbar, mal nicht und ich nehme mal an das es immer noch die Globale Suche stört. Kinoleak funktioniert ja immer noch nicht, und das seit bald einem viertel Jahr und es sieht nicht unbedingt danach aus ob es demnächst wieder funktionieren wird.

Meine Idee wäre es die beiden Sites vielleicht ins Backup zu verschieben, bei KKiste kann ja vielleicht noch eine Lösung gefunden werden bzw. kann man ja dort abwarten wie sich die Seite entwickelt. 

Kinoleak tut sich ja seit ner Ewigkeit nichts mehr und ist deswegen in meinen Augen doch momentan relativ Sinnlos es im Addon zu lassen..

**Meinungen?**

**Comment by Ston3s** [comment]
Das Site-Plugin funktioniert bei KinoLeak ja eigentlich.
Laut Lynx187 funktionieren nur noch wenige der gebotenen Links.
Solange die Seite noch online ist und das Site-Plugin läuft würde ich es noch drin lassen.
Wer will kann die Seite ja in de Einstellungen abwählen und wenn sie down sein sollte kann man immer noch ins Backup ziehen.

**Comment by Kukolorus** [comment]
Ok

**Comment by Ston3s** [comment]
Falls noch nicht vorhanden, bitte die Problematik zu Kiste detailliert mit betreffender Datei bzw. angehängter Log bereitstellen.
