### ISSUE TITLE
[HDFilme.tv] Filme regex error

### ISSUE THREAD

**Issue by sraedler** [StoneOffStones/plugin.video.xstream#60]
Bei HDFilme gehen keine Filme mehr, das regex findet immer ein episoden. Daher wird die falsche Methode geladen und ein error entsteht.

Beispiel.: "two" in die suche eingeben

**Comment by ghost** [comment]
Wird in 1 oder 2 stunden geprüft und (hoffentlich) gefixt

**Comment by ghost** [comment]
sollte so wieder gehen. Bitte mal prüfen und falls alles io ist bitte schließen

**Comment by seberoth** [comment]
EIn problem was ich grade sehe (wobei ich nicht überprüft habe, ob das immer so ist) ist, das es "var newlink..." bei mir nicht gibt, sondern "var hdfilme6..."

**Comment by Lynx187** [comment]
ne de regex ist inzwischen unabh. vom namen

**Comment by seberoth** [comment]
Wow... Sry... Bin lokal im falschem branch -.-

Das erklärt einiges...

**Comment by Ston3s** [comment]
Bei mir keine Fehlermeldung mehr.

**Comment by Ston3s** [comment]
zu?!

**Comment by ghost** [comment]
Ja jein. Die Lösung ist nicht ganz perfekt sieht commit von Lynx.

Lässt sich aber grade blöd lösen.Zurzeit geht man davon aus das nur Serien mehrere Links haben. Seit neustem gibt es aber quasi Verschiedenen Hoster.

Das müsste man irgend wie man lösen. Es ist (da die Seite wirklich nicht schön gemacht ist). Aber total schwere sagen ob es sich um eine Serie oder einen Film handelt.

Beispiel wäre hier:

hdfilme.tv/two-night-stand-2014-548-stream

Das nervige ist das man defacto den Link von "Server 1" und "Server 2" aufrufen muss damit sich die Variable für die Hoster ändert.

Alles in allen nicht gan so schön. Die jetzige Lösung deckt denke ich 90/95% ab. Aber es ist wie gesagt keine 100% Lösung.

Ich bin allgemein kein Fan davon wie die Seite programmiert ist (die Sortierung z.b geht garnicht). Aber die User scheinen sie ja zu mögen :'(

**Comment by ghost** [comment]
fixed im master
