### ISSUE TITLE
[KinoLeak] HosterPattern not proper working

### ISSUE THREAD

**Issue by sraedler** [StoneOffStones/plugin.video.xstream#61]
Das regex für die hoster selection ist nicht komplett funktionsfähig. 

Nachfolziehen: KinoLeak -> Animation -> Kung Fu Panda

Das Problem: Beim Regexparsen wird ebenfalls ''http://<img src='' in die liste genommen, was anschließend nicht zum hosternamen aufgelöst werden kann. Entweder muss in 170 das pattern angepasst werden oder nach 176 der url auf validität geprüft werden

**Comment by Ston3s** [comment]
Da es sowieso entfernt wurde kann das Thema aus zu.
