### ISSUE TITLE
bs.to: stolpert über lange bindestriche in den seriennamen

### ISSUE THREAD

**Issue by pjotrpottervogel** [StoneOffStones/plugin.video.xstream#64]
fehlermeldung:
UnicodeDecodeError:'ascii'codec can't decode byte 0xe2 in position 40: ordinal not in range(128) \plugin.video.xstream-nightly\resources\lib\logger.py",line 27, in __writeLog

xstream version: aktuelle nightly
os: win7

bs verwenden oft diese langen bindestriche, z.b: accused - eine frage der schuld, peaky blinders - gangs of birmingham, ...

**Comment by HvDaedalus** [comment]
Da mich nur anschließen. Das geht bei jedem Sonderzeichen/Umlaut so. Bsp: Ranma 1/2. Scheint ein Encoding Problem zu sein. Habe die loggerzeilen mal im Plugin auskommentiert, dann funzt alles.

**Comment by ghost** [comment]
Direkt alle raus zunehmen ist etwas mit dem Holzhammer ;)

Aber egal. Der Fehler wird wohl mit besagter Codierung zutun haben. Ich gucke heute Abend mal rein. Kann aber eigentlich nur einer dieser beiden sein:

https://github.com/StoneOffStones/plugin.video.xstream/blob/nightly/sites/bs_to.py#L155
https://github.com/StoneOffStones/plugin.video.xstream/blob/nightly/sites/bs_to.py#L188

Die anderen beiden Logger-Einträge sollte egal sein.

**Comment by Lynx187** [comment]
Man sollte eher auf die Zeile aus der Fehlermeldung achten. In diesem Fall wird nämlich ein bereits UTF-8 encodierter String nochmal encodiert.

**Comment by pjotrpottervogel** [comment]
habt ihr gut gemacht, danke - das funktioniert alles wieder!
