### ISSUE TITLE
Extra/Seperate addon-Id

### ISSUE THREAD

**Issue by Megachip** [StoneOffStones/plugin.video.xstream#66]
Hallö,

Warum nehmt ihr für die Beta bzw. Nightly nicht separate id's, z.b. -Beta und -Nightly, ähnlich wie es @sraedler schon getan hat. 
So kann der Nutzer "testen", ohne sich seine stable zu zerschießen...

Grüße, meg

**Comment by Ston3s** [comment]
Gibt mit der AutoUpdate Funktion Probleme.

**Comment by Megachip** [comment]
@StoneOffStones welche?
Baut sie doch einfach so dass die nightly autoupdate die updates (bzw. die zip) vom nightly zweig holt, die beta vom beta und... naja releases laufen ja eh übers repo...

**Comment by ghost** [comment]
Dein Gedanke ist nur leider nicht zuende gedacht. Sagen wir mal du hast ne Beta und stellst diese auf Nightly. Was passiert dann?

Wir hatten früher getrennte ID's und das führt wie von @StoneOffStones beschrieben zu Problemen mit dem AutoUpdate.Was der Grund war wieso wir die ID's wieder vereinheitlicht haben.

**Comment by Megachip** [comment]
@Viper2k4 ich muss jetzt gestehen, dass ich die aktuellen Versionen (und Optionen nicht kenne), ich wusste nicht, dass es einen Switch gibt. Ich hatte es eher für cleverer, 3 verschiedene Zweige (also auch addons) anzubieten, ohne einen Wechsel per option zu ermöglichen. 
Stell man sich einen Nutzer vor, der in der Release Version die option findet und sie einfach mal ausprobiert... und gerade dann ist die nightly defekt... Sie wird geladen, das Addon überschrieben und nix geht mehr... 
Aber ist nur nen Gedanke. Wenn es in-App nen Switch gibt, ergeben unterschiedliche IDs nat keinen Sinn.

**Comment by ghost** [comment]
Das ist eine Grundsatzdiskusion. Aber ein simples Beispiel ist Firefox.

Im Firefox kannst du auch auf Nightly stellen und wenn die aktuell Fehler enthält ist dem halt so. Stellt man ihn wieder auf Release wird er auch nicht Updaten bis die Release-Version neuer ist als die Nightly die zuletzt installiert wurde.

Das ist ein ganz üblicher Ablauf.

**Comment by Ston3s** [comment]
Thema abgeschlossen?!

**Comment by Ston3s** [comment]
Danke @viper2k4

**Comment by Ston3s** [comment]
Danke @viper2k4

**Comment by ghost** [comment]
Bitte Bitte ^^

??
