### ISSUE TITLE
SitePlugins werden nicht aktuallisiert (bei Addon-SubFolder)

### ISSUE THREAD

**Issue by ghost** [StoneOffStones/plugin.video.xstream#71]
Hi,

ich ein SitePlugin auswählen und hinzufüge oder entferne. Und dann mit der Zurücktaste (Backspace am PC oder zurück-button auf der FireTV). Wird die Liste nicht aktuallisiert und ich muss das Addon neu öffnen.

Klickt man auf "..." funktioniert alles.

@sraedler 
Das von dir angesprochene "updateDirectory()" bezieht sich aber auf die Directory() in dem der Eintrag ist und das ist in dem Fall dann nicht die Plugin-Liste.

**Comment by Lynx187** [comment]
Welche Kodi Version verwendest du denn, 16+?

**Comment by ghost** [comment]
15.2 (tritt aber wie gesagt nur bei der Versiob mit subfolder auf)

**Comment by sraedler** [comment]
bin grad nicht am pc, aber füg mal unter dem Update Directory das ein und Versuch es nochmals:

`xbmc.executebuiltin("XBMC.Container.Refresh")`

**Comment by Lynx187** [comment]
Es heisst`xbmc.executebuiltin("Container.Refresh")`, genau das macht UpdateDirectory.
Und richtig, die aktuelle Liste wird aktualisiert und die Plugin Übersicht ist in dem Fall nicht die aktuelle.

Generell sollte es wenn man ins Hauptmenü zurückwechselt aber trotzdem gehen. Auch wenn man über das Contextmenu in die Settings geht klappt das. Komisch.

**Comment by ghost** [comment]
Unterschied macht bei mir wie gesagt. Das "wie". Gehe ich über das Menü zurück sprich "..." funktioniert es. Gehe ich mit dem Zurück Button des jeweiligen System zurückt tut es das nicht.

Vermutlich ist es wirklich ein Kodi-Problem. Aber @sraedler  wollte nen Issue :)

**Comment by ghost** [comment]
Kodi 16.1 installiert Problem gone :)

**Comment by sraedler** [comment]
ja durch den issue ist das Problem jetzt besprochen und jeder informiert ;)
