### ISSUE TITLE
HDfilme.tv mehrere Server

### ISSUE THREAD

**Issue by Kukolorus** [StoneOffStones/plugin.video.xstream#72]
Hallo,

wenn man bei der oben genannten Seite einen Film öffnet kommt doch zuerst ein Fenster in welchem man die Qulität aussuchen kann. (Neuerdings) gibt es ja mehrere Server bei HdFilme über welche man den Film gucken kann. Solch eine Auswahl ist gar nicht im Plugin enthalten oder? Ich spiele darauf an falls auf den einen Server der Film nicht geht, jedoch auf einem anderen..

![asdasdasdasdasdasdasdasdasdas](https://cloud.githubusercontent.com/assets/18074507/14603433/e149dce8-056d-11e6-8190-4836931972bb.PNG)

Als Beispiel

**Comment by ghost** [comment]
Ich weiß ist mir auch schon aufgefallen:

https://github.com/Lynx187/plugin.video.xstream/pull/107

Siehe kommentar von vor 3 Tagen. Bin nur noch nicht dazu gekommen das einzubauen. Zurzeit bauen sie recht viele an der Seite irgendwie.

**Comment by Kukolorus** [comment]
Außerdem kann man ja jetzt wieder mit IPV6 Filme sehen. Mit den Cookies gibt es wohl manchmal Probleme, ist mir aber nicht aufgefallen.

**Comment by ghost** [comment]
Jemand ne Idee wie ich an die Links komme ohne alle 4 Links anzusurfen? Weil ne Auswahl-Liste mit:
- Server 1
- Server 2
- Server 3
- Openload

Sieht irgend wie auch komische aus. Zumal keiner weiß wo der Unterschied liegt. Problem ist aber das sich die Variable im Quelltext erst ändert wenn man die jeweilige Link ansurft.

PS:

Aber auch geil wie dumm die Seite ist. "Folgen 4". Einfach weil es 4 Hoster gibt ^^. Und Sortierung funktioniert immer noch nicht :/

**Comment by Kukolorus** [comment]
Wie meinst du das mit den Folgen 4 usw.?

Aber ja da muss ich dir zustimmen, die Grammatik ist auch sehr seltsam, als wäre sie vom Google Translator, was sie auch wahrscheinlich ist. Außerdem antworten die glaube auch nur English auf Deutsche Fragen, frage mich warum die dann deutsche Filme anbieten bzw. vertonte, das ergibt für mich ebenfalls wenig Sinn..

**Comment by Ston3s** [comment]
Was geschehen hier?

**Comment by ghost** [comment]
Ist im Master eingebaut
