### ISSUE TITLE
[DDL.ME] 'bool' is not iterable

### ISSUE THREAD

**Issue by sraedler** [StoneOffStones/plugin.video.xstream#73]
Bei ddl.me geht das Hall of Fame Feature nicht mehr. Fehler in Zeile 98, showEntries not iterable.

Edit: Ebenso gibt es sehr lange logzeileneinträge, die sehr langsam sind. Eine einzelne Zeile z.B. http://xbmclogs.com/pmvzx1rek

**Comment by ghost** [comment]
https://github.com/Lynx187/plugin.video.xstream/commit/ef859d7e72ea500f8dbad08e38fc8839d06078a4

**Comment by Ston3s** [comment]
Zu??
