### ISSUE TITLE
[GlobalSearch] Schlechte Darstellung

### ISSUE THREAD

**Issue by sraedler** [StoneOffStones/plugin.video.xstream#74]
Ich hab mal ein bisschen die neue Version getestet und mir fällt auf, dass die Globale Suche nicht schön ist. Wenn man z.B. "The Flash" sucht, ist die Darstellung so: https://snag.gy/P8EpCc.jpg

Ich finde wir sollte das Irgendwie schöner gestallten. Oder ist die Umstrukturierung noch ein Thema?

**Comment by ghost** [comment]
https://github.com/Lynx187/plugin.video.xstream/issues/55

^^

**Comment by sraedler** [comment]
oh^^

sollte man evtl. mal angehen oder ?

**Comment by Ston3s** [comment]
Finde ich auch recht unübersichtlich.
Vor allem weil als Indikator bei der Suche die Site-ID dient und diese bei einigen Seiten nichtmal der aktuellen tatsächlichen Domain darstellt.

Es wäre viel übersichtlicher wenn zuerst Ordner  für die die einzelnen Site-Plugins mit verfügbaren Suchergebnissen sichtbar wären und da drin ist dann der Content.
Man hat ja sowieso seine Favoriten ;)

Außerdem ist mir aufgefallen, dass wenn ich die Globale Suche verwende und danach die Auswahl wieder verlasse mir jedesmal die Viewtypes zerschossen werden.

**Comment by sraedler** [comment]
ne, Ordner finde ich nicht gut, ist viel zu viel geklicke...

eher eine Separierung, so wie es bei den Settings beim einstellen der Site Plugins ist...

**Comment by Ston3s** [comment]
Mmmhh, kann ich mir zwar nicht so recht vorstellen aber ich lasse mich gern davon überzeugen.
Könntest du es vielleicht detaillierter erläutern...

**Comment by ghost** [comment]
Ich finde einfach die Alte Version vor dem Threading toll :)

Movie4k
Film1
Film2
Film3
Kinox.to
Film1
Film3

usw.

**Comment by Ston3s** [comment]
Stimmt das würde auch gehen. Hilft einem aber nur wenig in Sachen Übersichtlichkeit wenn der jeweilige Skin keine Listenansicht anbietet!

**Comment by Ston3s** [comment]
Auch weil es bei einigen Site-Plugins sowieso recht unübersichtlich gestaltet ist da unzählige Suchergebnisse mit selben Namen vorhanden sind wie z.B. bei Filmpalast.

**Comment by StoneOffStones** [comment]
Hey Leute,  

mir ist auch in Bezug auf die Global Search Funktion aufgefallen das es die Ergebnisse nicht vernünftig dargestellt werden.
Also wenn ich in einem Skin sonst überall den Poster-View gewählt habe und diesen auch eigentlich bei den Global-Search Ergebnissen hätte geht das aktuell nicht wirklich.
Da der Viehtype meines wissens aktuell nicht dafür erzwungen werden kann.
Also werden die gefundenen Cover in zu breit oder nur teilweise dargestellt da falscher Viehtype standardmäßig von Kodi verwendet wird.

Des Weiteren ist mir auch aufgefallen, dass wenn ich den Viehtype der Ergebnisse auf den von mir gewünschten anpasse, diese Anpassung auch fehlerhafter weise zurück ins Hauptmenü übernommen wird!

Theoretisch müsste dieses Problem aus der Welt sein wenn man zwei neue Reiter in den Einstellungen unter Views hätte.
Und zwar Default-View für die Hauptansicht und die Ordnerstruktur bis zu den Streaming-Inhalten und natürlich noch eine Einstellung für den GlobalSearch-View.

Oder?!

**Comment by Ston3s** [comment]
Besteht das Problem noch?!
