### ISSUE TITLE
HDFilme.tv: Wildcardsuche

### ISSUE THREAD

**Issue by ghost** [StoneOffStones/plugin.video.xstream#76]
Siehe:

http://xstream-addon.square7.ch/showthread.php?tid=652&pid=3591#pid3591

Was meint ihr?

**Comment by sraedler** [comment]
Ich würde generell bei allen Seiten Wildcards erlauben, die gestallten die Suche nämlich einfacher...

**Comment by Ston3s** [comment]
Fände ich auch super...

**Comment by sraedler** [comment]
Sollte auch gemacht werden, sucht mal nach _ever*_ bei der globalen suche, da kommt ein bug zur Geltung

**Comment by Lynx187** [comment]
Ja der beliebte Spezualfall wenn es kein Suchergebnis bei m4k gibt.
Dort ist die Wildcard übrigens % und schon eingebaut.
Verhält sich bei mehr als einem Wort allerdings auch anders als erwartet.

**Comment by Ston3s** [comment]
Hab gesehen das eine extra Branch für fix-m4k versucht wurde zu erstellen.
Bitte Änderungen in Nightly einbringen.
Würde danach rebase vollziehen und PR erstellen

**Comment by ghost** [comment]
Ja habes nicht hinbekommen. Habe für movie4k und hdfilme.tv jetzt so pullrequest gemacht:

https://github.com/Lynx187/plugin.video.xstream/pull/123
https://github.com/Lynx187/plugin.video.xstream/pull/124

Wir sollten öfters ne rebase machen wenn es change in der Master gab^^

**Comment by Ston3s** [comment]
So rum verstehe ich den Sinn der Rebase-Funktion nicht wirklich!

**Comment by ghost** [comment]
ich weiß einfach nicht wie es geht ^^.

Habe ne neue Branche gemacht nur dann waren dort andere Commits mit drin :/

**Comment by Ston3s** [comment]
Einfach in die Nightly einarbeiten ;)
Solange es nur ein Thema bzw. zusammengehörige Themen gibt ist alles gut!

Nächstes Thema kann ja immer noch wie von dir immergrünen Branch vorbereitet werden und dann wenn soweit ebenfalls in die Nightly.

**Comment by Ston3s** [comment]
Wie sieht es bei in der Sache aus, schon was passiert?
Vielleicht könnte man doch erst die Änderung in die Nightly einbringen, damit es wenigstens erprobt werden kann?!

Auch weil das Thema hier diskutiert wird und ganz wo anders adressiert wird. Past ja auch nicht so ganz...

**Comment by ghost** [comment]
Ja der PR ist halt noch nicht angenommen. Kannst ja nen Merge mit meinen Branches machen :)

**Comment by Ston3s** [comment]
Ja bitte...

Irgendwie passiert sonst recht wenig, deshalb doch vielleicht lieber gemeinsam in der Nightly entwickeln ;)

**Comment by Ston3s** [comment]
Hab die Änderungen jetzt mal händisch eingefügt.
Aber komischerweise waren es nicht die selben Zeilen wie in der Master?!

**Comment by ghost** [comment]
darum mit Merges usw. Arbeiten :/. Das die Zeilen nicht Stimmen liegt dadran das doch letzten neuen Sachen eingebaut wurden. Dadurch hast du es total falsch eingebaut. Die Änderung gehört nicht in "showSearch" sondern in "_search"

Zumal die Änderungen grade in Lynx187's-Branche aufgenommen wurden.

Habe dein Commit mal gefixt. Aber lass sowas bitte anders machen.

**Comment by Ston3s** [comment]
Ok, neue Vorgehensweise hast du ja eindrücklich und logisch beschrieben. Bin auch dafür!

Mir hat es nur etwas zu lang gedauert um es zu erproben ;)

**Comment by Ston3s** [comment]
Besteht das Problem dann noch oder muss noch bei anderen Seiten hinzugefügt werden?

**Comment by ghost** [comment]
Mit dem Update vesteht kein Problem mehr und aknn zu gemacht werden.
