### ISSUE TITLE
Zentralisierte Einstellung in 2.2.0

### ISSUE THREAD

**Issue by Ron801** [StoneOffStones/plugin.video.xstream#77]
Was macht diese Funktion genau?Erkenne keinen Unterschied wenn Ein oder Aus.

**Comment by Ston3s** [comment]
Ist kein Issue!
Wenn aus dann hast du drei Settings-Ordner im Hauptmenü wenn an dann nur einen. Die spezifischen Settings zu xStream, URLResolver und Metahandler sind im Ordner "Settings" integriert.
