### ISSUE TITLE
UpdateManager Update Quelle nicht wählbar

### ISSUE THREAD

**Issue by sraedler** [StoneOffStones/plugin.video.xstream#8]
Im moment kann der UpdateManager nur vom Beta Branch updaten, da der Url im code hard codiert ist.

Dies sollte durch eine Einstellung mit branchnamen oder durch ein Bool wählbar sein, ob beta oder master branch zum Updaten verwendet wird.

Was würdet ihr wählen?

**Comment by Ston3s** [comment]
Bin für die Master/Beta Variante.
Ist eine sehr gute Idee, darüber habe ich mir auch bereits Gedanken gemacht weil diese Frage wieder interessant geworden wäre wenn man aus der Beta in die Master mergen wollte.

Ob man es jetzt Master oder Stable nennen würde ist eine Frage ;)

**Comment by sraedler** [comment]
Ja beim mergen muss zusätzlich vom fork auf base umgestellt werden (@StoneOffStones zu @Lynx187)

oder man codiert wieder hard in den UpdateManager, dass Master @Lynx187 ist und Beta deine @StoneOffStones Beta Branch

**Comment by Ston3s** [comment]
Ne das Problem meinte ich ja!
Es macht keinen Sinn bei jeder neuen Version neu zu codieren. Die Einstellung ist die schönere und bessere Variante ;)

**Comment by sraedler** [comment]
ok, dann werde ich das einbauen!

**Comment by Lynx187** [comment]
Das finde ich nur dann ok wenn aus dem log eindeutig hervorgeht wo die Updates gerade herkommen.
Ich habe nämlich keine Lust auch noch Fragen zu irgendwelchen Forks zu beantworten, die ich wenn überhaupt nur halb auf dem Schirm habe.
Am Besten sollte vor dem Download aus dieser oder evtl. aus beiden Quellen auch noch ein entsprechender Hinweis kommen dass man eher einen Zwischenstand läd etc.

**Comment by Ston3s** [comment]
Zusätzlich kann man ja Einstellung standardmäßig auf Master stellen.
Dann müsste man nicht vor dem PR umstellen.

**Comment by sraedler** [comment]
ok, dann mach ich das mal so:
1. default ist master branch
2. es gibt nur ein bool, das zwischen "hier" und Lynx187 umstellt
3. Logging des Repo URLs inklusive Version
4. Darstellung für den Benutzer welcher Branch geladen wird

**Comment by sraedler** [comment]
Hab diese "Features" eingebaut siehe #11 

Falls dies passt kann dieser Issue geschlossen werden.

**Comment by Ston3s** [comment]
Hallo, 

mir ist heute noch eine Sache aufgefallen.
Ist das gewollt, dass in den Einstellungen zweimal xStream AutoUpdate steht?
Wie und wo kann man eigentlich zwischen den den Master und Beta auswählen?

**Comment by sraedler** [comment]
ah nein, das ist ein bug vom testen, den ich leider gepusht hab!

werde es nachher fixen, sorry!

Edit: Es sollte nach PR #12 funktionieren, wurde durch ein fehlcommit beim testen des updates geändert.

Die Setting ist ganz normal wie die Auto-Update ein- und ausschaltbar in den xStream-Einstellungen

**Comment by StoneOffStones** [comment]
Super!
Und wo wähle die Master bzw. Beta Quelle aus?

**Comment by Ston3s** [comment]
Danke, jetzt ist es richtig.

Heute ist mir der Gedanke gekommen das es vielleicht noch besser wäre wenn ein eigener Punkt "Update" im Menü der Einstellungen ist. Dort könnte man dann gezielt die Themen auswählen.
- AutoUpdate
- Beta-Version zur Entwicklung

**Comment by Ston3s** [comment]
Was denkst du?

**Comment by sraedler** [comment]
ja hab ich auch schon gedacht, können wir auch machen, ist ja schnell gemacht...

zusätzlich muss ich noch etwas finden, dass der Fortschrittbalken den Downloadfortschritt ebenso darstellt und nicht nur das entpacken

**Comment by Lynx187** [comment]
Warum nicht ein Settingt mit 3 Optionen off|master|beta
Fortschrittsbalken so richtig für den Download geht mit urlretrieve eher nicht. Aber du könntest den Downloader nutzen den es schon in xStream gibt. Müsste ggf. noch etwas erweitert werden, der zeigt den Downloadfortschritt an.

**Comment by sraedler** [comment]
ja, drei Optionen klingt auch sehr gut!

muss ich mal schauen wie das geht...

ich hätte urlretrieve jetzt so gemacht:

https://blog.shichao.io/2012/10/04/progress_speed_indicator_for_urlretrieve_in_python.html

aber natürlich nur um den prozentsatz zu bekommen...

**Comment by Ston3s** [comment]
Das mit den drei Optionen hört sich gut an.
Noch schöner da ein Fenster welches aufkommt in dem man dann die Option auswählt. Nur die ausgewählte Option würde dann am Ende angezeigt werden.

Prozentangabe ist cool aber Donloadbalken ist nochmal besser ;)

**Comment by Lynx187** [comment]
Ok dann ist das mit urlretrieve auch möglich, aber warum doppelt machen.

Das was Kodi bereits für solche Optionen anbietet reicht auch aus.

**Comment by sraedler** [comment]
ok, dann mach ich das mit der download.py lib....

aber hab grad nicht so viel zeit, kann also noch ein bisschen dauern....

**Comment by Ston3s** [comment]
Da wartet man doch gerne ;)

**Comment by sraedler** [comment]
Ich hab da jetzt einen ganz blöden Bug drin und weiß nicht warum bzw. kann ihn nicht wirklich nachvollziehen.

Es wird nach dem Update wenn alles fertig ist nochmal das File gedownloaded. Weiß aber nicht warum, evtl. weil der Updatemanager überschrieben wird und daher neugeladen, aber das weiß ich nicht.

Kann jemand schauen ob ich einen simplen Fehler gemacht hab?

**Comment by StoneOffStones** [comment]
Ok, dann muss man mal schauen wie das mit den Tags im Detail funktioniert...

**Comment by sraedler** [comment]
Denk das ist jetzt gelöst und kann geschlossen werden, siehe #15
