### ISSUE TITLE
Filmpalast Icon

### ISSUE THREAD

**Issue by Kukolorus** [StoneOffStones/plugin.video.xstream#81]
Hallo, 

wollte mal fragen ob jemand der mit Bildbearbeitung und Co. umgehen kann vielleicht nochmal das Icon von Fimpalast ändern könnte sodass es nochmal schärfer ist, da es noch als einziges ziemlich unscharf aussieht. Der Fehler ist jetzt mehr Kosmetisch^^ :)

**Comment by Ston3s** [comment]
Leider ist kein besseres Bildmaterial verfügbar!
Wenn du mir das entsprechende Material zur Verfügung stellst kann ich es gerne anpassen.

Außerdem sieht es selbst auf meinem großen 52 Zoll TV noch recht gut aus...

**Comment by Ston3s** [comment]
Wenn kein Material zur Verfügung steht bitte schließen
