### ISSUE TITLE
[Settings] Hosterauswahl Groß-/Kleinschreibung

### ISSUE THREAD

**Issue by Ston3s** [StoneOffStones/plugin.video.xstream#82]
Hallo zusammen,

habe mich zuletzt mit der Darstellung und Formulierung der Settings beschäftigt.
Es wurde soweit fast alles angepasst und jetzt bleibt noch eine Kleinigkeit.
Für die Hosterauswahl wird noch **dialog / list / auto** so wie hier klein geschrieben angezeigt.
Jetzt hab ich gelernt das man nicht einfach bei Settingspunkten mit **type="labelenum"** die Schreibweise anpassen darf.

![bildschirmfoto 2016-05-12 um 16 59 49](https://cloud.githubusercontent.com/assets/12751497/15219708/0ed5ab92-1865-11e6-8d0b-49d6db2de496.png)

Wie könnte ich jetzt trotzdem **D**ialog / **L**ist / **A**uto anzeigen lassen. die Eintrag in den Settings muss sich doch auf eine Andere Datei/Code beziehen und dort müsste man doch dies anpassen.
Oder habe ich da einen Denkfehler bzw. gibt es eine andere Möglichkeit.

Danke für jeden Tipp!!!

**Comment by ghost** [comment]
Das liegt an den Abfragen im Cod siehe:

https://github.com/StoneOffStones/plugin.video.xstream/blob/master/resources/lib/gui/hoster.py#L280

Dort wird der eintrag abgefragt. Und es wird halt auf "list" geprüft. Wenn du jetzt "List" draus machst ist "List" halt nicht mehr" "list".

Das heißt du musst bei Solchen Änderungen halt auch den Code anpassen.

**Comment by StoneOffStones** [comment]
Sowas hab ich mir schon gedacht nur ich wusste nicht wo ich zu suchen habe...

**Comment by Ston3s** [comment]
Sowas hab ich mir schon gedacht nur ich wusste nicht wo ich zu suchen habe.
https://github.com/StoneOffStones/plugin.video.xstream/commit/e939a47bc025e7992bee5685836fbdf27aac50aa 
Habe jetzt List und Dialog nach meiner Einschätzung angepasst, passt das so und wo finde ich die auto-Funktion? 

Anpassung in den Settings folgt natürlich auch noch, sobald ich weiß das ich richtig unterwegs bin ;)

**Comment by ghost** [comment]
Da hast du z.b viele zu viel geändert :) (Siehe Kommentare im commit).

Such einfach mal im Code danach:

https://github.com/Lynx187/plugin.video.xstream/search?utf8=%E2%9C%93&q=hosterSelect

Hier siehst du wo die Einstellung "hosterSelect" abgefragt wird. Und genau dort musst du es auch ändern. Dort siehst du auch gut 2x auf "auto" und 1x auf "list" geprüft wird.

PS:

Mach sonne Test Änderungen mal in ner neuen Branch und Merge die später. Weil durch das Auto-Update bekommt jeder der jetzt Nightly eingestellt hat ne neue Version die ggf. nicht mehr funktioniert ^^

Ne eigene Branch eigenet sich auch besser zum Pull nach Lynx187 ;)

**Comment by Ston3s** [comment]
Danke für den Tipp, wieder ien wenig mehr die zusammenhänge verstanden!

Habe aktuell nur begrenzte möglichkeiten, deshalb korrigiere ich es diesmal noch in der nightly, beim nächten verscuh wird eine eigene Branch erzeugt.

Kannst du mal kurz checken/erproben ob es jetzt passt?!
Wenn i.O. kann direkt geschlossen werden ;)

**Comment by ghost** [comment]
Kein Kodi hier :)

Testen es doch selbst durhc umstellen ob sich was ändert dann weißt du es :)

**Comment by Ston3s** [comment]
Kein Kodi hier ;)

**Comment by Ston3s** [comment]
So scheint zu funzen!
