### ISSUE TITLE
[Site-Plugin] Series-Section of Goldstream.org

### ISSUE THREAD

**Issue by Ston3s** [StoneOffStones/plugin.video.xstream#91]
Hallo zusammen,

leider hat anis3 etwas Probleme bei der Integration der Serien von Goldstream in das Site-Plugin.
Könntet ihr bitte an der Stelle unterstützen und den fleißigen Kerl weiterhelfen.

Ich/wir bedanken uns bereits im Vorfeld für jede Art von Hilfe!!!

**Comment by ghost** [comment]
Heho,

die Seite ist echt totoal dumm aufgebaut. Und ich weiß nicht ob sich der Aufwand für die Serien lohnt (sind im verhältniss recht wenig).

**Comment by Ston3s** [comment]
Serien sind jetzt drin!

Jetzt fehlen noch die Cover. Aktuell werden diese von der Seite bei reaktiviertem Metahandler nicht gezogen wie z.B. bei BurningSeries und vielen anderen...

Extra Issue?!
