### ISSUE TITLE
[Krypton] Globale Suche liefert kein Ergebniss

### ISSUE THREAD

**Issue by ghost** [StoneOffStones/plugin.video.xstream#92]
Globale Suche bricht manchmal ab und leifert dann keine Ergebniss. Anscheinend bricht Kodi den Task ab:
LOG-Eintrag:

`10:23:50 T:5384   ERROR: CPythonInvoker(47, C:\Users\alexa\AppData\Roaming\Kodi\addons\plugin.video.xstream\default.py): script didn't stop in 5 seconds - let's kill it`

Ich glaube das selbe tritt beim aktivierten Metahandler auch auf wenn man eine normale Liste öffnen

**Comment by Lynx187** [comment]
Kodi konnte schon immer python scripte nach einer Weile beenden. Da das gerade mal eine Alpha Version ist kann sich noch viel ändern.

**Comment by ghost** [comment]
Kann man Kodi nicht auf irgend einer Art und Weise mitteilen das eine Aktion länger dauert?

**Comment by Lynx187** [comment]
Nicht explizit, zumindest nicht das ich wüsste. Evtl. weiss Kodi dass da noch was kommt wenn man mit der Api interagiert, aber das passiert ja eigentlich durch die Dialoge. 
Aber wie gesagt nur weil es bei einer Alpha nicht ganz klappt muss man sich noch keinen Kopf machen.

**Comment by Lynx187** [comment]
Mal nen Neustart gemacht? Danach war das Problem bei langen Laufzeiten bei mir erledigt.

**Comment by ghost** [comment]
jo teste auch grade etwas. Bis jetzt der Fehler auch nicht weiter aufgetretten. Der Metahandler hängt gelegentlich mal. Aber die Sucher liefert aktuelle auch bei langen Listen wie "Test".

**Comment by Kukolorus** [comment]
Also ich habe jetzt mal Kodi 17 Alpha 3 installiert und bei mir geht die Globale Suche und liefert Ergebnisse.

**Comment by Ston3s** [comment]
schließen?!

**Comment by ghost** [comment]
Teste es doch einfach selbst mehrmals und falls es nicht auftritt mach es zu :)

Wie Lynx schon sagt ist ne Alpha. Kann also durchaus sein das es gefixed wurde.

**Comment by Ston3s** [comment]
Habe es gestern sporadisch getestet, da hat es ein, zwei mal geklappt.
Hatte auf ein wenig mehr Feedback gehofft!

**Comment by ghost** [comment]
Naja ich habe das Issue aufgemacht weil Kodi öfters kein Ergebniss geliefert hat weil es die action gestopt hat. Wenn das jetzt funktioniet ist es ja super :)

Einfache alle Seiten aktivieren, ne suche nach "Test" machen und gucken ob nen ergebniss kommt. Falls ein kommt haben sie ggf. was ändernt.

**Comment by ghost** [comment]
Ich hatte den Fehler seit Ewigkeiten nicht mehr. Ich mach das mal zu ^^
