### ISSUE TITLE
Kodi 17-Bug-Tracking

### ISSUE THREAD

**Issue by ghost** [StoneOffStones/plugin.video.xstream#93]
Ich finde wir sollte die Bugs und Probleme die sich mit Kodi 17 ergeben hier bündeln.
- Globale Suche liefert kein Ergebniss #92
- Default-Skin zeigt kein Poster https://github.com/Lynx187/plugin.video.xstream/pull/137

PS:

Für neue Probleme bitte in neues Issue erstellen und hier Nachtragen. Wird ein Problem gelöst/abgeschlossen bitte ~~Durchstreichen~~ (siehe Markdown).

**Comment by Lynx187** [comment]
Sind dazu nicht schon die Issues da... + Label +ggf. Milestone

**Comment by ghost** [comment]
Joar fand es nur irgend wie cool wie z.b hier bei https://github.com/MahApps/MahApps.Metro/ in der PR's^^

**Comment by Lynx187** [comment]
Ja gut wenn der PR Ersteller die selber abhakt ist das ja auch sinnvioll. Dieser hat ja in der Regel keinen Zugriff auf die Tags und MS des Repos and das er den PR gerichtet hat.
