### ISSUE TITLE
Diverse Bugs

### ISSUE THREAD

**Issue by sraedler** [StoneOffStones/plugin.video.xstream#94]
Hab mal alle Plugins ein bisschen durchgeklickt und folgendes gefunden, denk man könnte es nach und nach abarbeiten
-  [x] CineDream: Beim Suchtext "Flash" wird FAQ angezeigt, was nicht geht
  - [x] es gibt noch mehr Problemseiten http://www.cine-dream.net/?s=kontakt
-  [x] DieFilme: ~~Bei Serien mit Folgen oder Staffen über 10 gibt es ein Sortierproblem. Es wäre gut wenn wir vor die einstelligen Zahlen eine 0 einfügen~~ Sortierung wählen reicht schon
-  [x] KinoKiste: klicke bei der Hosterwahl auf "Abbrechen" --> "AttributError: 'xbmc.Dialog' object has no Attribute 'close'"
-  [x] Movie4k: Genre (Serien), TopSerien und AlleSerien geht nicht
- [x]  Seriesever: 
  -  [x] Serien sollte in "Alle Serien" umbenannt werden, da der Name sonst verwirrend ist.
  -  [x]  Filme gehen nicht (schätze ein regex problem)
-  [x] Streamtausch: 
  -  [x]  ~~Neue Filme geht nicht~~ Firewallblockierung
  -  [x]  ~~Genre geht nicht~~ Firewallblockierung
  -  [x] Suche: "flash" --> FAQ wird angezeigt
- [x] Generell:
  -  [x] Es gibt bei allen Seiten diese Logwarning: 

> 10:52:31 T:4824 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.xstream/?site=filmpalast_to&function=showHosters&title=The+Flash+S02E15&mediaType=movie&MovieTitle=The+Flash+S02E15&thumb=http%3A%2F%2Ffilmpalast.to%2F%2Ffiles%2Fmovies%2F315%2Fthe-flash-s02e15.jpg&entryUrl=http%3A%2F%2Ffilmpalast.to%2Fmovies%2Fview%2Fthe-flash-s02e15&playMode=play
- [x]  Sporadisch kommt ein Fehler dass die Wiedergabe nicht möglich ist (Das ist der wichtigste Bug, denn man fixen muss, denn das ist extrem nervig, wenn man auf abbrechen klickt weil kein passender hoster dabei ist!!!).

> 11:01:38 T:11920   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.xstream/?site=movie4k_to&function=showHosters&title=100.000+Dollar+In+Der+Sonne&mediaType=movie&sMovieTitle=100.000+Dollar+In+Der+Sonne&MovieTitle=100.000+Dollar+In+Der+Sonne&thumb=https%3A%2F%2Fmovie4k.tv%2Fthumbs%2Fcover-2706217-100-000-Dollar-in-der-Sonne-movie4k-film.jpg&sUrl=http%3A%2F%2Fwww.movie4k.me%2Fn-100-000-Dollar-in-der-Sonne-online-film-6465001.html&playMode=play]

**Comment by Ston3s** [comment]
Updates könnten gleich in die Beta3 integriert werden ;)

**Comment by sraedler** [comment]
naja, würde es erst dann 1-2 tage so laufen lassen, weil die nightly zum testen ist und die beta nur vorstufe für die finale.

und es müssen erst mal alle punkte gemacht werden ;)

**Comment by Ston3s** [comment]
Das ist klar, wollte nur drauf hinweisen, dass die  Änderungen dann auch noch in die Beta3 könnten ;)

**Comment by Lynx187** [comment]
Zu den generellen Punkten hatte ich schon mal erwähnt, dass das an Kodi liegt.
Dazu müsste man Kodi sagen dass der Eintrag nicht abspielbar ist (selection mode "List" wählen), dann muss man aber auf z.B. resume playback verzichten (oder es selbst implementieren) und bei einigen Skins (z.B. Confluence) darauf dass in allen Views alle Metadaten angezeigt werden.

**Comment by sraedler** [comment]
Ok, das war mir nicht bekannt.

Aber schade, dass es nicht geht.

Hast du schon mit ihnen geschrieben?

**Comment by Lynx187** [comment]
Mit wem? Denen von Kodi? Ist bekannt hat aber keine Priorität.

**Comment by sraedler** [comment]
nun sollten alle Änderungen gemacht sein, bitte testen

**Comment by Kukolorus** [comment]
Meinst du mit 

" Sporadisch kommt ein Fehler dass die Wiedergabe nicht möglich ist (Das ist der wichtigste Bug, denn man fixen muss, denn das ist extrem nervig, wenn man auf abbrechen klickt weil kein passender hoster dabei ist!!!)."

das wenn man auf Abrechen klickt, Kodi stehen bleibt? Ist bei mir so :(

Und ich hätte mal eine Frage. Bei mir geht eine movie4k Seite nicht, und zwar die .to Seite. Gehen tut sie im Browser noch aber ich glaube die haben nun eine andere/neue Domain namens Movie.to welche auch https benutzt. Weiß jetzt nicht, ob das wichtig ist. Wollte es mit movie4k nur mal erwähnen :)

**Comment by sraedler** [comment]
Ich hab viper schon geschrieben, weil ich mir nicht sicher bin ob man das ändern sollte.

Movie4k und kinox haben jetzt nämlich einige neue domains und z.B. movie4k eine zufalls serie/film option. Dies sollte man natürlich irgendwann integrieren.

Ich hab nur grad nicht mehr die 2.7.9-2.7.11 python auf dem pc und krieg es nicht geupdated, drum kann ich da nicht weiter machen.
Und ich find auch irgendwie nicht wie ich das updaten könnte (in kodi)

**Comment by Ston3s** [comment]
Ich sehe hier war man fleißig!
Wenn alles erledigt und erprobt wurde bitte in die Beta übernehmen.

Danke!

**Comment by sraedler** [comment]
übernimm du das bitte

**Comment by Ston3s** [comment]
Änderungen wurden Übernommen!
Kann jetzt geschlossen werden oder?
