### ISSUE TITLE
[Updater] Error on older OpenElec-Versions

### ISSUE THREAD

**Issue by ghost** [StoneOffStones/plugin.video.xstream#98]
Heho,

scheint unter alten Kodi versionen ein Problem mit dem Updater zu geben:

http://xstream-addon.square7.ch/showthread.php?tid=724&pid=4451#pid4451

Wenn man danach googelt findet man auch ein bei Einträge zu anderen Addons die das Problem haben. Es gibt im endeffekt zwei Varianten:
- Try catch und ne Meldung ausgeben das der Updater Kodi... vorrausetzt
- workaround finden :)

Könnte aber auch ein Problem von OpenElec ansich sein. Problem ist wohl das "distutils.version" benutzt wird.

Grß

_EDIT_

@sraedler ich habe denke ich einen guten Workaround gefunden:

https://github.com/ruuk/service.xbmc.tts/blob/master/service.py#L188

Dort wird der Import geprüft und eine Fallback "LooseVersion" definiert. Mit der dann gearbeitet wird. Ich denke das könnte unser Problem hier fixen.

Guckst dir das mal an?

**Comment by Lynx187** [comment]
Bei OpenElec 5 wurde distutils entfernt, was eigentlich Standardbestandteil von Python ist. Also entweder Downgrade auf 4 oder Upgrade und hoffen dass es bei >5 wieder dabei war/ist.
Wenn man jetzt für alles mögliche eine Fallbackimplementierung mitführen will kann man ja gleich die nutzen, falls sie sich denn wirklich identisch verhält.

**Comment by ghost** [comment]
Sicher könnte man auch direkt die LooseVersion aus dem Fallback nehmen. Ich denke mal die Intuition da hinter war soweit es geht den Originalen Code (distutils) zu benutzen und nur im Ernstfall den Fallback. Ggf. Arbeite der Fallback auch in 99% der Fälle, wer weiß (habe ihn nicht weiter angesehen). Jedoch würde ich auch eher den Weg gehen der dort eingeschlagen wurde.

Und im Endeffekt könnte man den Code ja fast 1:1 übernehmen (wenn es auch nicht grade die feine englisch Art ist^^)

**Comment by sraedler** [comment]
Alternativ könnte man auch einfach die distutils.version in den lib ordner kopieren, dann muss man nur den import anpassen.

http://svn.python.org/projects/python/tags/r32rc1/Lib/distutils/version.py

**Comment by ghost** [comment]
Das würde ich nicht tun. Damit schleppen wir uns selbst ja ne Abhänigkeit mit rum. Wir bekommen Updates ja nicht wirklich mit.

Wie gesagt die Fallback Version ist eigentlich Wasserdicht. Damit benutzen wir immer die passende distutils des Systems und falls diese halt nicht vorliegen unser Fallback.

**Comment by sraedler** [comment]
Naja, seit 2 jahren wurde daran nichts mehr geändert, was auch zukünftig nicht so wahrscheinlich ist.

https://hg.python.org/distlib/file/tip/distlib/version.py

aber mir ist es egal, wie es machen willst

**Comment by ghost** [comment]
Naja und morgen kommt nen Update! Man hat schon Pferde kotzen sehen ;)

Direkt was machen wollte ich erstmal nicht ^^ ( sonst hätt ich kein Issue gemacht ;) ). Ich persönlich würde nur vorschlagen den Fallback-Code da 1:1 zu übernehmen. Das sollte eigentlich auch recht fix gemacht sein:

[Dort](https://github.com/StoneOffStones/plugin.video.xstream/blob/master/resources/lib/updateManager.py#L10)  das `as V` entfernen

[Hier](https://github.com/StoneOffStones/plugin.video.xstream/blob/master/resources/lib/updateManager.py#L65) und [da](https://github.com/StoneOffStones/plugin.video.xstream/blob/master/resources/lib/updateManager.py#L94) halt `LooseVersion` statt `V` benutzen

Und das hier:

```
try:
    #Fails on Helix beta 1 on OpenElec #1103
    from distutils.version import LooseVersion
except ImportError:
    def LooseVersion(v):
        comp = [int(x) for x in re.split(r'a|b',v)[0].split(".")]
        fourth = 2
        fifth = 0
        if 'b' in v:
            fourth = 1
            fifth = int(v.split('b')[-1] or 0)
        elif 'a' in 'v':
            fourth = 0
            fifth = int(v.split('a')[-1] or 0)
        comp.append(fourth)
        comp.append(fifth)
        return comp
```

Grob [hier](https://github.com/StoneOffStones/plugin.video.xstream/blob/master/resources/lib/updateManager.py#L31) rein kopiere.

Das habe ich nicht getestet. Aber sollte EIGENTLICH funktionieren.

**Comment by Lynx187** [comment]
Wenn man da wirklich drauf eingehen will ist die version.py aus den distutils eines aktuellen Python 2.7 zu kopieren echt die einfachste Variante.  Welche Abhängigkeit meinst du da denn, abgesehen von re?
Und wenn ich mir den Fallback vorschlag so ansehen ist der bei der derzeitigen Versionsbenennenung eher nicht wasserdicht.

**Comment by ghost** [comment]
Mir ist das eh egal. Von mir aus reicht auch nen Try Catch um den Import und ne Fehlermeldung.

Naja externe Libs ins Addon zu holen find ich persönlich nicht so schön. Falls döse sich halt mal Updaten (ja ich weiß bis Lodi auf 3.0 geht, vergeht noch Zeit). Hängt man halt an der alten.

Falls das Fallback Mist ist. Könnte man nicht per Default das System distutils nehmen und nur als Fallback das interne? Dann hätte wir ne Lösung die alle mögen ^^

**Comment by sraedler** [comment]
ja, das ist eine gute Idee ;)

dachte auch schon, wenn es nicht vorhanden ist sollte es herunter geladen werden, aber das ist alles zu kompliziert.

daher würde ich auch den Distutils nehmen und wenn das nicht vorhanden ist die version.py aus der Lib laden

Edit:
Hab den "fallback" mal so eingebaut, passt das euch?

0ccd290

**Comment by ghost** [comment]
Jo genau so meinte ich das :)

Jemand lust OpenElec zu testen?^^ Oder wollen wir dem Kollegen vom thread fragen?

**Comment by ghost** [comment]
Sieht so aus, das es keine probleme mehr gibt. Falls ja öffnen wir es einfach wieder.
