### ISSUE TITLE
[GlobalSearch] Keine Einträge

### ISSUE THREAD

**Issue by sraedler** [StoneOffStones/plugin.video.xstream#99]
Wenn Plugins angehackt sind, die entweder nicht gehen oder keine Ergebnisse liefern, dann wird kein Ergebnis angezeigt

z.B. 'flash' suchen, kkiste findet nichts --> keine Ergebnisse

auch wenn nur funktionierende Seiten drin sind

**Comment by ghost** [comment]
Weißt wieso sowas kommt? ^^

https://github.com/StoneOffStones/plugin.video.xstream/blob/dc1879d23e68dd93e05d2b48ab45b90b647a7c48/sites/video4k_to.py#L80

:P.

Aber ohne zu sticheln. Das kommt meiner Meinung nach wenn das Plugin ist Liste schließt obwohl sie garnicht den "Handle" über die Liste hat. Was bei der Globalen-Suche der Fall ist.

**Comment by ghost** [comment]
Kann das zu?
